### ISSUE TITLE
How to use New-MgSiteContentType and New-MgSiteListContentType

### ISSUE THREAD

**Issue by AndersRask** [microsoftgraph/msgraph-sdk-powershell#1012]
Hi,

documentation on the recently added possibility to add contenttypes using graph is pretty sparse.

I played around with it a bit, but didn't get it to work:

`New-MgSiteContentType -SiteId $site.Id -ParentId 0x0101  #428 
New-MgSiteContentType_CreateExpanded: Missing or incorrect ParentId
 `

Here I am just trying to create a bare-bone CT inherited from base doc CT, where I add columns/columnlinks later.
The error is a bit weird, as the root DocType should be valid.

I guess it would be nice with some samples with required parameters (the parameters does not say which are required!) and use cases like how to create a CT with links/cols to have something to go with

**Comment by peombwa** [comment]
@AndersRask, the [API reference page](https://docs.microsoft.com/en-us/graph/api/site-post-contenttypes?view=graph-rest-1.0&tabs=http) is a great starting point since the Microsoft Graph PowerShell commands are based on the API. Unfortunately, the [metadata](https://graph.microsoft.com/v1.0/$metadata) that the SDK is generated from isn't fully annotated to tell us which parameters are required, and which ones aren't. The service team is currently working on this, and a more accurate metadata will be available in there near future.

In this case, using the example in the [API reference page](https://docs.microsoft.com/en-us/graph/api/site-post-contenttypes?view=graph-rest-1.0&tabs=http), the command to create a site content type will be:
``` powershell
New-MgSiteContentType -SiteId $SiteId -Name "docSet" -Description "custom docset" -Base @{Name = "{NAME}"; Id = "{ID}" } -Group "Document Set Content Types"
```
You can use `Find-MgGraphCommand -Command "New-MgSiteContentType"` to find the API a command calls.

For API/service-related questions, please use https://developer.microsoft.com/en-us/graph/support.

**Comment by AndersRask** [comment]
> @AndersRask, the [API reference page](https://docs.microsoft.com/en-us/graph/api/site-post-contenttypes?view=graph-rest-1.0&tabs=http) is a great starting point since the Microsoft Graph PowerShell commands are based on the API. Unfortunately, the [metadata](https://graph.microsoft.com/v1.0/$metadata) that the SDK is generated from isn't fully annotated to tell us which parameters are required, and which ones aren't. The service team is currently working on this, and a more accurate metadata will be available in there near future.
> 
> In this case, using the example in the [API reference page](https://docs.microsoft.com/en-us/graph/api/site-post-contenttypes?view=graph-rest-1.0&tabs=http), the command to create a site content type will be:
> 
> ```powershell
> New-MgSiteContentType -SiteId $SiteId -Name "docSet" -Description "custom docset" -Base @{Name = "{NAME}"; Id = "{ID}" } -Group "Document Set Content Types"
> ```
> 
> You can use `Find-MgGraphCommand -Command "New-MgSiteContentType"` to find the API a command calls.
> 
> For API/service-related questions, please use https://developer.microsoft.com/en-us/graph/support.

Hi Peter,

thanx, that worked (except of course that the example in API reference uses the wrong docid :) )

While I agree that the API reference page has a lot of good info, I find the examples very lacking. As soon as you want to do something that is not straight forward, it is really frustratingly short on examples. I hope this changes over time, but as it is now it is barely usable.

It is really a shame, because both with the reference and this excellent module, it is a barrier to get people to use it, when there isn't any good examples and the usage is fairly complex :)

**Comment by peombwa** [comment]
@AndersRask, Thanks for the valuable feedback. We just added PowerShell snippets alongside the HTTP snippets in the API reference - https://docs.microsoft.com/en-us/graph/api/site-post-contenttypes?view=graph-rest-1.0&tabs=powershell. This should make it easier for customers to figure out how to use the commands.

We will continue improving our docs and discoverability of commands as part of #876.
