### ISSUE TITLE
Get-MGUser returns blank values for SignInActivity property

### ISSUE THREAD

**Issue by bobfrankly** [microsoftgraph/msgraph-sdk-powershell#1024]
Might be a revisit of #485 

Using the Beta profile:
``` PS
$try = Get-MGUser -userid user@domain.com
$try #returns

# LastNonInteractiveSignInDateTime LastNonInteractiveSignInRequestId LastSignInDateTime LastSignInRequestId
# -------------------------------- --------------------------------- ------------------ -------------------
```

Would expect values for these properties, but I'm not finding any.

**Comment by peombwa** [comment]
@bobfrankly, you need to explicitly `$select` SignInActivity, i.e., `-Property SignInActivity`. Please see the example in https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&tabs=powershell#example-3-get-users-including-their-last-sign-in-time.

**Comment by peombwa** [comment]
That's how the API currently works. The same call in Graph explorer with a UPN instead of a user id will fail with the same error. The SDK is just a mirror of the service.

You can open a service feature request at https://developer.microsoft.com/en-us/graph/support for the workload owners to look at.

**Comment by bobfrankly** [comment]
Alright. Thank you for the assistance!
