### ISSUE TITLE
Graph API/SDK missing - To get SharePoint User Profile UserLookupID

### ISSUE THREAD

**Issue by sharmajitendralal** [microsoftgraph/msgraph-sdk-powershell#1049]
Hello,

I am working on SharePoint list to create new record but unfortunately User Field failed to update with User Principle name or Using Email ID

The Unique way to update the SPO list User field using UserLookupId but there is no CMD/API in Graph to get that
**New-MgSiteListItem -ListId $ListID -SiteId $siteID -Fields @{ "Title" = "myDemo44"; "Enternumber" = 5; "UserLookupId" = 12 }**

So Please help here to use best practice to update the User field using Graph API Module only

**Comment by peombwa** [comment]
@sharmajitendralal, you can get and update a SharePoint list item fields as shown in the API/command examples in our API reference docs:
- Get SharePoint List Item fields - https://docs.microsoft.com/en-us/graph/api/listitem-get?view=graph-rest-1.0&tabs=powershell#request. Please note that the fields will be stored in the `.AdditionalProperties` of `Fields` property since it is an OpenType.
  ``` powershell
  $ListItem= Get-MgSiteListItem -SiteId $siteId -ListId $listId -ListItemId $listItemId -ExpandProperty "fields"
  $ListItem.Fields.AdditionalProperties # You'll find the fields here.
  ```
- Update SharePoint List Item fields - https://docs.microsoft https://docs.microsoft.com/en-us/graph/api/listitem-update?view=graph-rest-1.0&tabs=powershell#example
