### ISSUE TITLE
Scopes always have all scopes even when a smaller scope is requested

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/msgraph-sdk-powershell#1056]
### Steps to reproduce
```
connect-mggraph -Scopes 'Group.Read.All'
(get-mgcontext).Scopes
```

### Business need
Even if my app may have readwrite rights, sometimes I want to do things in read only mode to avoid accidents, and then use dynamic scoping to promote to write at the time of performing the write action.

### Expected
Group.Read.All
openid
profile
email

### Actual
Directory.ReadWrite.All
Group.Read.All
openid
profile
User.Read
User.Read.All
User.ReadWrite.All
email

**Comment by peombwa** [comment]
Sorry for the delayed response.

This is by design. We read the scopes from the access token's `scp` claim, which always has the previously consent scopes even when incrementally consenting to a single scope.

`(Get-MgContext).Scopes` is meant for customers who need to know which scopes they've already consented to.
