### ISSUE TITLE
get-mguser doesn't return LastPasswordChangeDateTime properly

### ISSUE THREAD

**Issue by PBigeon** [microsoftgraph/msgraph-sdk-powershell#1081]
When you use the following Cmdlet : 
`(get-mguser -UserId 6051b2f8-e7e4-4fed-b6f8-0c4f1905f260 -select 'LastPasswordChangeDateTime')`

You don't get the value of the LastPasswordChangeDateTime in the output, howerver, the object itself contains it :
`PS C:\Users\myuser\OneDrive - Microsoft\Scripts> (get-mguser -UserId 6051b2f8-e7e4-4fed-b6f8-0c4f1905f260 -select LastPasswordChangeDateTime)                

Id DisplayName Mail UserPrincipalName UserType
-- ----------- ---- ----------------- --------
`
`PS C:\Users\myuser\OneDrive - Microsoft\Scripts> (get-mguser -UserId 6051b2f8-e7e4-4fed-b6f8-0c4f1905f260 -select 'LastPasswordChangeDateTime').LastPasswordChangeDateTime

Thursday, February 10, 2022 8:14:06 AM`

This can lead to confusion for our customers

**Comment by peombwa** [comment]
This is by design/PowerShell limitation.

`Get-MgUser` returns an object of type [IMicrosoftGraphUser](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties) (`Get-Help Get-MgUser -Full`). We do provide a [default output format](https://docs.microsoft.com/en-us/powershell/scripting/developer/format/how-to-create-a-formatting-file-format-ps1xml?view=powershell-7.2) for each type, in this case (`Id DisplayName Mail UserPrincipalName UserType`), that is specified at build time and is only limited to one per type. PowerShell does not currently allow binary modules to alter the output format of a command at runtime as formatting is only limited to `.format.ps1xml`.

Customers are expected to use `Select-Object` or [other formatting commands](https://docs.microsoft.com/en-us/powershell/scripting/samples/using-format-commands-to-change-output-view?view=powershell-7.2) to modify the output to their desire:
``` powershell
Get-MgUser -UserId $UserId -Select 'LastPasswordChangeDateTime' | Select-Object -ExpandProperty LastPasswordChangeDateTime

# Or

$User = Get-MgUser -UserId $UserId -Select 'LastPasswordChangeDateTime'
$User.LastPasswordChangeDateTime
```
