### ISSUE TITLE
Invoke-MgInvalidateUserRefreshToken throwing exception, although operation succeeds

### ISSUE THREAD

**Issue by khant414** [microsoftgraph/msgraph-sdk-powershell#1092]
Hi, I ran into an issue where 'Invoke-MgInvalidateUserRefreshToken' throws an exception in relation to a null referenced object, but after tracing the operation in fiddler you can see it is successful. The screenshots below are in relation to my test tenant, let me know if you need any assistance.

![GraphSuccess](https://user-images.githubusercontent.com/36459326/154156315-cbfbf976-3fb0-427a-8ea9-7c425f194d56.png)
![PSException](https://user-images.githubusercontent.com/36459326/154156342-eb5ade00-50b4-4490-ad90-8b8c727d091d.png)

**Comment by brice-automatizit** [comment]
same issue.

using Invoke-GraphRequest in the meantime
$requestUri = "/beta/users/" + $graphUser.Id  + "/invalidateAllRefreshTokens"
$revoke = Invoke-GraphRequest -Method POST -Uri $requestUri

**Comment by peombwa** [comment]
The command was fixed by https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/1.10.0. Please update to the latest version of the SDK - `Update-Module Microsoft.Graph`.

@vandreytrindade, the command is only available in beta. You'll need to [switch to beta profile](https://docs.microsoft.com/en-us/powershell/microsoftgraph/get-started?toc=%2Fgraph%2Ftoc.json&view=graph-powershell-1.0#api-version) to use it.

You can also use `Revoke-MgUserSignInSession -UserId "USER"` when using commands under v1.0 profile
