### ISSUE TITLE
Continuous access evaluation error

### ISSUE THREAD

**Issue by rickjansen-dev** [microsoftgraph/msgraph-sdk-powershell#1105]
Hi, I'm trying to execute the following:

```pwsh
Connect-MgGraph -Scopes "Application.Read.All"

Get-MgApplication
```

But the call to `Get-MgApplication` always results in the following error:

```
Get-MgApplication_List1: Continuous access evaluation resulted in claims challenge with result: InteractionRequired and code: LocationConditionEvaluationSatisfied
```

A bit of googling around only resulted in this issue in the azure-powershell repo which might be similar: https://github.com/Azure/azure-powershell/issues/16766

I'm running into this problem on both powershell in windows and linux (wsl)

I tried `Disconnect-MgGraph` and connecting with `-ForceRefresh`, it just always results in the same error

**Comment by robinmalik** [comment]
We're also seeing this issue when connecting as global administrators and `Application.ReadWrite.All` with PowerShell 5.1. 

PowerShell 7.3.1 isn't an option either due to:
`Get-MgApplication_List1: One or more errors occurred. (Could not load file or assembly 'Microsoft.Graph.Authentication.Core, Version=1.20.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.)`.

All MgGraph modules are up to date (1.20.0).

**Comment by peombwa** [comment]
Closing as fixed by https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/2.0.0-preview6
