### ISSUE TITLE
Get-MgUser does not throw an exception when a 404 occurs like the AzureAD powershell module did.

### ISSUE THREAD

**Issue by RayGHeld** [microsoftgraph/msgraph-sdk-powershell#1129]
This is a customer support issue -- a support case has been opened for it.

try{
Get-MgUser -UserId 'trigger error'
Write-Host 'OK '
}
catch{
Write-Host 'not ok'
}

Customer is always getting the 'OK' -- it does not fall into the catch block.  I have verified the behavior in PowerShell 7 with the latest module as well.

**Comment by peombwa** [comment]
@RayGHeld, this is by design. This SDK supports [non-terminating errors](https://devblogs.microsoft.com/scripting/understanding-non-terminating-errors-in-powershell/), allowing PowerShell to continue to the next command and giving customers the flexibility to specify how non-terminating errors such as 404 not found are handled. By default, PowerShell sets `$ErrorActionPreference` to `Continue`, error messages are displayed, and execution continues unless you use the `ErrorAction` parameter.

In this case, the customer should specify an `ErrorAction` (`Get-MgUser -UserId 'trigger error' -ErrorAction Stop`) when running the command as documented at https://devblogs.microsoft.com/scripting/handling-errors-the-powershell-way/#erroraction-parameter.

The same behavior can also be observed with native PowerShell commands such as `Get-ChildItem`, e.g., `try { Get-ChildItem -Path "NOT_A_PATH" } catch { "In Catch" }`.
