### ISSUE TITLE
Building binary cmdlet modules using Microsoft.Graph NuGet package has conflicts with DLLs from Graph PS modules

### ISSUE THREAD

**Issue by AlanMcBee** [microsoftgraph/msgraph-sdk-powershell#1143]
I'm extending a script module by adding some custom binary modules, using the PowerShell Standard Library, targeting .NET Standard 2.0 because I need to support .NET Framework, but want to also use the module in PowerShell 7+.

Installed on my machine: 

- `Microsoft.Graph` PowerShell package 1.9.3 
    `-ProviderName PowerShellGet`
    `-Scope AllUsers`
    Installed using WindowsPowerShell
- `Microsoft.Graph` NuGet package 4.20.0
    Installed using `dotnet add package Microsoft.Graph`

CSProj file:

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Diagnostics.NETCore.Client" Version="0.2.257301" />
        <PackageReference Include="Microsoft.Graph" Version="4.20.0" />
        <PackageReference Include="Microsoft.Office.Interop.Excel" Version="15.0.4795.1000" />
        <PackageReference Include="Microsoft.Office.Interop.Outlook" Version="15.0.4797.1003" />
        <PackageReference Include="PowerShellStandard.Library" Version="5.1.0">
            <PrivateAssets>All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="System.Text.Json" Version="6.0.2" />
    </ItemGroup>

This has gone generally pretty well, until I try to use System.Text.Json to serialize anything from the Microsoft.Graph namespace. When I try that, I get these kinds of errors:

    ... : Could not load file or assembly 'Microsoft.Graph.Core, Version=2.0.8.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621)

Even though the correct version is in the same folder as the cmdlet assembly, it won't get loaded because this DLL is already loaded:

    C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.9.3\Microsoft.Graph.Core.dll

This DLL is versioned 1.25.1, so it seems to have come from the same-versioned NuGet package. Presumably, that version was loaded into the pwsh.exe process because my .psd1 file includes a RequiredModule set to `Microsoft.Graph.Mail`, which requires `Microsoft.Graph.Authentication`, which has this version of the DLL.

Following the info from https://docs.microsoft.com/en-us/powershell/scripting/dev-cross-plat/resolving-dependency-conflicts?view=powershell-7.2, I've tried (unsuccessfully) to set up `AssemblyLoadContext` to help resolve this, but it's quite difficult to attach a debugger in time to step through, because the launcher for a class library does not like using pwsh.exe, or something like that, and it appears that my ALC class(es) are not getting invoked in time to prevent loading the older version of Microsoft.Graph.Core.dll/

If I'm doing something wrong, cool, let me know.

My planned workaround is to not bundle the binary module in with the script module and to make sure I load the binary module first.

I think what I'd like to see is that the Microsoft.Graph.Core.dll that is packaged inside Microsoft.Graph.Authentication is at least nearly the same version as a contemporary release of the Microsoft.Graph NuGet package. Otherwise, I'll have to drop my NuGet reference version back to 1.25.1, which was released almost a year ago.

**Comment by peombwa** [comment]
@AlanMcBee, is there a reason why you need to load/use Microsoft.Graph .NET SDK v4.20.0 and Microsoft.Graph PowerShell in the same PowerShell session? These are two different SDKs that are not designed to be used together hence the dll conflict error you are getting - `Could not load file or assembly 'Microsoft.Graph.Core, Version=2.0.8.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621)`. I would recommend you stick to one SDK (MS Graph PowerShell if this is a PowerShell module) and fall back to [Invoke-MgGraphRequest](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-mailbag-a-deeper-look-into-the-microsoft-graph-powershell-sdk/?msclkid=1c367faeb21211ecba01be56c3e67075#manual-requests) when an API/command is missing.

Please note that Microsoft.Graph PowerShell (this repo) uses `Microsoft.Graph.Core v1.25.1` and Microsoft.Graph .NET SDK v4.20.0 uses `Microsoft.Graph.Core v2.0.8`. PowerShell won't allow you to load 2 different versions of the same dll in the same session until you fully implement an `AssemblyLoadContext` on your end to load the right versions of your dependency.

Microsoft Graph PowerShell and Microsoft Graph .NET SDK currently use two different versions of core due to the underlying auth dependency (MSAL vs. Azure Identity). We plan to move to a common core in MS Graph PowerShell v2 as part of a breaking change - https://github.com/microsoftgraph/msgraph-sdk-powershell/milestone/23.
