### ISSUE TITLE
There is only one cmdlet for both the listDeletedItems and getDeletedItem APIs requiring that the admin must know the Object ID of a deleted object for them to run the cmdlet. Can we get this cmdlet to also list all deleted objects that can be filtered by type (app,user,group)?.

### ISSUE THREAD

**Issue by msewaweru** [microsoftgraph/msgraph-sdk-powershell#1173]
![image](https://user-images.githubusercontent.com/73849846/159967847-56c627f7-c6a2-4dff-a0f4-1718cd083f03.png)

**Comment by peombwa** [comment]
@msewaweru. Thanks for taking the time to open this issue. The SDK does not currently support [OData cast](https://docs.microsoft.com/en-us/graph/api/directory-deleteditems-list?view=graph-rest-1.0&tabs=http#http-request) due to a lack of derived types in the CSDL metadata/OpenAPI file. We are already tracking OData cast support in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/19.

A workaround is to use `Invoke-MgGraphRequest` to make a direct REST call to list deleted directory items by type.
