### ISSUE TITLE
Get-MgGroupMember does not return member properties other than ID

### ISSUE THREAD

**Issue by titchy** [microsoftgraph/msgraph-sdk-powershell#1213]
When using Get-MgGroupMember the returned object only has an ID, regardless of th value given to the -Property parameter.
The result is that I have to then iterate through the list and use Get-MgUser for each entry. This hits the API a lot and seems rather inefficient.

**Comment by titchy** [comment]
The API supports the provision of expanded members; from the documentation: 
Supports $expand including nested $select. For example, /groups?$filter=startsWith(displayName,'Role')&$select=id,displayName&$expand=members($select=id,userPrincipalName,displayName)
But there appears to be no way to access this through this command.

**Comment by titchy** [comment]
Turns out that this is not a bug, or at least not the bug I thought it was.
The issue I was experiencing is that if you ask for parameters, but they are not asked for in the correct order, then you do not get them, and if you do not get them, they look like nothing is being returned.
Once I placed userprincipalname before othermail and figured out that otherMail is actually otherMails when asked for this way (even though the user object has otherMail specified as an attribute in the docs) then I noticed that values are sent, but not as attributes of the user object, but in the additionalattributes attribute.
Quite a pain to figure this all out.
I will leave this open in case the Triage team think that ordered attributes need fixing and attributes asked for need to be returned without values if they are asked for but have no value.

**Comment by peombwa** [comment]
@titchy, you can access the additional properties of group members from the `AdditionalProperties` property:
``` powershell
> Get-MgGroupMember -GroupId "GROUP_ID" -Top 1 | Select -ExpandProperty AdditionalProperties

Key               Value
---               -----
@odata.type       #microsoft.graph.user
businessPhones    {1230000000}
displayName       Name Name
givenName         Name
mail              Name@Name.onmicrosoft.com
officeLocation    B
preferredLanguage en-US
surname           Name
userPrincipalName Name@Name.onmicrosoft.com
```
`Get-MgGroupMember` returns an output of type [directoryObject](https://docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=http#response) which only has [two properties](https://docs.microsoft.com/en-us/graph/api/resources/directoryobject?view=graph-rest-1.0#properties): Id and DeletedDateTime. Why is this the case? A group member can be any of the following types:
- [device](https://docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-1.0)
- [group](https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0)
- [orgContact](https://docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-1.0)
- [servicePrincipal](https://docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0)
- [user](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0) 

We plan to simplify how customers can access derived types in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/19.

As for the query parameter ordering issue, please open a question/ticket at https://developer.microsoft.com/graph/support for the service team to investigate.

**Comment by robinmalik** [comment]
@peombwa Apologies for commenting on a closed issue, but has something changed since you last gave the example `Get-MgGroupMember -GroupId "GROUP_ID" -Top 1 | Select -ExpandProperty AdditionalProperties` ? 

I'm using Microsoft.Graph.Groups 1.16.0, beta profile, and only the Id is returned for the members. Whilst I understand the reasoning behind that, is it possible to get userprincipalnames for the members with this cmdlet or are we expected to make X number of additional lookups with something like:

`Get-MgGroupMember -GroupId $GroupId -All | ForEach {Get-MgUser -UserId $_.Id}`  ?

Thanks!

**Comment by curtiplas** [comment]
> The API supports the provision of expanded members; from the documentation: Supports $expand including nested $select. For example, /groups?$filter=startsWith(displayName,'Role')&$select=id,displayName&$expand=members($select=id,userPrincipalName,displayName) But there appears to be no way to access this through this command.

Are there plans to make this available via command line?

**Comment by putersdcat** [comment]
Just in case anyone finds this in the future, here is another inline solution to the conversation above about Get-MgGroupMember not returning the granular output data as expected. 

Here in this example you end up with "spat instantiated"™ custom object that follow the same structure as what is returned by the Get-MgUser at lease at time of writing. Also take care with the case in the additional properties,  DisplayName <> displayName

$AllGroupMembers = Get-MgGroupMember -GroupId $sourceGroupId -All | Select @{label="DisplayName";expression = {$_.AdditionalProperties.displayName} }, Id, @{label="Mail";expression = {$_.AdditionalProperties.mail} }, @{label="UserPrincipalName";expression = {$_.AdditionalProperties.userPrincipalName} }

**Comment by gavinltomra** [comment]
FYI, there is also now the `Get-MgGroupMemberAsUser` cmdlet, which seems to basically do the cast for you.

Though a caveat is that this will only report users and not service principals, other groups, or other kinds of member.  Also not sure which one is more efficient, especially if you wanted to query multiple member types.

**Comment by OtterKring** [comment]
I find it rather unsettling that this thread got closed, but the -Property parameter is still existing in `Get-MgGroupMember` and is still not working as expected (aka as in Get-MgUser, which also does not work as expected, aka as in Get-ADUser, but this is a very personal rant) after almost 3 years.
Additionally, the `AdditionalProperties` attribute, when when extended with Select-Object, returns a not-Powershell-like structure with case-sensitive names. To work around that I wrote a function which converts it to a regular `PSCustomObject`. Maybe some of you find it helpful. Just pipe the output of `Get-MgGroupMember` to it.
Finally, `AdditionalProperties` in regular graph still does not return all the properties you get from the beta command. How much performance and energy is waste every day because people must rely on a `Get-MgUser` call for every (or at least every 15, when using a filter) group member ever since?

[Expand-MgAdditionalProperties.zip](https://github.com/user-attachments/files/18840852/Expand-MgAdditionalProperties.zip)
