### ISSUE TITLE
Get-mgauditlogsignin

### ISSUE THREAD

**Issue by jachaohk** [microsoftgraph/msgraph-sdk-powershell#1251]
Is there a way to query using Get-mgauditlogsignin so that you can filter by Authentication Method within the AuthenticationDetails property?

When I attempt to use -property authenticationdetails, I get the following:
Get-MgAuditLogSignIn : Query option 'Select' is not allowed. To allow it, set the 'AllowedQueryOptions' property on EnableQueryAttribute or QueryValidationSettings.

I don't want to have to query every value and then where-object to get to the AuthenticationMethod property.

**Comment by peombwa** [comment]
The right parameter to use would have been [-Filter](https://docs.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#any-operator), but the API does not support filtering against `AuthenticationDetails` property:
``` powershell
Get-MgAuditLogSignIn -Filter "AuthenticationDetails/any(d:d/AuthenticationMethod eq 'Password')"
```

Please open a service feature request at https://developer.microsoft.com/en-us/graph/support to have your scenario supported.

**Comment by jachaohk** [comment]
I am a bit confused by your statement.  You say that right parameter is -filter but then say the API doesn't support it but provide the filter string anyways?   Does this work?

Also, what is the purpose of the -property parameter then?   I wanted to be able to query based on that property alone and hope that it also provided some base property values that way I can query against it.    For example if I run this on get-mguser

get-mguser -filter "usertype eq 'Guest'" -all -property signinactivity

it exposes the SignInActivity properties and then I can select not only the UPN and displayname but also the sign in activity properties.   Running get-mguser without -property does not give you the signinactivity detail, much like the mgauditlogsignin authenticationdetails property.

With mgauditlogsignin, the -property parameter doesnt work at all with certain properties if selected.

Thanks,

**Comment by peombwa** [comment]
Sorry for the delayed response.

> Is there a way to query using Get-mgauditlogsignin so that you can filter by Authentication Method within the AuthenticationDetails property?

No, the API does currently not support filtering against `AuthenticationDetails` property. You can however use `-Filter` to filter supported properties as shown in https://docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-1.0&tabs=powershell#example-2-retrieve-the-first-10-sign-ins-to-apps-with-the-appdisplayname-that-starts-with-graph.

> Also, what is the purpose of the -property parameter then? I wanted to be able to query based on that property alone and hope that it also provided some base property values that way I can query against it. For example if I run this on get-mguser

`-Property` is just an alias for `-Select`. It is used to specify which properties the service should include in response when making a request.
``` powershell
➜ Get-Help Get-MgAuditLogSignIn -Parameter Property
-Property <String[]>
    Select properties to be returned

    Required?                    false
    Position?                    named
    Default value
    Accept pipeline input?       false
    Accept wildcard characters?  false
```
`-Property` parameter corresponds to `$select` when using the API.  See the documentation on how to use `$select` at https://docs.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#select-parameter.


Please open a service feature request at https://developer.microsoft.com/en-us/graph/support since your scenario of filtering against `AuthenticationDetails` property is not yet supported by the service.
