### ISSUE TITLE
Support Keystoke (ctrl-c) cancellation for Connect-MgGraph

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/msgraph-sdk-powershell#1259]
When using `connect-mggraph` interactively, if you close the browser window rather than hitting back or other activity, it hard-locks the cmdlet requiring a powershell restart. I should be able to cancel via the cancellation keystroke and get my prompt back.

I recommend looking at the Az implementation of `Connect-AzAccount` which follows the same flow but allows for cancellation via a `CancellationToken` which is wired to the PS cancel event

**Comment by ddyett** [comment]
would be good to add. adding to backlog.

**Comment by ddyett** [comment]
should work in the V2 release.

**Comment by peombwa** [comment]
Closed by #1201. Will ship in v2.

**Comment by dieks** [comment]
When using connect-mggraph interactively, if you close the browser window rather than hitting back or other activity, it locks the cmdlet until a timeout is reached. After which it my script continues as if sign in succeeded.
I should be able to cancel signing in by closing the browser tab/window and get my prompt back and get a return value that represents my cancelation.

PS C:\> Get-Module Microsoft.Graph, Microsoft.Graph.Authentication

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.30.0                Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGr…

PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.5.4
PSEdition                      Core
GitCommitId                    7.5.4
OS                             Microsoft Windows 10.0.26200
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Browser version seems to be OK:
Microsoft Edge for Business
Microsoft Edge is up to date.
Version 143.0.3650.96 (Official build) (64-bit)
