### ISSUE TITLE
Add RoleManagement v1.0 API support

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/msgraph-sdk-powershell#1267]
The guidance for the PIMv3 API has been updated to reference the 1.0 endpoint and needs to be regenerated, the module currently still points to the beta endpoints for things like roleEligibilitySchedule

```
find-mggraphcommand -uri "https://graph.microsoft.com/v1.0/roleManagement/directory/roleEligibilitySchedules"
Find-MgGraphCommand: URI ' https://graph.microsoft.com/v1.0/roleManagement/directory/roleEligibilitySchedules' in v1.0 is not valid or is not currently supported by the SDK. Ensure the URI is formatted correctly and try again.
```
![image](https://user-images.githubusercontent.com/15258962/168856685-79888816-36ba-4ff8-8cbd-eb8e30b698a3.png)

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

PIMv3 APIs will be coming to v1.0 as part of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1265. We were blocked by one of our dependencies from refreshing commands in the SDK. The blocker has since been resolved, and a release should go out mid this month.
