### ISSUE TITLE
Get-MgRoleManagementDirectoryRole* under wrong package

### ISSUE THREAD

**Issue by willfiddes** [microsoftgraph/msgraph-sdk-powershell#1271]
The "*MgRoleManagementDirectoryRole*" cmdlets appears to fall under the "Microsoft.Graph.DeviceManagement.Enrolment" package which is not right.

They should technically fall under "Microsoft.Graph.Identity.DirectoryManagement"

Azure AD Role management is not part of Intune or Enrollment

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

We will review the module mapping in the next major update to avoid breaking change - https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/838. 

@maisarissi, we need to settle on long term module mapping approach to remain consistent with APIs.

**Comment by peombwa** [comment]
We currently have the commands in `Identity.Governance` module as there is no way to disambiguate between `/roleManagement/directory/*` and `/roleManagement/entitlementManagement/*`, since they share the same "root"/OpenAPI tag - `roleManagement.rbacApplication`:
![image](https://user-images.githubusercontent.com/7061532/214402275-005c6073-a61e-4bbe-94b0-ad449aab9f04.png)
![image](https://user-images.githubusercontent.com/7061532/214402352-a908dddf-7163-40ce-8f6b-e98930448e1d.png)

The current module classification model uses OpenAPI tags to split the paths into modules using the module mapping config at https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/features/2.0/config/ModulesMapping.jsonc.

We will keep the issue open as a tracking item to review the current module naming model.

**Comment by CarolKigoonya** [comment]
Issue is resolved in PowerShell v2
