### ISSUE TITLE
Reopening issue #1008

### ISSUE THREAD

**Issue by aremo-ms** [microsoftgraph/msgraph-sdk-powershell#1272]
@maisarissi and @peombwa
I'm reopening [this](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1008) issue. 
**Cannot reproduce** doesn't resolve it for me. I have same standard PowerShell with same standard terminal and cannot get through it. I even installed 1.9.0 version for Microsoft.Graph.Authentication and still have this issue.
I need real help with chat and not msfbot trying to shake me off with inactivity claims.

Found [similar issue](https://github.com/pnp/PnP-Sites-Core/issues/2548) that was "successfully" archived and forgotten

This issue holds us back for Azure-Samples
![image](https://user-images.githubusercontent.com/85962119/169599029-c7ea6547-279a-4fbd-9fbf-c9c2322ca2a8.png)

**Comment by peombwa** [comment]
@aremo-ms, did you perform a clean install of the SDK as instructed in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1008#issuecomment-1028348639?

The dll mismatch can occur if you load modules with mismatched dependency, e.g., the version of `Microsoft.Graph.Authentication` does not match `Microsoft.Graph.Groups`.  Please verify that the versions of Microsoft.Graph* modules loaded in your PowerShell session are the same (1.9.6 is the latest release) - `Get-Module Microsoft.Graph* | select Name, Version`.

Please share with us:
- A script that we can use to reproduce this (include your `Import-Module` commands, if any).
- Output of:
  - `Get-Module | Select Name, Version`.
  - `$PSVersionTable`.

Issue https://github.com/pnp/PnP-Sites-Core/issues/2548 is not related to the PowerShell SDK. The issue is for the [Microsoft Graph .NET Core library](https://www.nuget.org/packages/Microsoft.Graph.Core/1.9.0).

**Comment by aremo-ms** [comment]
working on uninstall now. Will update soon

**Comment by aremo-ms** [comment]
Was able to create a group. The issue was an old version of Graph. Clean install helped indeed. Thanks a lot guys
