### ISSUE TITLE
Get-MGUser wont show the property such as department if it was not part of the Property parameter

### ISSUE THREAD

**Issue by farismalaeb** [microsoftgraph/msgraph-sdk-powershell#1311]
Get-MGUser won't get all the user property if it was not part of the Property parameter.
This line return nothing
`Get-MgUser -UserId UserName@Domain.com | fl Department`
 But this line returns the result
`Get-MgUser -UserId UserName@Domain.com -Property department | select department`

If this is by design then I think properties such as department should not be listed in the FL or Select unless mentioned in the Property parameter.

**Comment by peombwa** [comment]
This is by design. The SDK mirrors how the Microsoft Graph API works. The API does not return all properties by default, and customers are expected to use `$select` to specify the non-default properties to retrieve. See https://docs.microsoft.com/en-us/graph/query-parameters#select-parameter.

As per the API reference doc - https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties:
> The name for the department in which the user works. Maximum length is 64 characters.
> Returned only on $select. Supports $filter (eq, ne, not , ge, le, in, and eq on null values).

`-Property` is an alias for `$select`.
