### ISSUE TITLE
Unable to install Microsoft Graph PowerShell from the nukpg file. 

### ISSUE THREAD

**Issue by willfiddes** [microsoftgraph/msgraph-sdk-powershell#1342]
Repro steps:

Register-PackageSource -Name PSR -Location C:\AAD\Apps\powershell\GraphRepository\ -ProviderName NuGet -Trusted

Place files into the local repository i.e. microsoft.graph.1.10.0.nupkg; microsoft.graph.authentication.1.10.0.nupkg

Install-Package -Name Microsoft.Graph.Authentication -Source PSR
Install-Package : No match was found for the specified search criteria and package name 'Microsoft.Graph.Authentication'. Try
Get-PackageSource to see all available registered package sources.

Find-Package -Source PSR returns no results.

Other nukpg files work such as Azure AD PowerShell module

**Comment by peombwa** [comment]
@willfiddes, I'm not able to reproduce this on my end using the steps provided above.
![image](https://user-images.githubusercontent.com/7061532/175434148-da46adbb-82fe-4468-a893-64df8eab2525.png)

Try running `Install-Package` with `-Debug` to see where the issue is coming from. I suspect it is something to do with your environment.
