### ISSUE TITLE
Devices attribute missing in ConditionalAccessConditionSet variable

### ISSUE THREAD

**Issue by CelesteDG** [microsoftgraph/msgraph-sdk-powershell#1347]
See the comments in GitHub issue https://github.com/microsoftgraph/microsoft-graph-docs/issues/17205

CC @msewaweru @FaithOmbongi

**Comment by peombwa** [comment]
The issue is not related to our SDK. Customer is using a soon to be deprecated AzureAD PowerShell module and not our SDK. 

Devices property is available on [ConditionalAccessConditionSet](https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessConditionSet?view=graph-rest-1.0) using our SDK - https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/new-mgidentityconditionalaccesspolicy?view=graph-powershell-1.0.
