### ISSUE TITLE
MG PowerShell module should have similar permissions like the Graph Explorer

### ISSUE THREAD

**Issue by cnshenj** [microsoftgraph/msgraph-sdk-powershell#1378]
This is related to issue #1356. The answer in #1356 is not correct.

I am **NOT** an admin. I can use endpoints like `GET /servicePrincipals` or `GET /servicePrincipals/{id}/appRoleAssignments` in [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) if I sign in with my own credentials.
If I check the permissions needed for the same operation in MG PowerShell, all the scopes require admin consent.
```
Find-MgGraphCommand -command Get-MgServicePrincipal | Select -First 1 -ExpandProperty Permissions

Name                       IsAdmin Description                   FullDescription
----                       ------- -----------                   ---------------
Application.Read.All       True    Read applications             Allows the app to read applications and service princ…
Application.ReadWrite.All  True    Read and write applications   Allows the app to create, read, update and delete app…
Directory.AccessAsUser.All True    Access the directory as you   Allows the app to have the same access to information…
Directory.Read.All         True    Read directory data           Allows the app to read data in your organization's di…
Directory.ReadWrite.All    True    Read and write directory data Allows the app to read and write data in your organiz…
```

The fact that Graph Explorer can use those endpoints proves that the permissions to call the graph API is properly granted. Inspecting the access token obtained by Graph Explorer, I see it has scope: "Directory.ReadWrite.All". The reason is that Graph Explorer has all the proper permissions granted. I can confirm this in [Azure Portal](https://ms.portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/CallAnAPI/appId/de8bc8b5-d9f9-48b1-a8ad-b748da725064/isMSAApp~/false):

![image](https://user-images.githubusercontent.com/8441956/178052490-1810226f-e21d-4a77-b145-341f17ef7eb2.png)

Note that these are permission for "the app to call Graph API on user's behalf", it's not giving the user the permission they should not have. MG PowerShell must have an app registration of its own - and the app owner (not users) should get proper admin consent, just like Graph Explorer or AzureAD PowerShell,

**Comment by peombwa** [comment]
@cnshenj, sorry for the delayed response.

From the screenshot, it looks like you are using GE in the MSIT tenant.

Please note that Graph Explorer is pre-consented for the permissions shared above in the MSIT tenant for GET operations only since it is a web app that uses a different authentication model (proxy-based auth). PowerShell on the other hand isn't pre-consented in the tenant because it is a 3p public app with incremental scope consent support. See the response at https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/684#issuecomment-1165516148 for details.

Even with pre-consent, an admin MUST first approve the app for admin permissions before you can use them. So, `Directory.ReadWrite.All` will still need admin consent before using it as described in the API reference. Customers generally work with their tenant admins to get their apps approved.

The recommendation we've gotten from the ACE team is that internal customers (I assume you are) should create their own appId with the required permissions and go through the ACE admin consent process. Once approved, you can use your app id with the module by invoking `Connect-MgGraph -ClientId "Approved_App_Id" -TennantId "Your_Tennant_Id" -DeviceCode`. Go to MSW and search for `"Admin Consent Program Guidance"` for more info on the official admin consent guidance.

AzureAD uses a different authentication module that is not recommended for public apps like ours.
