### ISSUE TITLE
Create a pipeline for updating powershell documents on microsoftgraph-docs-powershell repository

### ISSUE THREAD

**Issue by timayabi2020** [microsoftgraph/msgraph-sdk-powershell#1437]
Currently updates to [powershell document repository](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell) are done locally by running a scripts and manually creating a pull request.
The scripts are responsible for

1. Copying markdown files from the [powershell sdk repository](https://github.com/microsoftgraph/msgraph-sdk-powershell) to [powershell docs repository](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell)
2. Updating markdown help
3. Escaping disallowed html tags as mentioned [here](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1135).

There is need for automating the above process through an azure pipeline because running it on a local machine is time consuming and resource intensive

**Comment by peombwa** [comment]
@timayabi2020, please close this issue since it is marked as done. Don't forget to also link it to the pull request that closed in:
![image](https://user-images.githubusercontent.com/7061532/185458514-028e64e9-4ee4-46df-982e-c79b44e7598c.png)

Using keywords like fixes #IssueNumber or closes #IssueNumber in your PR descriptions will automatically link issues to PRs and close them for you.
