### ISSUE TITLE
automatically refresh Microsoft.Graph Token

### ISSUE THREAD

**Issue by tobs88** [microsoftgraph/msgraph-sdk-powershell#1543]
Hi,
we establish a graph connection via a third-party tool and Module Microsoft.Graph.Authentication. The token expires after 1 hour and we have no way of refresh the token in the script. Is it possible for the token to update itself automatically, like Exchange or Teams?

**Comment by peombwa** [comment]
This by design:
![image](https://user-images.githubusercontent.com/7061532/193319246-4e58c7bb-57d4-4764-bb39-f9df40ca5f46.png)

We are not able to refresh the provided access token without a refresh token as the token was acquired by a third-party client. Most 3rd-party auth clients handle access token caching and refresh internally.

One solution is to add a timer to your script that calls the 3rd party auth client for a new access token every 55 minutes.

What's the reason why you need to use a third-party auth client to get an access token?
