### ISSUE TITLE
Sync the offline cmdlet help from the online reference content

### ISSUE THREAD

**Issue by msewaweru** [microsoftgraph/msgraph-sdk-powershell#1548]
Some cmdlets like Get-MgUser have the updated descriptions and examples from the offline help but others, I cannot help for them.
![image](https://user-images.githubusercontent.com/73849846/193229648-1ac6801a-bb5a-4b39-9cad-ec64f16d95dd.png)

Running `Update-Help` returns the error below:
![image](https://user-images.githubusercontent.com/73849846/193230035-fbd15d61-3449-427e-8737-ced59f0b3e1f.png)

**Comment by peombwa** [comment]
Please check the spelling of license in the command name, Both the API and the command use license and not licence. The issue is with the British vs American spelling of license as a noun. `man Get-MgUserLicenseDetail` works just fine! See https://learn.microsoft.com/en-us/graph/api/user-list-licensedetails?view=graph-rest-1.0&tabs=powershell#example.

Update-help is not supported for any of our modules, as they always ship with updated help.

**Comment by msewaweru** [comment]
> Please check the spelling of license in the command name, Both the API and the command use license and not licence. The issue is with the British vs American spelling of license as a noun. `man Get-MgUserLicenseDetail` works just fine! See https://learn.microsoft.com/en-us/graph/api/user-list-licensedetails?view=graph-rest-1.0&tabs=powershell#example.
> 
> Update-help is not supported for any of our modules, as they always ship with updated help.

Thanks @peombwa, I missed that spelling issue. Question I see some inconsistencies in the way the 2 help files sync. For example, if I check another cmdlet `Get-MgUserManager`, I get these descriptions:

![image](https://user-images.githubusercontent.com/73849846/193544561-6fb3f27f-3822-464a-b3c3-ed84fb3de53c.png)

Vs

![image](https://user-images.githubusercontent.com/73849846/193544677-7c5107e0-0bff-4f82-8467-fd1e41262318.png)

What do I need to do so that the descriptions are in sync?
