### ISSUE TITLE
Using any command that Updates existing AAD application created by AzureAD PS module fails with 

### ISSUE THREAD

**Issue by LenaVinogradov** [microsoftgraph/msgraph-sdk-powershell#1598]
Resource '<my app id>' does not exist or one of its queried reference-property objects are not 
present
We are in the process of migrating from AzureAD PS as part of the deprecation notice https://learn.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-beta
I have many pre-existing AAD applications created by AzureAD PS. 
Attempt to use:
Update-MgApplication -ApplicationId $application.ObjectId <any parameters accepted by this cmdlett here>
Set-MgApplicationLogo -ApplicationId $application.AppId -InFile $appLogoUrl
results in the error:  "Resource '591ad232-5864-40a1-b73b-eacf9e3b72fa' does not exist or one of its queried reference-property objects are not present."
I have attempted suggested in this issue [https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/935] workaround for the Set-MgApplicationLogo:
Invoke-MgGraphRequest -Uri "https://graph.microsoft.com/beta/applications/$Id/logo" -Method PUT -InputFilePath $appLogoUrl -ContentType "image/png" and I have received the same error:

Invoke-MgGraphRequest : PUT https://graph.microsoft.com/beta/applications/591ad232-5864-40a1-b73b-eacf9e3b72fa/logo
HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: 9c63d570-5bfe-4e0f-a3c1-4e338ba8a041
client-request-id: 9c63d570-5bfe-4e0f-a3c1-4e338ba8a041
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"East US","Slice":"E","Ring":"5","ScaleUnit":"005","RoleInstance":"MN1PEPF00006710"}}
x-ms-resource-unit: 1
Cache-Control: no-cache
Date: Fri, 28 Oct 2022 20:51:20 GMT
Content-Encoding: gzip
Content-Type: application/json
{"error":{"code":"Request_ResourceNotFound","message":"Resource '591ad232-5864-40a1-b73b-eacf9e3b72fa' does not exist or one of its queried reference-property objects are not 
present.","innerError":{"date":"2022-10-28T20:51:20","request-id":"9c63d570-5bfe-4e0f-a3c1-4e338ba8a041","client-request-id":"9c63d570-5bfe-4e0f-a3c1-4e338ba8a041"}}}

**Comment by peombwa** [comment]
@LenaVinogradov, please go through the Azure AD Graph API to Microsoft Graph API migration guide at https://learn.microsoft.com/en-us/graph/migrate-azure-ad-graph-property-differences#application-property-differences and https://learn.microsoft.com/en-us/graph/migrate-azure-ad-graph-property-differences#directoryobject-property-differences to review the property differences between the two APIs. ObjectId got renamed to Id in Microsoft Graph.

`Get-MgApplication -ApplicationId $AzureADPsApplication.ObjectId` should work if you are signed into the right tenant.

Please open a question/ticket at https://developer.microsoft.com/en-us/graph/support for the API owners to review your case If you are still getting a 404 error after going through the migration guide and using the right properties.

**Comment by peombwa** [comment]
@LenaVinogradov, for:
1. We are still blocked by the missing required headers in the CSDL metadata. A workaround is to use `Invoke-MgGraphRequest` to set an application's logo. See the workaround in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/935#issuecomment-1072897650.
2. An application's logo cannot be set by updating an application. This is how the API functions. The unnecessary `-LogoInputFile` parameter on `Update-MgApplication` will be removed in v2 of the module now that we have https://github.com/microsoft/OpenAPI.NET.OData/issues/254.
3. This is by design. Microsoft Graph API requires `Application.ReadWrite.All` permissions to update an application - https://learn.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&tabs=http#permissions. This is a high privilege permission that requires an admin consent as stated in https://learn.microsoft.com/en-us/graph/permissions-reference#application-resource-permissions. Your admin can grant consent to the permission [tenant wide](https://learn.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent) or [to a specific user in your tenant](https://learn.microsoft.com/en-us/azure/active-directory/manage-apps/grant-consent-single-user). As permissions are beyond the scope of this module and are tied to the functionality of the API, I'd recommend you open/ go through existing questions at https://learn.microsoft.com/en-us/answers/topics/microsoft-graph-applications.html.

Please note that AD PS module calls a different API to Microsoft Graph PowerShell module. The two APIs are not identical and have a different permissions model. See https://learn.microsoft.com/en-us/graph/migrate-azure-ad-graph-configure-permissions.

**Comment by peombwa** [comment]
I'd suggest you open a feature request at https://developer.microsoft.com/en-us/graph/support as this is an API requirement. There is nothing the module can do to bypass permission requirement.

The permissions can be successfully used with the module once an admin has granted consent to them. This is stated as a prerequisite to using the API.
