### ISSUE TITLE
Get-MgGroupMember stopped working

### ISSUE THREAD

**Issue by asos-romantikhonov** [microsoftgraph/msgraph-sdk-powershell#1623]
¡Hola!

`Get-MgGroupMember -GroupId $groupId` stopped working as expected, it does not return any results at all.
I've used graph explorer to test and get the same results its working only with beta profile. 

Workaround found:
`Get-MgGroupMember -GroupId $groupId -CountVariable CountVar -ConsistencyLevel eventual `

But its still an issue for an older sdk versions where Get-MgGroupMember does not support option -ConsistencyLevel

**Comment by peombwa** [comment]
@asos-romantikhonov, `Get-MgGroupMember` works as expected with the latest version of the module:
![image](https://user-images.githubusercontent.com/7061532/201415372-0e75fb75-9f5f-4221-bebb-1b7b83e05f4b.png)

Which version of the module are you using? Have you consented to the [permissions](https://learn.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=http#permissions) needed to list group members? 

Please share the `-Debug` output when running the command to help us understand what the issue is.
