### ISSUE TITLE
Get-MgDeviceManagementManagedDevice fails if parameters are set

### ISSUE THREAD

**Issue by andreiv3103** [microsoftgraph/msgraph-sdk-powershell#1632]
Hello all

I am using Get-MgDeviceManagementManagedDevice to get the Intune info on all devices in our tenant.
If I run it like:
Get-MgDeviceManagementManagedDevice -All
It works just fine.
However, if I set any filter, like -Filter "OperatingSystem eq 'Windows'"
It fails with: "More than 3 retries encountered while sending the request."
This happens also if I use the -Property paramter and try to select specific properties.

**Comment by peombwa** [comment]
@andreiv3103, the error is due to the [service throttling your requests](https://learn.microsoft.com/en-us/graph/throttling#best-practices-to-handle-throttling).

By default, the command will retry a throttled request three times before failing. You can [modify the max retry](https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/1584#issue-1417492648) using `Set-MgRequestContext -MaxRetry 5` to something > 3 to see if this resolves the issue.

If the issue persists, please open a support ticket/question at https://developer.microsoft.com/en-us/graph/support with the `request-id` and `date` of the failed request to get help from the workload owner. See https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug.

**Comment by andreiv3103** [comment]
Hello Peter. Thanks for the reply.
But if that is the case, then why is:
Get-MgDeviceManagementManagedDevice -All
working? Wouldn't that be throttled also?

**Comment by peombwa** [comment]
That's a good question for the API owner. Service workloads throttle requests using different strategies. See https://learn.microsoft.com/en-us/graph/throttling-limits#identity-and-access-service-limits.

Opening a support ticket with the failing `request-id` will help in figuring out why requests containing `$filter` are being throttled.

**Comment by andreiv3103** [comment]
Understood. Thank a lot!
