### ISSUE TITLE
Update Microsoft.Graph.Core reference to 3.x

### ISSUE THREAD

**Issue by BrianTJackett** [microsoftgraph/msgraph-sdk-powershell#1691]
As part of [Microsoft Graph extension for .NET Interactive Notebooks](https://github.com/microsoftgraph/msgraph-dotnet-interactive-extension), we are loading both Microsoft Graph .Net v5 SDK and PowerShell v2 SDK into same kernel.  Currently this causes conflicts with Microsoft.Graph.Core being at different versions (3.x and 2.x).

Would like to know if possible to target PowerShell v2 SDK to 3.x of Microsoft.Graph.Core?  If not possible, will be looking into alternatives.

**Comment by BrianTJackett** [comment]
Note, I did read comment [here](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1143#issuecomment-1086411601) about not loading multiple Microsoft Graph SDKs into same context.  Polyglot Notebooks (part of .Net Interactive) support using multiple languages side by side in different code blocks, hence the topic came up.

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

Our original plan was to move to `Microsoft.Graph.Core` 3.x once it went to GA. However, since `PowerShell v2 SDK` is still in public preview, we can consider bumping the version of `Microsoft.Graph.Core` to 3.x in our next release as the upgrade is trivial,

**Comment by ddyett** [comment]
@peombwa can you update with detail around authhandler we discussed.

**Comment by BrianTJackett** [comment]
Appreciate any update on progress.  Looking at revisiting this item during upcoming FHL week (1.5 weeks away).  If anything would be available to test I'm happy to try out.

**Comment by peombwa** [comment]
@BrianTJackett, we are unfortunatly not able to seamlessly move to Microsoft.Graph.Core v3 as originally planned due to deprecation of auth handler Microsoft.Graph.Core v3.

In Microsoft.Graph.Core v3, auth is now handled by Kiota's HTTP client request adapter, which is not compatible with AutoREST( the code generator for PowerShell). See reference item for more details on the deprecation - https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1601#issuecomment-1373393533.

To support Microsoft.Graph.Core v3, we will need to add to:
- [ ] Bump Microsoft.Graph.Core dependency to v3.
- [ ] Write our own custom auth handler to handle CAE claims, and auth calls to Azure.Identity.
- [ ] Register the custom auth handler in the middleware pipeline when creating an HTTP client from NET Core v3.

We will use this issue as a tracking item for adding Microsoft.Graph.Core v3 support.

**Comment by peombwa** [comment]
Fixed by https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/2072. Will ship as part of v2.0.0-rc4.
