### ISSUE TITLE
Get-MgApplication -ApplicationId only accepts objectIds

### ISSUE THREAD

**Issue by rvdwegen** [microsoftgraph/msgraph-sdk-powershell#1715]
![Screenshot 2022-12-25 133355](https://user-images.githubusercontent.com/20259120/209468066-0789d36f-073b-43cb-8949-56e2db1dc342.png)

As shown in the screenshot, the ApplicationId parameter does not accept application id's, only objectId's.

**Comment by peombwa** [comment]
This is by design. The API only accepts objectIds. See https://learn.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0#properties and https://learn.microsoft.com/en-us/graph/api/application-get?view=graph-rest-1.0&tabs=http#http-request:
> Unique identifier for the application object. This property is referred to as Object ID in the Azure portal. Inherited from [directoryObject](https://learn.microsoft.com/en-us/graph/api/resources/directoryobject?view=graph-rest-1.0). Key. Not nullable. Read-only. Supports $filter (eq, ne, not, in).

and https://learn.microsoft.com/en-us/graph/api/application-get?view=graph-rest-1.0&tabs=http#http-request
> Replace {applicationObjectId} with the id for the application object, also referred to as the Object ID in the Azure portal.
