### ISSUE TITLE
Update calendar appointments

### ISSUE THREAD

**Issue by lucafabbri365** [microsoftgraph/msgraph-sdk-powershell#174]
Hello,
I'm writing to report an error while using Microsoft Graph PowerShell cmdlets (Outlook Calendar) to set the _Reminder_ to _0 days_ for all recurring appointments/events inside Birthdays' calendar, in bulk.

This is the first code part:

```
Connect-Graph -Scopes "Calendars.ReadWrite","User.Read.All"
$userId = (Get-MgUser | Where-Object {$_.DisplayName -eq "Bill Gates"}).Id
$calendarId = (Get-MgUserCalendar -UserId $userId -Top 10 | Where-Object {$_.Name -eq "Birthdays"}).Id
```

Then I tried these cmdlet at first:
```
Get-MgUserCalendarEvent -CalendarId $calendarId -UserId $userId -Top 2000 | %{ Update-MgUserEvent -EventId $_.Id -UserId $userId -ReminderMinutesBeforeStart 0}
```
...but I get the error below (maybe due to [Request Validator](https://developer.microsoft.com/en-us/office/blogs/introducing-request-validator-to-beta-endpoint/)):

```
Update-MgUserCalendarEvent : Recursive navigation is not allowed after property 'Events' according to the entity schema.
At line:1 char:80
+ ... p 2000 | %{ Update-MgUserCalendarEvent -EventId $_.Id -UserId $userId ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ UserId = 0a24...oftGraphEvent }:<>f__AnonymousType41`3) [Update-MgUserCa...UpdateExpanded1], Exception
    + FullyQualifiedErrorId : NavigationNotSupported,Microsoft.Graph.PowerShell.Cmdlets.UpdateMgUserCalendarEvent_UpdateExpanded1
```
...and these cmdlets, for second:

```
Get-MgUserCalendarEvent -CalendarId $calendarId -UserId $userId -Top 2000 | %{ Update-MgUserEvent -EventId $_.Id -UserId $userId -ReminderMinutesBeforeStart 0}
```

Reminder was changed successfully, however the **Update-MgUserEvent** cmdlet returns the error below (for each item in loop), 

```
Update-MgUserEvent : The server responded with an unrecognized response, Status: OK
At line:1 char:1
+ Update-MgUserEvent -EventId $myEventId -ReminderMinutesBeforeStart 0  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ UserId = 0a24...oftGraphEvent }:<>f__AnonymousType41`3) [Update-MgUserEvent_UpdateExpanded], RestException`1
    + FullyQualifiedErrorId : OK,Microsoft.Graph.PowerShell.Cmdlets.UpdateMgUserEvent_UpdateExpanded
```

Bye,
Luca

**Comment by peombwa** [comment]
The second issue is related to https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/110

**Comment by jantoney** [comment]
Just to add to this, because it seems to be related to the first error.
I understand that I'm using Group calendars, and not individual, but I it seems to be another issue somewhere. Not the specific command.

I was getting this error using pre 0.5.0 but only a few random commands. After upgrading to 0.5.0 it seems that more commands are now affected. It could be that I just didn't notice it before, forgot about the issue and got around it another way, but I don't think this is me doing something wrong.

Running 
`Get-MgGroupCalendarEvent -groupid {Group_ID}`
I see the correct result where it lists the events for that group.
This group I'm testing with only has (and shows) 1 event - All good

Running the below after copying the Event ID from the first command
`Get-MgGroupCalendarEvent -groupid {Group_ID} -EventId {Event_ID}`
Results in:
`Get-MgGroupCalendarEvent_Get: Recursive navigation is not allowed after property 'Events' according to the entity schema.`

My system:
PowerShell 7.0.0 (x64) both in User and Administrator elevations.
Also same result in PowerShell 5.1 Build 18362 Rev 752
Windows 10 1909 Build 18363.778
