### ISSUE TITLE
$chatId　の構文や記載のルールについて

### ISSUE THREAD

**Issue by takeshi-hayakawa** [microsoftgraph/msgraph-sdk-powershell#1765]
現在、Microsoft.Graph.Teams　を使用して、
Teamsのチャット（インスタントメッセージ）を一覧化するテストを行っておりますが、
構文エラーなのか出力ができません。
Teamsのチャットを一覧で表示させたいURLは以下の通りです。

（Teams Chat URL）
https://teams.microsoft.com/_?culture=ja-jp&country=jp#/conversations/19:28b388c76a9d46679b4e7b4bd8ed35c3@thread.v2?ctx=chat

（Reference）
https://learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&tabs=http#request

参考URLを拝見しましたが、理解ができませんでした。

（Original）
Import-Module Microsoft.Graph.Teams
$RequiredScopes = @("Chat.Read")
Connect-MgGraph -Scopes $RequiredScopes

$chatId = "<19:28b388c76a9d46679b4e7b4bd8ed35c3@thread.v2?>"　＜＝＝？？？
$chatMessages = Get-MgChatMessage -ChatId $chatId -All -PageSize 50

そもそも数名に送付するチャット（インスタントメッセージ）はMicrosoftGraphで一覧表示できないのでしょうか？
それとも、記述の仕方に誤りがあるのでしょうか？

ご教示の程よろしくお願いいたします。

**Comment by peombwa** [comment]
Please share a detailed description of the issue. Your response should include:
1. Debug out of the failing command:
``` powershell
# Provide -Debug output here.

```

2. Loaded modules: 
``` powershell
# Provide output of Get-Module here.

```

3. Detailed repro steps, if any:
``` powershell
# Provide repro steps here.

```

See [Troubleshooting common errors in Microsoft Graph PowerShell](https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0) for more details.

**Comment by peombwa** [comment]
Thanks for the -Debug log.

The request is failing because you are passing a malformed chatId. As stated in the service response (`Invalid MRI, should start with digits and colon`), the chatId (`$chatId = "<19:28b388c76a9d46679b4e7b4bd8ed35c3@thread.v2?>"`) has a leading `<` and ending `?>` in the chatId, which is not correct.

As shown in the [API reference examples](https://learn.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&tabs=http#example-1-get-a-group-chat), the chatId should be `19:28b388c76a9d46679b4e7b4bd8ed35c3@thread.v2`.

**Comment by takeshi-hayakawa** [comment]
I RESOLVED #CHATID.
Could you please close to this issue.
