### ISSUE TITLE
Get-MgDriveItemContent saves to wrong path if file has no extension

### ISSUE THREAD

**Issue by guinoronha2** [microsoftgraph/msgraph-sdk-powershell#1775]
If try to download a file using Get-MgDriveItemContent and this file has no extension, it creates a folder with the file name, and then saves the file inside that folder.

Microsoft.Graph.Files module version: 1.20
Tested in Windows 11, Windows Server 2012 R2

Example: 
$file = Get-MgDriveItem -DriveId $drive.id -DriveItemId "root:/noextensionfile:"
Get-MgDriveItemContent -DriveId $drive.id -DriveItemId $file.id -OutFile c:\temp\$($file.name)

Edit: For some reason the command above is being altered when I post it. So here's a screenshot of the same:
![image](https://user-images.githubusercontent.com/123949909/215469269-543f623b-3690-4f66-8778-b40cd1c4a733.png)

Expected behavior:
File named "noextensionfile" is saved in "C:\Temp"
Full path is: C:\temp\noextensionfile

What actually happens:
A folder named "noextensionfile" is created under C:\Temp and the file is saved in it. The actual full path of the file is: C:\temp\noextensionfile\noextensionfile

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

I can indeed confirm that this is a bug in v1.x. The issue is not reproducible when using `v2.x` (preview):
![image](https://user-images.githubusercontent.com/7061532/216199929-d7cf0242-3684-41d7-a00b-1be4af8c25d3.png)

We will investigate and provide a bug fix in our upcoming releases for v1.x.

As a workaround, you can:
- Use [`v2.x` preview](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/features/2.0/docs/upgrade-to-v2.md).
- Specify an extension when downloading the file.

**Comment by guinoronha2** [comment]
Thanks! I'll try v2 preview in the meantime.
