### ISSUE TITLE
Connect-MgGraph: Support popup authentication window using WebView2

### ISSUE THREAD

**Issue by jasoth** [microsoftgraph/msgraph-sdk-powershell#1783]
WebView2 with MSAL would allow a popup browser on Windows that supports FIDO2 and CBA auth methods.
https://learn.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by peombwa** [comment]
Thanks for following up on this.

We will be adding support for [WAM](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/wam) as our default auth popup in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1133. The [recommendation from MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3270#issuecomment-1119470270) is to use WAM on Windows instead of WebView since it's more secure.
