### ISSUE TITLE
get-mguser with -Filter returns empty AdditionalProperties 

### ISSUE THREAD

**Issue by Janooski** [microsoftgraph/msgraph-sdk-powershell#1815]
This thread is based on this issue, which I am reopening as I experience the same issue: https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1171.

I want to start with the info, that I can confirm everything that was written in the initial thread. I can see all attributes when using `Get-MgUser -UserId $USER_ID | Select -ExpandProperty AdditionalProperties` but when using -Filter it returns the AdditionalProperties as {} (as written in this thread). 

My problem isn't solved, as extensionAttributes remain under AdditionalProperties and are not returned when using -Filter. I get all users with a license with the following neat command:

`Get-MgUser -Filter 'assignedLicenses/$count ne 0' -ConsistencyLevel eventual -CountVariable unlicensedUserCount -All -Property "id, assignedLicenses, givenName, surname, userPrincipalName, AdditionalProperties"`

But I need a value stored in the extensionAttributes for further filtering, but this doesn't work conveniently as the extensionAttributes are just not returned. I can work around this by starting a new Get-MgUser -UserId request for each user, which then returns the needed extensionAttribute value, but increases the time the script takes massively (from under 10 minutes to multiple hours). I would appreciate any help on this. Thanks!

_Originally posted by @Janooski in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1171#issuecomment-1429947729_

**Comment by peombwa** [comment]
@Janooski, this is by design. The extension properties are not returned because you haven't included them in your `$select`/`-Property` parameter.

`$select`/`-Property` is used to limit the properties returned by a query to those needed by your app. This is mentioned at https://learn.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#optional-query-parameters:
> To return an alternative property set, specify the desired set of [user](https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0) properties using the OData $select query parameter. For example, to return displayName, givenName, and postalCode, add the following to your query $select=displayName,givenName,postalCode.


Please include the required extension properties in the `-Property` parameter as show at https://learn.microsoft.com/en-us/graph/extensibility-overview?tabs=powershell#retrieve-a-directory-extension:
``` PowerShell
Get-MgUser -Filter 'assignedLicenses/$count ne 0' -ConsistencyLevel eventual -CountVariable unlicensedUserCount -All -Property "id, assignedLicenses, givenName, surname, userPrincipalName, extension_XXXXX"
```
![image](https://user-images.githubusercontent.com/7061532/221327676-9778ba94-f2d1-4b88-b073-5c6c43f66f88.png)

Alternatively, you can call `Get-MgUser` without `-Property` to have all properties returned:
``` powershell
 Get-MgUser -Filter 'assignedLicenses/$count ne 0' -ConsistencyLevel eventual -CountVariable unlicensedUserCount -All | Select -ExpandProperty AdditionalProperties
```

Please note that `AdditionalProperties` is not part of the response you get from the service. It is a Microsoft Graph PowerShell specific property that holds "extra" properties that are not part of the official schema. These include directory extensions.

**Comment by Janooski** [comment]
I can confirm that it works when adding the name of the extensionAttribute under -Property. It is still a bit confusing that -Filter and -UserID work differently. But I appreciate your help on this!
