### ISSUE TITLE
Dependency conflict with azure powershell (Az.Attestation)

### ISSUE THREAD

**Issue by sopelt** [microsoftgraph/msgraph-sdk-powershell#1818]
# Issue Description

Starting with [Microsoft.Graph.Authentication 2+](https://www.powershellgallery.com/packages/Microsoft.Graph.Authentication/2.0.0-preview5) there is a dependency conflict with azure powershell. [Az.Attestation](https://www.powershellgallery.com/packages/Az.Attestation/2.0.0) as well as this module both deliver `Microsoft.IdentityModel.Tokens.dll` as a dependency and they are not compatible. Depending which of the two modules has been loaded/imported/used first, the other one breaks.

Powershell code that deals with Az and Mg is quite common in project doing Azure provisioning via powershell which makes this quite "unpleasent" to say the least.

# Symptoms

`Connect-MgGraph` fails with the following error:

> Connect-MgGraph: Invalid JWT access token.

# Repro

```PowerShell
docker run -it mcr.microsoft.com/powershell:ubuntu-22.04

Install-Module -Name Az.Attestation -RequiredVersion 2.0.0 -Force
Install-Module -Name Microsoft.Graph.Authentication -RequiredVersion 2.0.0-preview5 -AllowPrerelease -Force

Import-Module -Name Az.Attestation -Version 2.0.0
Import-Module -Name Microsoft.Graph.Authentication -Version 2.0.0

Connect-MgGraph
```

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

We will be dropping the dependency on `Microsoft.IdentityModel.Tokens` due to https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1816. The conflict shouldn't occur once the dependency is dropped.

Our module already uses an assembly resolving handler that loads all our dependencies. However, this is currently limited to PowerShell 5.1 due lack of `AssemblyLoadContext` in `netstandard2.0`, which we target. One workaround would be to use the two modules in PowerShell 5.1:
![image](https://user-images.githubusercontent.com/7061532/221281594-322ea23e-214d-490b-9343-6d5ef1c8836a.png)


I'll use this issue to track using .NET's reflection API to create a custom `AssemblyLoadContext` when targeting `netstandard2.0`.

**Comment by sopelt** [comment]
Hi @peombwa , thank you for the update. Is there a timeframe on when this might be resolved?

**Comment by peombwa** [comment]
Sorry for the delayed response. The fix is ready (https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/1867) and should be go out as part of this week's release.

**Comment by helplessJ** [comment]
Happening to me on Ubuntu 22.04 fresh install today
