### ISSUE TITLE
Get-MgSecurityAlert returns a warning, but not the result

### ISSUE THREAD

**Issue by alexandair** [microsoftgraph/msgraph-sdk-powershell#1820]
When I run the `Get-MgSecurityAlert` command, I get the following warning:
```powershell
PS> Get-MgSecurityAlert
WARNING: 199 - "Microsoft/Microsoft Defender ATP/403/62", 199 - "Microsoft/Office 365 Security and Compliance/403/267"
```

Why am I getting this warning?

Running the same command with the `-Debug` switch, I've realized that `Get-MgSecurityAlert` targets the legacy alert endpoint `/alerts`, but not the new `'/alerts_v2` endpoint. When I run `Invoke-MgGraphRequest` and target the `'/alerts_v2` endpoint, I get the expected result.
Is there a cmdlet that works with `'/alerts_v2` endpoint?

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

The command exists because `/alerts` is still declared as a valid endpoint in the service schema:
![image](https://user-images.githubusercontent.com/7061532/220490531-b00f0f90-fea3-4ae1-b1f3-142670852b15.png)

We will add support for `/alerts_v2` endpoint in the upcoming releases.

**Comment by peombwa** [comment]
Closing as fixed by https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/2.0.0-preview6
