### ISSUE TITLE
Get-MgUserContact shows permissions denied when running it from delegate access. 

### ISSUE THREAD

**Issue by CAllinson** [microsoftgraph/msgraph-sdk-powershell#1860]
Getting permissions errors when attempting to use these commands (UserID and TenantID omitted from this post)

connect-mggraph -TenantId _TENANTID_ -Scopes "Contacts.ReadWrite"
Get-MgUserContact -UserId _USERID_

Get-MgUserContact : Access is denied. Check credentials and try again.
At line:1 char:1
+ Get-MgUserContact -UserId _USERID_
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ UserId = 8c1c..., Property =  }:<>f__AnonymousType37`8) [Get-MgUser
   Contact_List], RestException`1
    + FullyQualifiedErrorId : ErrorAccessDenied,Microsoft.Graph.PowerShell.Cmdlets.GetMgUserContact_List

**Comment by peombwa** [comment]
Thanks for following up on this.

Is `-UserId USERID` the id of the signed-in user? If not, then this is by design. `Contacts.ReadWrite` in delegate access only allows you to read contacts of the signed-in user.

You will need to consent to `Contacts.Read.Shared` to view shared contacts, or use application permission to read contacts of all users. See https://learn.microsoft.com/en-us/graph/api/user-list-contacts?view=graph-rest-1.0&tabs=http and https://learn.microsoft.com/en-us/graph/permissions-reference#contacts-permissions.
> Get a contact collection from the default contacts folder of the signed-in user.

> There are two scenarios where an app can get contacts in another user's contact folder:
> If the app has application permissions, or,
If the app has the appropriate delegated [permissions](https://learn.microsoft.com/en-us/graph/api/user-list-contacts?view=graph-rest-1.0&tabs=http#permissions) from one user, and another user has shared a contact folder with that user, or, has given delegated access to that user. See [details and an example](https://learn.microsoft.com/en-us/graph/outlook-get-shared-contacts-folders).
