### ISSUE TITLE
Move-MgUserMessage does not output the new message object

### ISSUE THREAD

**Issue by MikeShepard** [microsoftgraph/msgraph-sdk-powershell#1861]
https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.users.actions/move-mgusermessage?view=graph-powershell-1.0

The output section shows the output of the cmdlet as: Microsoft.Graph.PowerShell.Models.IMicrosoftGraphMessage1

There is in fact no output at all.

The same seems to be the case with Move-MgUserMailFolderMessage

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

We've already addressed this in v2 preview of the SDK as part of the success status code range support - [v2 Preview Blog Post](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-powershell-v2-is-now-in-public-preview-half-the-size-and-will-speed-up-your-automations/#unblock-scenarios-with-the-new-success-range-code-support). However, there is currently a bug in v2 preview which results in the command being named `Move-MgUsersMessage` instead of `Move-MgUserMessage`.

![image](https://user-images.githubusercontent.com/7061532/225750161-4fdf12eb-74ee-48ba-8886-306e628cdaa5.png)

The naming bug will be addressed in our upcoming v2 preview releases in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1788.
