### ISSUE TITLE
Get-MgDevice does not return the property userPrincipalName

### ISSUE THREAD

**Issue by RayGHeld** [microsoftgraph/msgraph-sdk-powershell#1886]
We cannot get the userPrincipalName in the output although it does show in the managed devices portal in Azure and in MS Graph Explorer:

![image](https://user-images.githubusercontent.com/40300226/226438954-4722d50a-e2df-470b-af4a-632304a42808.png)

![image](https://user-images.githubusercontent.com/40300226/226439232-31a421f1-0072-4c9a-b50c-3aac49c89227.png)

**Comment by SeniorConsulting** [comment]
I don't think this property is floated using the **_devices_** API endpoint. To see what I mean, jump onto Graph Explorer (https://developer.microsoft.com/en-us/graph/graph-explorer), and run the absolute URI you're seeing in your script - feel free to exclude the ?Selectxxx part so that you get all the properties.

I think what you're looking for is the DeviceManagementManagedDevices endpoint (Or in the PowerShell module, this is Get-MgDeviceManagementManagedDevice.

I hope this helps!

**Comment by peombwa** [comment]
Thanks for following up on this.

As stated by @SeniorConsulting, `userPrincipalName` is not a property of a `device` type as per the API reference - https://learn.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta#properties. Please use [Get-MgDeviceManagementManagedDevice](https://learn.microsoft.com/en-us/graph/api/intune-devices-manageddevice-list?view=graph-rest-1.0#request) instead.
