### ISSUE TITLE
Issue: How to retrieve members of a set of AzureAD groups using PowerShell Microsoft Graph

### ISSUE THREAD

**Issue by LH1959** [microsoftgraph/msgraph-sdk-powershell#1905]
I'm having a problem getting all members of a range of groups from AzureAD.
Who can help me?
Thank you in advance   
With the script below I can retrieve the members of 1 group and that works fine.

Connect-MgGraph
$GROUP_NAME = 'SUG-APP-MAN-SPBI_BICC-P'
$group = Get-MgGroup -Filter "DisplayName eq '$GROUP_NAME'"
$members = Get-MgGroupMember -GroupId $group.Id
$users = @()
foreach ($member in $members)
        {
        $user = Get-MgUser -UserId $member.Id
        $users += New-Object PSObject -Property @{Group = $group.DsplayName;
        Name = $user.DisplayName; 
        USERPRINCIPALNAME = $user.Mail}
        }
$users | Format-Table
    
This I am trying to retrieve all members of a range of groups.
The problem is how I define variable $GROUP_NAME
 
Connect-MgGraph
$GROUP_LIST = Get-MgGroup
foreach ($Group in $GROUP_LIST)
{
    $GROUP_NAME = $GROUP_LIST
    $group = Get-MgGroup -Filter "DisplayName eq '$GROUP_NAME'"
    $members = Get-MgGroupMember -GroupId $group.Id
    $users = @()
    foreach ($member in $members)
        {
        $user = Get-MgUser -UserId $member.Id
        $users += New-Object PSObject -Property @{Group = $group.DsplayName;
        Name = $user.DisplayName; 
        USERPRINCIPALNAME = $user.Mail}
        }
}
$users | Format-Table

**Comment by SeniorConsulting** [comment]
Hi LH1959,

Firstly, I've noticed a typo in your foreach loop:

> $group.DsplayName

I assume you're looking for $group.DisplayName

Secondly, to address your question - I'll need a little more info to complete writing what you're looking for, but I assume you want to list out the group members of every group in your tenant?
If that's the case, you'll need to add a -All flag to your second line ($GROUP_LIST = Get-MgGroup -All).
If you're not looking for all groups, but only a subset, you might be able to use a filter, such as:
`Get-MgGroup -filter "startsWith(DisplayName, 'SUG_APP')"`

Though if you're wanting to return groups with a particular name, you could try the search function:
`Get-MgGroup -search '"DisplayName:SUG_APP"' -ConsistencyLevel eventual`

For some more examples of those searches, refer to here:
https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.groups/get-mggroup?view=graph-powershell-1.0
or here:
https://learn.microsoft.com/en-us/graph/filter-query-parameter?tabs=http

Looking at your code, there are a few things to fix up. You shouldn't need to query graph again on your $group = Get-MgGroup line, or on the line after that, because you already have that information stored in $GROUP_LIST. You could also cut out on some extra queries by using the additionalproperties field. This would make any query run much faster.

My last piece of advice is that you're destroying the $Users array each loop, before outputting it, this is why you're not getting any output. It should be moved into the second foreach loop.

Overall, this gives you:
Connect-MgGraph
$GROUP_LIST = Get-MgGroup -search '"DisplayName:SUG_APP"' -ConsistencyLevel eventual
foreach ($Group in $GROUP_LIST){
    $members = Get-MgGroupMember -GroupId $group.Id
    $users = @()
    foreach ($member in $members){
        $users += New-Object PSObject -Property @{
        Group = $group.DisplayName;
        Name = $member.AdditionalProperties.displayName;
        USERPRINCIPALNAME = $member.AdditionalProperties.mail}
        $users | Format-Table
    }
}

**Comment by LH1959** [comment]
Thanks, the problem is already solved
