### ISSUE TITLE
Please add property "Date assigned" to applications assigned to a user.

### ISSUE THREAD

**Issue by msewaweru** [microsoftgraph/msgraph-sdk-powershell#1912]
https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/issues/220

**Comment by SeniorConsulting** [comment]
> If I use the GUI (portal.azure.com -> Users and then select a user, and then click on "Applications" on the left), I can see a list of applications that the user is permitted to use (either through admin consent or user consent). It includes a field "Date" on the list view. And if you click on the application's name, it displays a field "Date assigned". This is very useful (we recently had a phishing attack where a user's account was compromised and the attacker installed an app, which sent emails on their behalf). Even after resetting the password, the app was still there and still had permissions. By looking at the app details, we could see that it was installed on the date of the attack and then removed it for the user. We'd like to be able to run an analysis to see which apps were installed across the entire tenant in a certain timeframe to help identify other potential risks.
The Get-MgUserOauth2PermissionGrant seems to be the most promising cmdlet I could find... It gives the Id of the user and the app, as well as the scopes it has been granted access to. It would be great if you could add the date and time when the app was assigned to the user. It must be in there somewhere because the GUI picks up on it.

Hi outorted,

Is the cmdlet that you're looking instead Get-MgUserAppRoleAssignment? This more closely replicates what you're seeing on the Applications blade in Azure AD.

`Get-MgUserAppRoleAssignment -UserId John.Doe@contoso.com | Format-Table ResourceDisplayName,CreatedDateTime `

**Comment by peombwa** [comment]
@outorted, as pointed out by @SeniorConsulting, `CreatedDateTime` from [Get-MgUserAppRoleAssignment](https://learn.microsoft.com/en-us/graph/api/user-list-approleassignments?view=graph-rest-1.0&tabs=powershell#example-2-list-approleassignments-granted-to-a-user-filtered-by-resourceid) is what you are looking for.

Here is what the [API reference doc](https://learn.microsoft.com/en-us/graph/api/resources/approleassignment?view=graph-rest-1.0#properties) says about `CreatedDateTime` property:
> The time when the app role assignment was created. The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z. Read-only.

An app role assignment is:
> A relationship between the assigned principal (a user, a group, or a service principal), a resource application (the app's service principal) and an app role defined on the resource application.

**Comment by outorted** [comment]
Hi @SeniorConsulting  and @peombwa,
Thanks for the feedback. I've just tested and that gives me the information I'm looking for. I had originally hoped that I could find the information the other way around (i.e. look at the app and then find out when it was assigned to each of its users), but it looks like it is a user-centric query (i.e. look at the user and find out when each app was assigned). For my particular use case, that is not perfect and will slow down performance because I'll have to push everything through some foreach loops. But I appreciate that there are other use cases out there, for which the user-centric approach makes more sense.

Thanks again for your help. Please feel free to close this ticket/issue.

Best regards,
Steven
