### ISSUE TITLE
PowerShell 7 - Connect-MgGraph interactively possible bug

### ISSUE THREAD

**Issue by KG-droid** [microsoftgraph/msgraph-sdk-powershell#1923]
Hi all 

I'm not sure whether this is a bug or if I've just missed some additional step/s, but within Windows PowerShell, the command:

Connect-MgGraph -ClientId "YOUR_APP_ID" -TenantId "YOUR_TENANT_ID"

(for this command use a tenantid for an app registration which is separate from the tenant your signed into to the device from, or there maybe some way to force it to prompt for sign in if your already logged into the tenant on your device)

it works perfectly, it pops ups an integrated little browser window for you to login, and it all works fine, however when I attempt exactly the same thing in PowerShell 7.3.3 (not tried earlier versions), it instead opens up a new tab in MS Edge, and if I try to login, it then fails because the redirect url provided in the request is http://localhost and not https://login.microsoftonline.com/common/oauth2/nativeclient. 

Which I'm assuming is because its using MSEdge instead of the integrated browser and its giving that local host as the redirect url in its request. Question is, is this meant to happen, and the fix is to add http://localhost to the redirect urls on the app registration, or is this a bug?
The MSAL.PS module and the Get-MSALToken command still works with the integrated browser in PowerShell 7, so I'm assuming its not some blocker related to PS7 specifically, if the MSAL.PS module can still use the integrated browser.

**Comment by peombwa** [comment]
@KG-droid, since you are using a custom client id, you'll need to set the appropriate redirect URI on the app registration as stated at https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-client-application-configuration#redirect-uri-for-public-client-apps. In this case, you'll need to add both `http://localhost` (for PowerShell core) and `https://login.microsoftonline.com/common/oauth2/nativeclient` (for PowerShell 5.1) as the app's redirect URI in Azure Portal.

PowerShell 5.1 is built on top of .NET Framework (FW) app and PowerShell core is built on top .NET Core/.NET 5+. Our SDK uses the default browser for interactive auth in PowerShell 7.x since .NET Core doesn't have a UI for the embedded web view.

This will all be simplified when we add WAM support as part of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1133.

**Comment by KG-droid** [comment]
> @KG-droid, since you are using a custom client id, you'll need to set the appropriate redirect URI on the app registration as stated at https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-client-application-configuration#redirect-uri-for-public-client-apps. In this case, you'll need to add both `http://localhost` (for PowerShell core) and `https://login.microsoftonline.com/common/oauth2/nativeclient` (for PowerShell 5.1) as the app's redirect URI in Azure Portal.
> 
> PowerShell 5.1 is built on top of .NET Framework (FW) app and PowerShell core is built on top .NET Core/.NET 5+. Our SDK uses the default browser for interactive auth in PowerShell 7.x since .NET Core doesn't have a UI for the embedded web view.
> 
> This will all be simplified when we add WAM support as part of #1133.

Thanks :), I've added the localhost if that is the correct solution, and that's fixed it, and as it uses the actual Web browser you get to take advantage of the saved passwords too, is this documented anywhere, I couldn't find it. If not, is it worth adding a MS Kb somewhere for others to see? , as without the detail you have provided I wasn't sure if adding localhost was a recommended solution.
