### ISSUE TITLE
Cannot New-MgPlannerTask with recurrence

### ISSUE THREAD

**Issue by ontorder** [microsoftgraph/msgraph-sdk-powershell#1961]
I'm trying to create (updating would fine too i guess) a task with recurrence settings.
To do this I'm using the New-MgPlannerTask cmdlet in beta profile (it doesn't look like there is `-Recurrence` parameter in v1.0).
The problem is that the model seems incomplete? I send this:
```
new-mgplannertask
    -title <>
    -planid <>
    -bucketid <>
    -Recurrence @{schedule=@{pattern=@{type='absoluteMonthly';interval=1;dayOfMonth=30}}}
```
which debugging sends this:
```
Body:
{
  "bucketId": "<>",
  "dueDateTime": "2023-04-29T22:00:00Z",
  "planId": "<>",
  "title": "<>",
  "recurrence": {
    "schedule": {
      "pattern": {
        "type": "absoluteMonthly",
        "dayOfMonth": 30,
        "interval": 1
      }
    }
  }
}
```
then the cmdlet exits with the error
`Validation for field 'Recurrence.Schedule.Range', on entity 'Task' has failed:`
and I know this entity is required, but there is no mention of it in documentation and I have no idea where to put it (and all my attempts to add it to the command failed).

Version is 1.25

Trying directly from graph explorer I see the error message comes from there, still I'm looking in the models but to no avail.

**Comment by peombwa** [comment]
Thanks for following up on this.

Please open a question at https://developer.microsoft.com/en-us/graph/support to get assistance from the API owner as this is a service-related issue that can be reproduced in Graph Explorer.

This repository is intended for issues related to the functionality of the module (bugs and feature requests). We may not be the best place to answer some queries that are tied to the functionality of the API or how to use an API.

`-Recurrence` is missing in v1.0 because it is only available in beta. See https://learn.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-1.0#properties.

**Comment by ontorder** [comment]
Ok, so then are you able to create a task with -Recurrence?

**Comment by ontorder** [comment]
trying a hopefully not too quick test:
```
> Update-MgPlannerTask -ifmatch '<etag>' -plannertaskid <task id> -Recurrence @{schedule=@{pattern=@{type="absoluteMonthly";interval=1;dayOfMonth=30}}}
Update-MgPlannerTask : Schema validation has failed. Validation for field 'Recurrence.Schedule.Range', on entity 'Task' has failed: A non-null value must be specified for this field.
At line:1 char:1
+ Update-MgPlannerTask -ifmatch ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ PlannerTaskId...hPlannerTask1 }:<>f__AnonymousType35`3) [Update-MgPlannerTask_UpdateExpanded1], RestException`1
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.UpdateMgPlannerTask_UpdateExpanded1
```
seems kinda the same error, and no 'range' field/object in the doc for update-mgplannertask
(i confirm i used beta cmdlet and beta doc page)

**Comment by peombwa** [comment]
> Please open a question at https://developer.microsoft.com/en-us/graph/support to get assistance from the API owner as this is a service-related issue that can be reproduced in Graph Explorer.

Thanks for confirming.

This is a service error since the API is failing to validate the property despite it being documented as supported. Please open a question/ticket at https://developer.microsoft.com/en-us/graph/support to get assistance from the API owner. Remember to include the `request-id` and `date` of the failing request in the questions/ticket. See [Microsoft Graph PowerShell module troubleshooting guide](https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug) for more details.

**Comment by ontorder** [comment]
i had not much luck with this; not much else to do
