### ISSUE TITLE
Get-MgUser imports an alternate version of Microsoft.Graph.Authentication, causing AggregateException error

### ISSUE THREAD

**Issue by Lauwnch** [microsoftgraph/msgraph-sdk-powershell#1981]
Hello,

Working with a fresh install of Microsoft.Graph from PSGallery. After Connect-MgGraph, Microsoft.Graph.Authentication version 1.25.0 is imported. Then, once Get-MgUser is run, Microsoft.Graph.Authentication version 1.27.0 is imported. Per past issues on this project where AggregateException occurred, this version mismatch may be responsible, but not sure how to resolve on my end since the module is responsible for these imports.

Only thing that you don't see in the snippet below is that, in a previous powershell session, I did run Select-MgProfile -Name "beta".

Any help is appreciated!

```
Windows PowerShell

Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\WINDOWS\system32> Get-Module Microsoft.Graph.Identity.DirectoryManagement, Microsoft.Graph.Authentication | Select Name, Version
PS C:\WINDOWS\system32> Update-Module Microsoft.Graph
PS C:\WINDOWS\system32> Connect-MgGraph
Welcome To Microsoft Graph!
PS C:\WINDOWS\system32> Get-Module Microsoft.Graph.Identity.DirectoryManagement, Microsoft.Graph.Authentication | Select Name, Version

Name                           Version
----                           -------
Microsoft.Graph.Authentication 1.25.0


PS C:\WINDOWS\system32> Get-MgUser -All
Get-MgUser : One or more errors occurred.
At line:1 char:1
+ Get-MgUser -All
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgUser_List1], AggregateException
    + FullyQualifiedErrorId : System.AggregateException,Microsoft.Graph.PowerShell.Cmdlets.GetMgUser_List1

PS C:\WINDOWS\system32> Get-Module Microsoft.Graph.Identity.DirectoryManagement, Microsoft.Graph.Authentication | Select Name, Version

Name                           Version
----                           -------
Microsoft.Graph.Authentication 1.25.0
Microsoft.Graph.Authentication 1.27.0


PS C:\WINDOWS\system32> Get-MgContext


ClientId              :  <redacted>
TenantId              :  <redacted>
CertificateThumbprint :
Scopes                : {Application.Read.All, Application.ReadWrite.All, Directory.Read.All, Group.ReadWrite.All...}
AuthType              : Delegated
AuthProviderType      : InteractiveAuthenticationProvider
CertificateName       :
Account               :  <redacted>
AppName               : Microsoft Graph PowerShell
ContextScope          : CurrentUser
Certificate           :
PSHostVersion         : 5.1.22621.963



PS C:\WINDOWS\system32>
```

**Comment by peombwa** [comment]
Thanks for following up on this.

The error is due to different versions of the modules being auto loaded by PowerShell in your session. You'll need to restart your PowerShell session either before or after running `Update-Module Microsoft.Graph`.

> Only thing that you don't see in the snippet below is that, in a previous powershell session, I did run Select-MgProfile -Name "beta".

Running `Select-MgProfile -Name "beta"` auto imports `Microsoft.Graph.Authentication v1.25.0`. `Update-Module Microsoft.Graph` updates the locally installed modules to `v1.27.0`. Running `Get-MgUser -All` after the update means you are importing the latest version of `Microsoft.Graph.Users` (`v1.27.0`), which auto-imports `Microsoft.Graph.Authentication v1.27.0` hence the error.

PowerShell does not unload imported modules when you update them. You'll need to restart the PowerShell session to use the newly updated modules.

**Comment by Lauwnch** [comment]
Thanks for the response @peombwa.

Restarted computer, fresh powershell session, issue persists:

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\WINDOWS\system32> Get-Module Microsoft.Graph.Identity.DirectoryManagement, Microsoft.Graph.Authentication | Select Name, Version
PS C:\WINDOWS\system32> Connect-MgGraph
Welcome To Microsoft Graph!
PS C:\WINDOWS\system32> Get-Module Microsoft.Graph.Identity.DirectoryManagement, Microsoft.Graph.Authentication | Select Name, Version

Name                           Version
----                           -------
Microsoft.Graph.Authentication 1.25.0


PS C:\WINDOWS\system32> Get-MgUser
Get-MgUser : One or more errors occurred.
At line:1 char:1
+ Get-MgUser
+ ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgUser_List1], AggregateException
    + FullyQualifiedErrorId : System.AggregateException,Microsoft.Graph.PowerShell.Cmdlets.GetMgUser_List1

PS C:\WINDOWS\system32> Get-Module Microsoft.Graph.Identity.DirectoryManagement, Microsoft.Graph.Authentication | Select Name, Version

Name                           Version
----                           -------
Microsoft.Graph.Authentication 1.25.0
Microsoft.Graph.Authentication 1.27.0


PS C:\WINDOWS\system32>
```

**Comment by peombwa** [comment]
@Lauwnch, your repro steps shows `Microsoft.Graph.Authentication v1.25.0` wrongly being auto loaded by PowerShell despite having `v127.0` installed. This could be due to two issues:
- PowerShell is wrongly importing an older version as part of its auto load feature. For this, you'll need to uninstall the older version of the module and do a fresh install. See https://learn.microsoft.com/en-us/powershell/microsoftgraph/installation?view=graph-powershell-1.0#uninstalling-the-sdk for more details. Alternatively, you can upgrade to the latest version of PowerShell at https://aka.ms/PSWindows.
- Something is wrong with how the conflicting modules are installed on your machine.

I can't repro this behavior in PowerShell 5.1 despite having both v1.25.0 and v1.27.0 of the modules installed on my machine.

Could you share the output of the following to right after the error message:
``` powershell
Get-Module Microsoft.Graph.Users, Microsoft.Graph.Authentication -ListAvailable | Select Name, Version, ModuleBase
```

**Comment by Lauwnch** [comment]
@peombwa Thanks especially for that final tip - checking the ModuleBase of both versions of Microsoft.Graph.Authentication untangled the mystery.

On my previous work computer, Microsoft.Graph (v1.25.0) was installed in my <user profile>\Documents\WindowsPowershell\Modules. OneDrive must have sync'd that location, and brought that folder over to this new machine. 

On the new machine, when I installed Microsoft.Graph (v1.27.0), it installed to Program Files\WindowsPowershell\Modules.

My PSModulePath lists the user profile location first, so it pulls the Connect-MgGraph from there, loading v1.25.0 of Microsoft.Graph.Authentication. Then when I call Get-MgUser, it uses the Program Files version (v1.27.0) since Microsoft.Graph.Users isn't present in my user profile module location.

Resolved by uninstalling the module, deleting the graph modules out of my user profile location, and re-installing the module.

Thanks again!
