### ISSUE TITLE
Unable to obtain customSecurityAttributes

### ISSUE THREAD

**Issue by DarrenGowing** [microsoftgraph/msgraph-sdk-powershell#1990]
I am trying to obtain customSecurityAttributes using Get-MgUser. I have tried:

Select-MgProfile -Name beta
$userId = 'userID'
$userCSA = Get-MgUser -UserId $userId -Property "customSecurityAttributes"
$userCSA.CustomSecurityAttributes.AdditionalProperties | fl

I can then get the key and value:

Key   : TestKey
Value : {[@odata.type, #microsoft.graph.customSecurityAttributeValue], [**ExamUsername**, Blank], [**ExamPassword**, Blank]}

Then I'm stuck. What I want to do is output "UserPrincipalName,Id,EmployeeId,ExamUsername,ExamPassword"

Has anyone got any thoughts on how to do this?

FYI:

I have tried this way: 

Get-MgUser -UserId $userId -Property "customSecurityAttributes","userPrincipalName" | Select-Object "userPrincipalName" -ExpandProperty customSecurityAttributes | Select-Object "UserPrincipalName","AdditionalProperties" -ExpandProperty AdditionalProperties

Which outputs Key and Value put no userPrincipalName

Key          Value
---          -----
TestKey {[@odata.type, #microsoft.graph.customSecurityAttributeValue], [ExamPassword, Blank], [ExamUsername, …

If I add **| get-member** I can see the username is listed but it won't display:

![image](https://user-images.githubusercontent.com/122686407/235704339-08f2a43a-8b44-4e1f-91de-74c55a6f4129.png)

Hope someone can help.

**Comment by peombwa** [comment]
Thanks for following up on this.

`CustomSecurityAttributes` is an open type i.e., it's properties can be anything that you specify. Because of this, custom security attribute properties can only be accessed via `additionalProperties` bag.

You can use [PowerShell's calculate property with Select-Object](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/select-object?view=powershell-7.3#-property) to "flatten" CustomSecurityAttribute properties to the top-level as such:
``` powershell
$User = Get-MgUser -UserId $UserId -Property UserPrincipalName, CustomSecurityAttributes
$User | Select-Object `
UserPrincipalName,
@{Name = "ProjectDate"; Expression = { $_.CustomSecurityAttributes.AdditionalProperties.Engineering.ProjectDate } },
@{Name = "ProjectName"; Expression = { $_.CustomSecurityAttributes.AdditionalProperties.Engineering.ProjectName } }
```
