### ISSUE TITLE
Invoke-MgInvalidateUserRefreshToken not working on Graph 1.0

### ISSUE THREAD

**Issue by ciocodeea** [microsoftgraph/msgraph-sdk-powershell#2003]
The cmdlet Invoke-MgInvalidateUserRefreshToken doesn't seem to exists in Graph 1.0. I get this error **The term 'Invoke-MgInvalidateUserRefreshToken' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again**. I saw a thread that says if works only for beta, but what is the replacement for 1.0?

**Comment by peombwa** [comment]
Thanks for reaching out.

Please use `Revoke-MgUserSignInSession` instead. `InvalidateAllRefreshTokens` API/command was replaced by `Revoke-MgUserSignInSession`/`revokeSignInSessions` API. See blog post announcement at https://devblogs.microsoft.com/microsoft365dev/breaking-change-invalidate-all-refresh-tokens-update-in-microsoft-graph-beta/.

`Revoke-MgUserSignInSession` is available in both v1.0 and beta endpoint. `Invoke-MgInvalidateUserRefreshToken`/`invalidateAllRefreshTokens` is only available in beta.

You can follow [API changelog](https://developer.microsoft.com/en-us/graph/changelog/?search=invalidateAllRefreshTokens) for official API updates.

**Comment by ciocodeea** [comment]
Thank you for your answer! I found in the meantime the link for the API command aka **_revokeSignInSession_** https://learn.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-1.0&tabs=powershell
The example for the PowerShell request is **_Revoke-MgUserSign_** and the article is much newer. In the changelog there isn't anything newer than 2019.

**Comment by peombwa** [comment]
`Revoke-MgUserSign` is an alias for `Revoke-MgUserSignInSession`. The PowerShell snippet in API reference doc will need to be updated to show the actual command name, not the alias. I've opened an issue to track this at https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1551.

> In the changelog there isn't anything newer than 2019.

That's because the API hasn't changed since then. The [replacement of `InvalidateAllRefreshTokens` with `revokeSignInSessions`](https://devblogs.microsoft.com/microsoft365dev/breaking-change-invalidate-all-refresh-tokens-update-in-microsoft-graph-beta/) happened in 2019. `revokeSignInSessions` has been available in both v1.0 and beta since 2019.

**Comment by peombwa** [comment]
Aha! Thanks for flagging this in the doc. I've transferred the issue to the docs team for cmdlet map to be updated - https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/issues/284.

**Comment by petero-dk** [comment]
The old powershell command is still referenced in the Microsoft Entra blade for review of Permissions:

<img width="911" height="463" alt="Image" src="https://github.com/user-attachments/assets/e4b33469-bd5e-4a0f-b15b-7eb6a4fb1693" />
