### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by gmantri** [microsoftgraph/msgraph-sdk-powershell#2007]
Not sure if this is the right place to report issues with the documentation but I found a typo in [`New-MgApplication`](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.applications/new-mgapplication?view=graph-powershell-1.0) and [`Update-MgApplication`](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.applications/update-mgapplication?view=graph-powershell-1.0). 

Under `API` section, the name of the property should be `KnownClientApplication` instead of `KnownClientApplications`. 

This is based on the SDK documentation here: https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.powershell.cmdlets.resources.msgraph.models.apiv10.imicrosoftgraphapiapplication.knownclientapplication?view=az-ps-latest#microsoft-azure-powershell-cmdlets-resources-msgraph-models-apiv10-imicrosoftgraphapiapplication-knownclientapplication

**Comment by peombwa** [comment]
Thanks for following up on this.

This is not a typo. The property is named `KnownClientApplications` in the official API schema - https://learn.microsoft.com/en-us/graph/api/resources/apiapplication?view=graph-rest-1.0#properties. The API schema is our single source of truth for property names.

The documentation at https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.powershell.cmdlets.resources.msgraph.models.apiv10.imicrosoftgraphapiapplication.knownclientapplication?view=az-ps-latest#microsoft-azure-powershell-cmdlets-resources-msgraph-models-apiv10-imicrosoftgraphapiapplication-knownclientapplication is for Azure PowerShell module, not this module. Please follow up with the module author.

**Comment by gmantri** [comment]
@peombwa - Thanks for looking into this. I completely agree that the name of the property in the REST API is `knownClientApplications` however if you look at the property name in the PowerShell SDK, it is named as `KnownClientApplication` (and the JSON serialization name is `knownClientApplications`) but in the documentation for `New-MgApplication` and `Update-MgApplication`, the property is named as `KnownClientApplications`. If I use this name in my PS code, the `knownClientApplications` property is not updated. It gets updated properly if I use `KnownClientApplication`, the property is updated properly.

To summaize,

following code works:

```
[Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphApiApplication ]$azureAdApiAppApiSettings = @{
    KnownClientApplication=@("some guid");
}
```

and this does not work (and no errors are thrown):

```
[Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphApiApplication ]$azureAdApiAppApiSettings = @{
    KnownClientApplications=@("some guid");
}
```

**Comment by peombwa** [comment]
@gmantri, the provided examples are not working as expected because you are mixing Azure PowerShell SDK and Microsoft Graph PowerShell SDK types and property names.

`[Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphApiApplication]` is exclusively meant for use with [New-AzADApplication](https://learn.microsoft.com/en-us/powershell/module/az.resources/new-azadapplication?view=azps-9.7.1) in Azure PowerShell SDK, not this module. Please take note of the namespace difference, `Microsoft.Azure.PowerShell` vs `Microsoft.Graph.PowerShell`.

You'll need to use `Microsoft.Graph.PowerShell.Models.IMicrosoftGraphApiApplication` type to use the property with `New-MgApplication` or `Update-MgApplication` as shown in the [cmdlet reference doc](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.applications/new-mgapplication?view=graph-powershell-1.0#inputs) i.e:
``` powershell
[Microsoft.Graph.PowerShell.Models.IMicrosoftGraphApiApplication]$azureAdApiAppApiSettings = @{
    KnownClientApplications=@("some guid");
}
```

Azure PowerShell SDK and Microsoft Graph PowerShell SDK are currently targeted at two different audiences. I've taken a note for us to review the interoperability of types between the two SDKs in future versions.

**Comment by gmantri** [comment]
@peombwa - I see. Thank you for clarifying. It is certainly a mistake from my side. However when I search for `IMicrosoftGraphApiApplication`, I am being redirected to Azure PowerShell SDK instead of Microsoft Graph PowerShell SDK. Can the documentation include links to proper SDK. That would be immensely helpful.

**Comment by peombwa** [comment]
Awesome! I'll follow up with the docs team internally to review the feasibility of publishing Microsoft Graph PowerShell SDK types to .NET API browser.
