### ISSUE TITLE
Get-MgPolicyIdentitySecurityDefaultEnforcementPolicy authentication issue

### ISSUE THREAD

**Issue by xaviervv** [microsoftgraph/msgraph-sdk-powershell#2018]
Within the same flow I can perfectly use Get-MgIdentityConditionalAccessPolicy, New-MgIdentityConditionalAccessPolicy and Update-Get-MgIdentityConditionalAccessPolicy

But when I use Get-MgPolicyIdentitySecurityDefaultEnforcementPolicy I am getting a scope authentication issue

```
Disconnect-MgGraph
Remove-Item "$env:USERPROFILE\.graph" -Recurse -Force

Connect-AzAccount
$graphToken = Get-AzAccessToken -ResourceTypeName MSGraph
Connect-MgGraph -AccessToken $graphToken.Token

$InformationPreference = 'Continue'

Write-Information "Get current scopes"
(Get-MgContext).scopes

$requiredScopeForDefaultPolicy = (Find-MgGraphCommand -Command Get-MgPolicyIdentitySecurityDefaultEnforcementPolicy -ApiVersion v1.0).Permissions.Name
Write-Information "Required scopes for default policy: $($requiredScopeForDefaultPolicy)"
# this will output Policy.Read.All

$requiredScopeForMfaPolicy = (Find-MgGraphCommand -Command Get-MgIdentityConditionalAccessPolicy -ApiVersion v1.0).Permissions.Name
Write-Information "Required scopes for mfa policy: $($requiredScopeForMfaPolicy)"
# this will output Policy.Read.All, Policy.Read.All

Get-MgPolicyIdentitySecurityDefaultEnforcementPolicy # will fail - authentication / scope

Get-MgIdentityConditionalAccessPolicy # will succeed

Connect-MgGraph -Scopes "Policy.Read.All"
Get-MgPolicyIdentitySecurityDefaultEnforcementPolicy # will succeed
```

Script aboves proves that both commands use the same scopes, yet one fails to execute. I do not understand the current behaviour. Is this a bug?

Some additional information: 
windows 11
powershell: 7.3.4
msgraph version1.27.0

**Comment by peombwa** [comment]
Thanks for following up on this.

You are getting the authentication error because the access token acquired using `Get-AzAccessToken` does not have the required `Policy.Read.All` permission:
> Connect-AzAccount
> $graphToken = Get-AzAccessToken -ResourceTypeName MSGraph
> Connect-MgGraph -AccessToken $graphToken.Token

Does `$graphToken.Token` have `Policy.Read.All` permission that's needed to call [the API](https://learn.microsoft.com/en-us/graph/api/identitysecuritydefaultsenforcementpolicy-get?view=graph-rest-1.0&tabs=http#permissions)? You can https://jwt.ms/ to decode the access token and inspect the assigned scopes.

AFIK, `Get-AzAccessToken` does not support incremental scope consent. Please use `Connect-MgGraph -Scopes "Policy.Read.All"` to consent the required permission before using `Get-MgPolicyIdentitySecurityDefaultEnforcementPolicy`.

`GET /identity/conditionalAccess/policies (Get-MgIdentityConditionalAccessPolicy)` is probably succeeding in error or it supports `Directory.AccessAsUser.All`, which isn't documented. The API is listed as requiring `Policy.Read.All` permission - https://learn.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-1.0&tabs=http. I'd recommend you follow up with the API owner at https://developer.microsoft.com/en-us/graph/support.
