### ISSUE TITLE
Get-MgDeviceManagementDeviceCompliancePolicy and null ScheduledActionsForRule and Assignments

### ISSUE THREAD

**Issue by tehmichael** [microsoftgraph/msgraph-sdk-powershell#2025]
Hello!  I noticed that Get-MgDeviceManagementDeviceCompliancePolicy doesn't populate the ScheduledActionsForRule and Assignments properties.  

Is this a bug or is there a different way to pull these properties?  Thank you!

**Comment by peombwa** [comment]
This is by design. The reference properties are not returned by default by the API since they are relationships. You'll need to use `-ExpandProperty` ([$expand](https://learn.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2Fbeta&view=graph-rest-beta&tabs=http#expand-parameter) when using the REST API) to retrieve the [reference properties (relationships)](https://learn.microsoft.com/en-us/graph/api/resources/intune-shared-devicecompliancepolicy?view=graph-rest-beta#relationships):
``` powershell
➜ Get-MgDeviceManagementDeviceCompliancePolicy -ExpandProperty ScheduledActionsForRule, Assignments | select ScheduledActionsForRule, Assignments

ScheduledActionsForRule                Assignments
-----------------------                -----------
{20e8abf8-9a33-44d8-8baf-78a805c35199} {20e8abf8-9a33-44d8-8baf-78a805c35199_8925b5be-893f-46ff-a85b-0557fabc9a5e}
```

**Comment by tehmichael** [comment]
Thank you for the response @peombwa !  Really appreciate you taking the time to get back.  Would I be able to pick your brain a little on exporting certain configurations?  Right now to export compliance policies I'm having to pick out the properties I want and manually write in the ScheduledActionsForRule (see below).  Do you have any recommendations on how I could export an Android or iOS compliance policy to a format that is easy to import using the Get-MgDeviceManagementDeviceCompliancePolicy -BodyParameter cmdlet?  Or are you aware of a spot that may have some examples to refer to?  Thank you!

`
$scheduledActionsForRule = @{
        '@odata.type'                 = '#microsoft.graph.deviceComplianceScheduledActionForRule'
        ruleName                      = 'PasswordRequired'
        scheduledActionConfigurations = @(
            @{
                '@odata.type' = '#microsoft.graph.deviceComplianceActionItem'
                actionType    = 'block'
            }
        )
    }
`
