### ISSUE TITLE
Request returned Non-Json response of OctetStream with Content-Disposition

### ISSUE THREAD

**Issue by nickp85** [microsoftgraph/msgraph-sdk-powershell#2088]
Seems Graph API calls are changing to a new format requiring POST with a body to specify filters/select values. When making one of these calls via Invoke-MsGraphRequest, the output is not JSON and the cmdlet complains that you need to output to a file. Invoke-RestMethod can supply the output to variables or on screen etc without needing an output file.

Invoke-MgGraphRequest : Request returned Non-Json response of OctetStream with Content-Disposition , Please specify '-OutputFilePath' or '-InferOutputFileName' 
At line:1 char:1
+ Invoke-MgGraphRequest POST -Uri "https://graph.microsoft.com/beta/dev ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Graph...eMgGraphRequest:InvokeMgGraphRequest) [Invoke-MgGraphRequest], ValidationMetadataException
    + FullyQualifiedErrorId : InvokeGraphContentTypeException,Microsoft.Graph.PowerShell.Authentication.Cmdlets.InvokeMgGraphRequest

Can these cmdlets be updated to handle non-Json response since Microsoft seems to be providing different outputs now?

Example:
Invoke-MgGraphRequest POST -Uri "https://graph.microsoft.com/beta/deviceManagement/reports/getDeviceInstallStatusReport" -body $body

I reversed engineered the new method from the Intune web GUI since the old method using the below has been removed it seems and now returns an HTTP400 since last week after working for years.

`https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/<id>/deviceStatuses`

Thanks

**Comment by peombwa** [comment]
`Invoke-MgGraphRequest` asking you to specify `'-OutputFilePath' or '-InferOutputFileName'` is by design. The original intent was to avoid automatically downloading files to the user's working directory without them explicitly opting into this. Using `-InferOutputFileName` switch, you can call the command to automatically download the file in your current working directory and infer the file name.

As for `https://graph.microsoft.com/beta/deviceManagement/reports/getDeviceInstallStatusReport` returning a 400. The API path is not documented as supported in the API reference docs - https://learn.microsoft.com/graph/api/resources/intune-reporting-devicemanagementreports?view=graph-rest-beta. Since this is the `beta` endpoint you are calling, I wouldn't be surprised if the API was changed as indicated in the [beta disclaimer](https://learn.microsoft.com/en-us/graph/api/overview?view=graph-rest-beta):
> The APIs in the beta endpoint are subject to change. We don't recommend that you use them in your production apps.


As per the API reference, [`GET /deviceAppManagement/mobileApps/{mobileAppId}/deviceStatuses`](https://learn.microsoft.com/en-us/graph/api/intune-apps-mobileappinstallstatus-get?view=graph-rest-beta&source=recommendations) is the API to call as you've pointed out above. Its response is a collection of JSON objects.

**Comment by nickp85** [comment]
> As per the API reference, GET /deviceAppManagement/mobileApps/{mobileAppId}/deviceStatuses is the API to call as you've pointed out above. Its response is a collection of JSON objects.

This API doesn’t exist anymore. The only way is the report way which results in a file download. There doesn’t appear to be a way to get the JSON anymore

**Comment by peombwa** [comment]
It looks others have also run into the same error when calling the API in recent past - https://github.com/microsoftgraph/microsoft-graph-docs/issues/21782.

I'd recommend you open a service feature request/question at https://developer.microsoft.com/graph/support for the API owner to review your scenario.
