### ISSUE TITLE
Update-MgIdentityConditionalAccessPolicy error code 1007

### ISSUE THREAD

**Issue by assistmeister** [microsoftgraph/msgraph-sdk-powershell#2091]
Hi y'all ! 

Since we've had a mishap with one of our customer with Conditional Access (and a horrible support story), we want to put in place a script in Azure Automate Account using a managed identity that will do a check up on any deny session control, and add us (being a service provider) in the exceptions.

Everything is working fine, except the adding part of the script. I really don't see what I'm doing wrong, and since the documentation is sparse as of today, I don't know where to go from here. 

There is the code : 
```
$params = @{
    Conditions = @{
        Users = @{
            ExcludeGuestsOrExternalUsers = @{
                GuestOrExternalUserTypes = @("serviceProvider")
                ExternalTenants = @{
                    MembershipKind = "enumerated"
                    AdditionalProperties = @{
                        "@odata.type" = "#microsoft.graph.conditionalAccessEnumeratedExternalTenants"
                        "members" = @("ff916034-0d5a-40db-a95f-xxxxxxxxxxxx")
                    }
                }
            }
        }
    }
}

$Policies = Get-MgIdentityConditionalAccessPolicy

$policy = $policies[5] # (This is a test policy in a sandbox environnement)

Update-MgIdentityConditionalAccessPolicy -ConditionalAccessPolicyId $policy.Id -BodyParameter $params -Verbose
```
Here is the full error message : 

Update-MgIdentityConditionalAccessPolicy_Update1: 1007: Incoming ConditionalAccessPolicy object is null or does not match the schema of ConditionalAccessPolicy type. For examples, please see API documentation at https://docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-update?view=graph-rest-1.0.

Any help would be appreciated !

**Comment by peombwa** [comment]
Thanks for following up on this.

The issue is coming from how `ExcludeGuestsOrExternalUsers` in `$params` is constructed:
- `GuestOrExternalUserTypes` is a string, which represents an enum value.
- `AdditionalProperties` should not be specified when using `-BodyParameter` parameter set.

Using the `-Debug` parameter on the command, we can see that the request body is not constructed as expected hence the error message:
<img width="632" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/7061532/7444801f-94a6-400b-a2c8-b431651fda8a">


The `$params` should be construct as shown below:
``` powershell
$params = @{
    Conditions = @{
        Users = @{
            ExcludeGuestsOrExternalUsers = @{
                GuestOrExternalUserTypes = "serviceProvider" # This is an enum according to the API reference, not an array.
                ExternalTenants = @{
                    MembershipKind = "enumerated"
                    "@odata.type" = "#microsoft.graph.conditionalAccessEnumeratedExternalTenants" # AdditionalProperties should not be specified when using -BodyParameter
                    "members" = @("ff916034-0d5a-40db-a95f-xxxxxxxxxxxx")
                }
            }
        }
    }
}
```
See https://learn.microsoft.com/en-us/graph/api/resources/conditionalaccessguestsorexternalusers?view=graph-rest-1.0 and https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/update-mgidentityconditionalaccesspolicy?view=graph-powershell-1.0#notes for more details.
