### ISSUE TITLE
Get-MgUser_List1: Expected comma, literal, or object. Was Eof: .

### ISSUE THREAD

**Issue by spottedmahn** [microsoftgraph/msgraph-sdk-powershell#2097]
When I execute `Get-MgUser` I get:

> Get-MgUser_List1: Expected comma, literal, or object. Was Eof: .

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/14079228/5110c653-6282-4cf4-86d1-0ff6e8e0f0cf)

What am I doing wrong?  I connected & that was successful.

```
PS C:\Users\mdepouw> Connect-MgGraph -Scopes "User.ReadBasic.All", "Application.ReadWrite.All"
```
> Welcome To Microsoft Graph!

---

I also tried the sample in the readme & that errors out too:

```
PS C:\Users\mdepouw> Get-MgUser -Top 10 -Property Id, DisplayName, BusinessPhones | Format-Table Id, DisplayName, BusinessPhones
```

>Get-MgUser_List1: The query specified in the URI is not valid. The limit of '0' for Top query has been exceeded. The value from the incoming request is '10'.

**Comment by SeniorConsulting** [comment]
That's one I haven't seen before. I would recommend running the command:
`Get-MgUser -debug`

The debug flag should take you through step by step, and give a bit more information. Choose what you think is relevant, and doesn't contain sensitive information such as authentication tokens, and upload 'em here. This should give the devs a wee bit more to work with.

**Comment by spottedmahn** [comment]
>PS C:\blah> Get-MgUser -debug
DEBUG: [CmdletBeginProcessing]: - Get-MgUser begin processing with parameterSet 'List1'.
DEBUG: [Authentication]: - AuthType: 'Delegated', AuthProviderType: 'InteractiveAuthenticationProvider', ContextScope: 'CurrentUser', AppName: ''.
DEBUG: [Authentication]: - Scopes: [].
DEBUG: ============================ HTTP REQUEST ============================

>HTTP Method:
GET

>Absolute Uri:
https://graph.microsoft.com/v1.0/users

>Headers:
FeatureFlag                   : 00000047
Cache-Control                 : no-store, no-cache
SdkVersion                    : graph-powershell/1.28.0,Graph-dotnet-1.25.1
User-Agent                    : Mozilla/5.0,(Windows NT 10.0; Microsoft Windows 10.0.19045; en-US),PowerShell/2023.6.0    
Accept-Encoding               : gzip

>Body:
DEBUG: ============================ HTTP RESPONSE ============================

>Status Code:
OK

>Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : 76a14505-78b2-4fba-a3b5-2d258c1e82ad
client-request-id             : 76a14505-78b2-4fba-a3b5-2d258c1e82ad
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"North Central US","Slice":"E","Ring":"3","ScaleUnit":"002","RoleInstance":"CH01EPF00022C9A"}}
OData-Version                 : 4.0
Date                          : Mon, 26 Jun 2023 13:07:00 GMT

>Body:
{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#users","value":[{"error":{"code":"InternalServerError","message":"Invalid response. Expected list response must have value property.","innerError":{"date":"2023-06-26T13:07:00","request-id":"76a14505-78b2-4fba-a3b5-2d258c1e82ad","client-request-id":"76a14505-78b2-4fba-a3b5-2d258c1e82ad"}}}


>DEBUG: [CmdletException]: Received exception with message 'ParserException - Expected comma, literal, or object. Was Eof: 
. :    at Microsoft.Graph.PowerShell.Runtime.Json.JsonParser.ReadArray()
   at Microsoft.Graph.PowerShell.Runtime.Json.JsonParser.ReadFieldValue()
   at Microsoft.Graph.PowerShell.Runtime.Json.JsonParser.ReadField()
   at Microsoft.Graph.PowerShell.Runtime.Json.JsonParser.ReadObject()
   at Microsoft.Graph.PowerShell.Runtime.Json.JsonParser.ReadNode()
   at Microsoft.Graph.PowerShell.Runtime.Json.JsonNode.Parse(SourceReader sourceReader)
   at Microsoft.Graph.PowerShell.Runtime.Json.JsonNode.Parse(String text)
   at Microsoft.Graph.PowerShell.Users.<>c.<UsersUserListUser1_Call>b__1433_0(Task`1 body)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgUser_List1.onOk(HttpResponseMessage responseMessage, Task`1 response)       
   at Microsoft.Graph.PowerShell.Users.UsersUserListUser1_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, 
IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Users.UsersUserListUser1_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, 
IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Users.UsersUserListUser1(String consistencyLevel, Nullable`1 Top, String Search, String Filter, Nullable`1 Count, String[] Orderby, String[] Select, String[] Expand, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgUser_List1.ProcessRecordAsync()'
Get-MgUser_List1: Expected comma, literal, or object. Was Eof: .
DEBUG: [CmdletEndProcessing]: - Get-MgUser end processing.

**Comment by SeniorConsulting** [comment]
Thanks for that. I can't dip my toes into the detail, as I'm not a dev of this, but comparing my command to yours, I do see some differences, where I _**might**_ be able to make some recommendations:

> DEBUG: [Authentication]: - AuthType: 'Delegated', AuthProviderType: 'InteractiveAuthenticationProvider', ContextScope: 'CurrentUser', AppName: ''.
> DEBUG: [Authentication]: - Scopes: [].

Mine returns two differences from yours:
DEBUG: [Authentication]: - AuthType: 'Delegated', AuthProviderType: 'InteractiveAuthenticationProvider', ContextScope:
'Process', AppName: '**Microsoft Graph Command Line Tools**'.
DEBUG: [Authentication]: - Scopes: [**Application.ReadWrite.All, AppRoleAssignment.ReadWrite.All, Group.ReadWrite.All,
GroupMember.Read.All, openid, profile, User.Read, User.Read.All, email**].

I wouldn't expect you to have _**all**_ of the scopes I've got in there, but at least some might be worthwhile, like the two you specified ("User.ReadBasic.All", "Application.ReadWrite.All"). Normally a lack of permissions would simply return a 403 though, rather than what you're seeing. Could be worth a shot trying to reauthenticate though, similarly to how you have in the past, but maybe try a single permission first - just something like your User.ReadBasic.All

As for the missing AppName, that's a curious one which I don't have any theories for. I'll wait to see if the devs come back.

**Comment by spottedmahn** [comment]
It appears to be related to work vs. personal account.

My work account on `Disconnect-MgGraph`:
>ClientId              : 795aeb11-e02b-4ed0-a198-ffc553aa6824
TenantId              : 6477136e-01f5-4660-ae0c-17db764fc884
CertificateThumbprint : 
Scopes                : {openid, profile, User.ReadBasic.All, email}
AuthType              : Delegated
AuthProviderType      : InteractiveAuthenticationProvider
CertificateName       : 
Account               : mdepouw@ceiamerica.com
AppName               : Microsoft Graph Command Line Tools
ContextScope          : CurrentUser
Certificate           :
PSHostVersion         : 2023.6.0

My personal account that is tied to my VS Subscription that is tied to my Azure subscription:
>ClientId              : 795aeb11-e02b-4ed0-a198-ffc553aa6824
TenantId              : 
CertificateThumbprint : 
Scopes                : 
AuthType              : Delegated
AuthProviderType      : InteractiveAuthenticationProvider
CertificateName       : 
Account               : 
AppName               : 
ContextScope          : CurrentUser
Certificate           : 
PSHostVersion         : 2023.6.0

I also see the same disconnect info for another personal MSFT account that is not associated w/ an Azure subscription.

---

sidenote, how can I get that info w/ performing `Disconnect-MgGraph`? 🤔

**Comment by spottedmahn** [comment]
>sidenote, how can I get that info w/ performing `Disconnect-MgGraph`? 🤔

[Get-MgContext](https://learn.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0#using-get-mgcontext)

**Comment by SeniorConsulting** [comment]
Yeah. I have a few different accounts (e.g. between my lab environment and my work environment), which is why when I sign in, I actually use Connect-MgGraph -ContextScope Process. For me, this means once I close my PowerShell window, it logs me out. Sounds like extra work to most people in having to sign in multiple times to use the cmdlets, but it provides me with a protective barrier where I'm _**less likely**_ (i.e. Not immune) to making a change in the wrong environment.

Let me know if you need any further help working this out, or whether you've managed to sort it out with a combination of authentication stuff.

**Comment by spottedmahn** [comment]
>whether you've managed to sort it out with a combination of authentication stuff

Are we able to use this SDK against personal accounts?  I didn't see anything in the readme/docs about this.

I have a personal account tied to my [VS subscription](https://visualstudio.microsoft.com/subscriptions/) that is tied to an Azure subscription.  Seems like this won't work 🤷‍♂️.

>I actually use `Connect-MgGraph -ContextScope Process`

I like it! 👍

**Comment by timayabi2020** [comment]
@spottedmahn thanks for identifying and raising this issue. This is, however, a service issue since its responding with a http status code 200 and an OData exception in the response body. Please open a support ticket/question at https://developer.microsoft.com/en-us/graph/support to get assistance from the API owner.
