### ISSUE TITLE
Filter to find unlicensed users does not work

### ISSUE THREAD

**Issue by carlosdzrz** [microsoftgraph/msgraph-sdk-powershell#2112]
I run the Get-MgUser command with the following filter: Filter = 'assignedLicenses/$count eq 0 and OnPremisesSyncEnabled eq true'. It always returns the same two results, which do not correspond to reality. Currently in the tenant I have 17 unlicensed users. Here is an example:
<img width="637" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/25250895/1dd4f958-8bbc-4bdc-a3d9-29db6098fa16">

**Comment by peombwa** [comment]
Thanks for following through on this.

Calling the command with `-Debug` will reveal that the inaccurate count is coming from the service. Please follow the [troubleshooting guide](https://learn.microsoft.com/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug) and open a service question with the API owner at https://developer.microsoft.com/en-us/graph/support for this to be invested.

**Comment by carlosdzrz** [comment]
I attach the transcript file with the debug parameter. I have deleted the personal information data of the tenant users.
I have opened a service question. thank you very much.
[debug.log](https://github.com/microsoftgraph/msgraph-sdk-powershell/files/11954682/debug.log)

**Comment by peombwa** [comment]
Thanks for providing the debug log. The debug log shows that the wrong count is coming from the API via the `@odata.count` response. I'd recommend you open a service issue at https://developer.microsoft.com/en-us/graph/support to get further assistance from the API owner. Please include the `requestId` and `date` of the affected request in your ticket/question. See [Microsoft Graph PowerShell module troubleshooting guide](https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug) for more details.

Since you are using v2 of SDK, can you confirm if the inconsistent count is also present when using the dedicated count commands - `Get-MgUserCount -Filter 'assignedLicenses/$count eq 0 and OnPremisesSyncEnabled eq true' -ConsistencyLevel eventual`. This command calls `GET https://graph.microsoft.com/v1.0/users/$count`.
