### ISSUE TITLE
Please finally fix this bug: "OperationStopped: Could not load file or assembly ‘System.IdentityModel.Tokens.Jwt"

### ISSUE THREAD

**Issue by schittli** [microsoftgraph/msgraph-sdk-powershell#2116]
Hello

it's a shame that M$ has no inner motivation to fix M$ bugs. Does M$ really tell customers that they have to search the way through different M$ teams so that they finally fix an issue, as you proposed it here?: https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1838#issuecomment-1444811912

Just to be sure:

1. We have installed a new Windows Server 2022
2. Then, we installed the M$ PowerShell Module `Microsoft.Graph`
3. We use the command `Connect-ExchangeOnline`
4. We get the error: **OperationStopped: Could not load file or assembly 'System.IdentityModel.Tokens.Jwt, Version=6.22.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621)**
5. According to `Get-Module Microsoft.Graph -ListAvailable | select ProjectUri` this project is responsible for `Microsoft.Graph`

### As long as M$ earns billions every months, 
it would be fair if M$ would fix bugs and don't wait months and years until some customer spends their spare time to fix it.

**Of course, as for any professional software, we expect** that you do not just let the SW crash as any beginner with 3 weeks of programming experience would do it, but that the Module checks the prerequisites and it heals itself or displays a working solution.

### And, please: Don't close the Ticket as long as the bug is not solved.
… or: forward the ticket to the right team and add a link here.

Thanks a lot, kind regards,
Thomas

**Comment by RayGHeld** [comment]
The Microsoft Graph PowerShell SDK and the ExchangeOnline powershell module are 2 totally different modules.  The connect-exchangeonline is tno going to get an access token for Microsoft Graph.  You should be using the Connect-MgGraph command instead to get an access token for Microsoft Graph.   https://learn.microsoft.com/en-us/powershell/microsoftgraph/overview?view=graph-powershell-1.0

**Comment by peombwa** [comment]
As mentioned in the referenced issue and as shown in your repro steps, the bug is present in [ExchangeOnlineManagement](https://www.powershellgallery.com/packages/ExchangeOnlineManagement) module when invoking (`Connect-ExchangeOnline`). Please use the dedicate support options for the affected module to report the bug - https://learn.microsoft.com/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#report-bugs-and-issues-for-the-exchange-online-powershell-module.

In the meantime, you could consider using [v2 version of this SDK](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/docs/upgrade-to-v2.md), which dropped the dependency on `System.IdentityModel.Tokens.Jwt`. Please also note RayGHeld's comment above on the interoperability between the two modules.

This repo is intended for issues exclusive to the Microsoft Graph PowerShell SDK. As such, external issues will be closed as there are dedicated support options for them.
