### ISSUE TITLE
When will v2.0.0 of Microsoft.Graph.DeviceManagement.Enrolment be available?

### ISSUE THREAD

**Issue by mark3grahams** [microsoftgraph/msgraph-sdk-powershell#2154]
### Discussed in https://github.com/microsoftgraph/msgraph-sdk-powershell/discussions/2152

<div type='discussions-op-text'>

<sup>Originally posted by **ztrhgf** July 12, 2023</sup>
We want to migrate all graph modules to version 2.0.0, but Microsoft.Graph.DeviceManagement.Enrolment is still just 1.28.0. When the version 2.0.0 will be released?</div>

I think it is moving to Microsoft.Graph.DeviceManagement.Enrollment fixing the spelling but many CMDlets are missing.

v1.28
(Get-Command -Module Microsoft.Graph.DeviceManagement.Enrolment).count       
390

v2.0
(Get-Command -Module Microsoft.Graph.DeviceManagement.Enrollment).count
24

v2.0 Beta
(Get-Command -Module Microsoft.Graph.Beta.DeviceManagement.Enrollment).count
190

**Comment by mark3grahams** [comment]
Also, in CMDlets you are now using Windows vs Window.

Microsoft.Graph.DeviceManagement.Enrolment
Get-MgDeviceManagementWindowAutopilotDeviceIdentity


Microsoft.Graph.DeviceManagement.Enrollment
Get-MgDeviceManagementWindowsAutopilotDeviceIdentity

**Comment by mark3grahams** [comment]
Which makes this link bad.

To view the beta release of this cmdlet, view [Get-MgBetaDeviceManagementWindowAutopilotDeviceIdentity](https://learn.microsoft.com/en-us/powershell/module/Microsoft.Graph.Beta.DeviceManagement.Enrolment/Get-MgDeviceManagementWindowAutopilotDeviceIdentity?view=graph-powershell-beta)

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

Please see the [breaking change guidance](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/docs/upgrade-to-v2.md#renamed-devicemanagementenrolment-module-to-devicemanagementenrollment) for more details:
> - `DeviceManagement.Enrolment` module was renamed to `DeviceManagement.Enrollment`.
> - Pluralized product names, such as `Windows`, were wrongly named to their singular form in v1, and have since been corrected in v2.

As for:
> Which makes this link and many others bad.
To view the beta release of this cmdlet, view [Get-MgBetaDeviceManagementWindowAutopilotDeviceIdentity](https://learn.microsoft.com/en-us/powershell/module/Microsoft.Graph.Beta.DeviceManagement.Enrolment/Get-MgDeviceManagementWindowAutopilotDeviceIdentity?view=graph-powershell-beta)

This is due to stale reference docs - https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/issues/322. Cmdlet reference doc for the now renamed `DeviceManagement.Enrolment` module shouldn't be there. The reference docs will be addressed in the referenced issue. Please use the reference docs for  `DeviceManagement.Enrollment` instead - [v1.0](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.devicemanagement.enrollment/?view=graph-powershell-1.0) and [beta](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.beta.devicemanagement.enrollment/?view=graph-powershell-beta).

**Comment by mark3grahams** [comment]
What about the CMDlet count discrepancy?

**Comment by peombwa** [comment]
The cmdlet count difference between SDK v1.x and v2.x is due to the change mentioned in the breaking change guide at https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/docs/upgrade-to-v2.md#directory-role-and-entitlement-management-commands:
> Directory role and entitlement management commands that were in `DeviceManagement.Enrollment` module have been moved to Identity.Governance to align with the [API reference](https://learn.microsoft.com/graph/api/resources/directoryrole?view=graph-rest-1.0).

**Comment by mark3grahams** [comment]
Thanks for the information

**Comment by peombwa** [comment]
Closing as resolved. Stale docs will be removed by https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/issues/322.
