### ISSUE TITLE
Use RequiredVersion 1.9.2 but download  dependencies with v2.1.0

### ISSUE THREAD

**Issue by yuanweilei** [microsoftgraph/msgraph-sdk-powershell#2164]
I run this command on my local PowerShell to save v1.9.2, but some dependencies with v2.1.0 is downloaded. Could you please tell me why?
Save-Module -Name Microsoft.Graph -RequiredVersion 1.9.2 -Path .\modules

For example, Microsoft.Graph.Applications.
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/26296423/8b4df02e-40e7-47e9-8c79-5b0a477c5f54)

**Comment by peombwa** [comment]
The ability to install older versions of the SDK was added in v1.12.2. All versions prior to v1.12.2 didn't support an exact version match for their dependencies. See v1.12.2 release notes for more details - https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/1.12.2.

Please use the latest version of v1.x (v1.28.0) if your goal is to use v1.x - `Install-Module -Name Microsoft.Graph -RequiredVersion 1.28.0`.

**Comment by yuanweilei** [comment]
@peombwa 
Thank you very much! I will try to use 1.12.2.

Could I ask you another question?
**About 10 days ago (before v2.0.0 release)**, I used the same command but Microsoft.Graph.Applications **v1.9.6** was downloaded. You told me that v1.28.0 is the latest version of v1.x, but why v1.9.6 was downloaded?

Save-Module -Name Microsoft.Graph -RequiredVersion 1.9.2 -Path .\modules

**Comment by peombwa** [comment]
I'd recommend you use v1.28.0 as it is the latest stable release of the v1.x SDK.

As for:
> About 10 days ago (before v2.0.0 release), I used the same command but Microsoft.Graph.Applications v1.9.6 was downloaded. You told me that v1.28.0 is the latest version of v1.x, but why v1.9.6 was downloaded?

> Save-Module -Name Microsoft.Graph -RequiredVersion 1.9.2 -Path .\modules

This is more of a question for the author of the `Save-Module` command. My theory is:
`Save-Module` installs any version of `Microsoft.Graph.Authentication` greater than or equal to 1.9.2 since 1.9.2 is specified as the minimum version. This is because in all versions prior to v1.12.2, the dependency version of `Microsoft.Graph.Authentication` was specified under `ModuleVersion` (>=). This was later changed to `RequiredVersion` (=) in v1.12.2+ to support installation of older versions. See https://learn.microsoft.com/powershell/module/microsoft.powershell.core/about/about_module_manifests?view=powershell-7.3#requiredmodules for more details:
> ModuleVersion - Specifies a minimum acceptable version of the module.
> RequiredVersion - Specifies an exact, required version of the module.

**Comment by yuanweilei** [comment]
@peombwa 
Thank you again. Understood the question above is regarding Save-Module.

I am still confused why Microsoft.Graph -RequiredVersion 1.9.2 got v1.9.6 not the latest v1.28.0, but maybe I should ask this question on PowerShell side.

I just guess, maybe v1.9.6 is the last version of v1.9.z, so it is download. (There are versions of v1.10.0, 1.11.0, ..., v1.28.0 >= v1.9.2)

**Comment by peombwa** [comment]
Awesome! The author of `Save-Module` is the right contact point for the question.

I'll close the issue since the original question has been answered by https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2164#issuecomment-1638898941. Feel free to open a new issue if the problem persists.

**Comment by JeremyTBradshaw** [comment]
Hello, I would like to report that the issue seems to be back again.  I'm using PowerShell core

```powershell
$PSVersionTable                                                                                                                                                                                              ─╯

Name                           Value
----                           -----
PSVersion                      7.6.3
PSEdition                      Core
GitCommitId                    7.6.3
OS                             Microsoft Windows 10.0.26200
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1, 6.0, 7.0}
PSRemotingProtocolVersion      2.4
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Using module versions 5.5.1 (Az.Accounts) and 2.35.1 (Microsoft.Graph.Authentication).

If I use Connect-MgGraph first (import MS Identity client DLL from there first), both are OK, but if I Connect-AzAccount first, Graph module is dead with:

```powershell
authentication failed: Method not found: 'Microsoft.Identity.Client.PublicClientApplicationBuilder......
```
