### ISSUE TITLE
connect-mggraph -accesstoken - error when passing msal access token

### ISSUE THREAD

**Issue by Cagey-One** [microsoftgraph/msgraph-sdk-powershell#2219]
Hi all,

When trying to connect to mggraph using a msal access token I receive an error like below:

Connect-MgGraph : Cannot bind parameter 'AccessToken'. Cannot convert the 'tokeninfo' of type "System.String" to type "System.Security.SecureString".
Connect-MgGraph -AccessToken $msaltoken.accesstoken
+                              ~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Connect-MgGraph], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.Graph.PowerShell.Authentication.Cmdlets.ConnectMgGraph

I have used this configuration in the past and it was working (I assume an update has come through) and now requires a secure string. I have tried converting the string of the access token but ran into issues with the formatting of convertto-securestring.

Sample code that generates the error:
#Generate MSAL token using application credential
$msaltoken = Get-MsalToken -TenantId $TenantId -ClientId $ClientId -ClientSecret $ClientSecret
#connect using msal access token
Connect-MgGraph -AccessToken $msaltoken.accesstoken

Modules:
ModuleType Version    Name
---------- -------    ----                              
Script     4.37.0.0   MSAL.PS
Script     2.1.0      Microsoft.Graph.Authentication

Thanks in advance.

**Comment by SeniorConsulting** [comment]
Hi Cagey-One,

This behaviour was pointed out in the breaking change section, for when you moved between version 1.x of the Graph SDK to 2.x
https://github.com/microsoftgraph/msgraph-sdk-powershell#upgrading-to-v2

What's required now is a SecureString, rather than just a string.

One option may be to use PowerShell's ConvertTo-SecureString to store the access token in.
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.security/convertto-securestring?view=powershell-5.1

**Comment by Cagey-One** [comment]
Thanks for the confirmation @SeniorConsulting I had been working on the convertto-securestring in an attempt to get it to work.

Have now continued testing and found this to work appropriately:
$accesstoken = ConvertTo-SecureString "$($msaltoken.AccessToken)" -AsPlainText -Force

Thanks again.
