### ISSUE TITLE
Missing Get-MgBetaSitePage from latest version

### ISSUE THREAD

**Issue by groveale** [microsoftgraph/msgraph-sdk-powershell#2251]
**Describe the bug**
> Missing `Get-MgBetaSitePage` cmdlet from Microsoft.Graph.Beta.Sites version 2.3.0

**To Reproduce**
1. Execute `$pages = Get-MgBetaSitePage -SiteId $sites[0].Id`
2. See error at `Get-MgBetaSitePage: The term 'Get-MgBetaSitePage' is not recognized as a name of a cmdlet, function, script file, or executable program.`

**Expected behavior**
> This was possible in previous version using  'Get-MgSitePage' but switching to Beta context

**Debug Output**
> N/A

**Module Version**
2.3.0

**Environment Data**
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

The command is missing due to a type change that was made in the beta version of the API ~last week. The API (`/sites/{site-id}/pages`) was moved under `baseSitePage`, which is currently not covered by the SDK - https://learn.microsoft.com/graph/api/basesitepage-list?view=graph-rest-beta&tabs=http. Such API changes can happen in beta without notice as stated in the beta API disclaimer:
> APIs under the /beta version in Microsoft Graph are subject to change. Use of these APIs in production applications is not supported. To determine whether an API is available in v1.0, use the Version selector.

We will add support for `baseSitePage` in the next SDK refresh.
