### ISSUE TITLE
Get-MgBetaDirectoryDeletedItemAsUser needs a parameter for ConsistencyLevel

### ISSUE THREAD

**Issue by SuryenduB** [microsoftgraph/msgraph-sdk-powershell#2256]
Get-MgBetaDirectoryDeletedItemAsUser needs a parameter for ConsistencyLevel
As User object deleted by Azure AD Connect adds additional data for UPN as prefix.

We need to search with ends with filter , which is not possible unless there ConsistencyLevel Header

**Comment by SeniorConsulting** [comment]
Hi SuryenduB,

This looks like a statement of fact. Can you please describe what you had hoped would happen with you raising this new issue?

It would be useful if you could've completed the full template when you raised this ticket, which includes headings such as "Describe the bug", and "Expected behavior"
