### ISSUE TITLE
Connect-Graph Error : Could not load file or assembly 'System.Net.Http'

### ISSUE THREAD

**Issue by KP-GIT** [microsoftgraph/msgraph-sdk-powershell#227]
I want to perform operations using Graph API services, I have installed the relevant powershell module. However when I am running thee command "**Connect-Graph**" it results in error.

Error faced :
 
```
Connect-Graph : Could not load file or assembly 'System.Net.Http, Version=4.1.1.2, 
Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system 
cannot find the file specified.
At line:1 char:1
+ Connect-Graph
+ ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-Graph], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.Graph.PowerShell.Aut 
   hentication.Cmdlets.ConnectGraph
```

I guess that it is not finding the correct version of the assembly, however not sure. Could you please help in identifying the issue as well as its solution.

**Comment by peombwa** [comment]
@KP-GIT Could you share the following details to help us repro this issue:
1. What version of the SDK are using? Run `Get-Module Microsoft.Graph -ListAvailable`.
2. What version of PowerShell are you running? Execute `$PSVersionTable.PSVersion`.
3. If PowerShell Core v6 or greater, what OS are you running?

**Comment by KP-GIT** [comment]
@peombwa I just found somewhere that this might be an issue with .Net Framework version and updating the .Net Framework to 4.8 I am not facing this error. However I am facing a different error now "**Must specify CertificateThumbprint or CertificateName**". I am accessing Graph via an App so I understand I need to provide the Client and Tenant ID, it is asking for certificate as well, is there no other way around the certificate? Maybe instead of Certificate if we use the shared secret?

**Comment by peombwa** [comment]
That's great 🎉

We don't support secrets due to security reasons - one may unintentionally store a secret in a script and check it in to source control. We recommend the use of certificates which can be passed via a `-CertificateThumbprint` or `-CertificateName` to `Connect-Graph` cmdlet.

We will be supporting [managed identities](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview) in the near future. It will solve the security concerns with secrets and credentials. See our authentication roadmap here https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/142#issuecomment-600819834.
