### ISSUE TITLE
Get-MGGroup filter with special characters doesn't work

### ISSUE THREAD

**Issue by fug4zi** [microsoftgraph/msgraph-sdk-powershell#2280]
Hi,

we have a group with a "+" and a "|" char and im unable to filter this group.

I tried to encode the searchstring, but nothing helped. 
The "+" sign can be encoded with %2b, but the "|" char is unsearchable.

So i tried this:
```
$str = "P+R | Workspace"
Get-MgGroup -Filter "displayName eq '$([System.Web.HttpUtility]::UrlDecode($str))'"
```

With Invoke-MgGraphRequest everything is working fine.
```
(Invoke-MgGraphRequest -Uri "https://graph.microsoft.com/v1.0/groups?filter=displayname eq '$([System.Web.HttpUtility]::UrlDecode($str))'").value
```

I'm using Powershell Graph v.2.4.0

**Comment by psignoret** [comment]
@peombwa I came across this issue today as well. I don't think the `|` is the problem, that seems to be encoded fine (e.g. when checking with -Debug). The issue is that `+` always gets replaced with ` ` (space), a problem introduced in #1826, which makes it impossible to filter for the `+` character.

@fug4zi As a temporary work-around while this gets fixed, you could consider using -Search instead of -Filter. This is not an exact match comparison, so you would need to pass the results through an extra client-side filter to remove any unwanted items*:

```powershell
$str = "P+R | Workspace"
Get-MgGroup -Search "displayName:$($str)" -CountVariable c -ConsistencyLevel eventual -All | ? { $_.DisplayName -eq $str }
```

*For example, groups named "P R Workspace", "WorkspaceP|R" would be returned with `-Filter "displayName:P+R | Workspace"`.

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

This is indeed a bug that was introduced by the fix for #1339. The root cause is with how `UrlDecode` class decodes the `+` character. `[System.Web.HttpUtility]::UrlDecode("P+R | Workspace")` replaces the `+` with space `P R | Workspace`.

As a workaround, please use the suggested workaround by Psignoret at https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2280#issuecomment-1712160769 as we investigate the issue:
> $str = "P+R | Workspace"
> Get-MgGroup -Search "displayName:$($str)" -CountVariable c -ConsistencyLevel eventual -All | ? { $_.DisplayName -eq $str }

**Comment by DougChandler** [comment]
What about all the other properties that can be filtered? Are they also fixed? I am seeing the same issue where I cannot filter OnPremisesImmutableID where there is a '+' in the value...
Is it just DisplayName that is fixed?

**Comment by timayabi2020** [comment]
@DougChandler yes they will be fixed by this https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/2361
