### ISSUE TITLE
Using client secret to the connect to the MS graph is not achieving its end goal - transferring from the docs repo

### ISSUE THREAD

**Issue by msewaweru** [microsoftgraph/msgraph-sdk-powershell#2315]
Thanks for reporting the bug. Please ensure you've gone through the following checklist before opening an issue:
- Make sure you can reproduce this issue using the latest released version of [Microsoft.Graph](https://www.powershellgallery.com/packages/Microsoft.Graph) or [Microsoft.Graph.Beta](https://www.powershellgallery.com/packages/Microsoft.Graph.Beta).
- Please search the existing issues to see if there has been a similar issue filed.
- For issues related to authentication and service errors, please refer to our [troubleshooting guide](https://learn.microsoft.com/powershell/microsoftgraph/troubleshooting). For service issues, please open a question at https://developer.microsoft.com/graph/support.

**Describe the bug**
 While I go through the Using client secret credentials part to connect to the MS graph. I observe that you need to enter the secret as the # Enter client_secret in the password prompt.
From this behavior, I feel we didn't reach the end goal of running as a demon service.
So there any way to bypass that prompt

**To Reproduce**
1. Execute `-Mg-` with `...`
2. See error at `...`

**Expected behavior**
> A clear and concise description of what you expected to happen.

**Debug Output**
> Run the problematic command with `-Debug` and paste the resulting debug stream below.
> ⚠ ATTENTION: Be sure to remove any sensitive information that may be in the logs.

**Module Version**
> Please run `Get-Module Microsoft.Graph*` after cmdlet execution and paste the output below.
> If a module cannot be installed or imported, please run `Get-Module -ListAvailable` and paste the output.

**Environment Data**
> Please run `$PSVersionTable` and paste the output below. If running the Docker container image, indicate the tag of the image used and the version of Docker engine.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by SeniorConsulting** [comment]
A method to use this is documented here:
https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/docs/upgrade-to-v2.md#client-secret-credentials

If you're attempting to authenticate with an app registration using a client secret, you'll always need to supply that client secret. However, it's usually not advised to store this in a script. In that sense, it comes down to what you're using to authenticate. For example:
If you're running your script from an Azure Automation Account, you should be able to use an encrypted AutomationVariable, so that when you run your script, you could obtain the client secret using:
`$ClientSecret = Get-AutomationVariable <The name/ID of my variable>`

Alternatively, you could retrieve the secret from an Azure Key Vault.

**Comment by timayabi2020** [comment]
The other alternative is to make use of managed identity. For example, a service instance like cloudshell ships with its own identity. So ```Connect-MgGraph -Identity``` picks the access token from that environment.
