### ISSUE TITLE
Attribute proxyAddresses not accessible to Get-MgUser

### ISSUE THREAD

**Issue by rayksland** [microsoftgraph/msgraph-sdk-powershell#2337]
**Describe the bug**

Querying Entra with -->

$(Get-MgUser -UserId someuser@example.com).proxyAddresses 

returns no data, whereas

the same type of query with Get-MgGroup  -->

$(Get-MgGroup -GroupId 'GROUP-UUID-NUMBER-THING').proxyAddresses 

returns a list of proxyAddresses as expected e.g.

smtp:group-alias2@example.onmicrosoft.com
SMTP:group-alias1@example.com

Have also tried the Get-MgUser query with a 'USER-UUID-NUMBER-THING' because it accepts that too. Same results.

**Debug Output**
DEBUG: [CmdletBeginProcessing]: - Get-MgUser begin processing with parameterSet 'Get'.
DEBUG: [Authentication]: - AuthType: 'AppOnly', TokenCredentialType: 'ClientCertificate', ContextScope: 'Process', AppName: 'Valid_Mail_Addresses'.
DEBUG: [Authentication]: - Scopes: [Group.Read.All, MailboxSettings.Read, User.Read.All].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.microsoft.com/v1.0/users/someuser%40example.com

Headers:
FeatureFlag                   : 00000043
Cache-Control                 : no-store, no-cache
User-Agent                    : Mozilla/5.0,(Linux; Linux 6.1.0 #1 SMP Thu Dec 15 20:31:06 MSK 2022; en-CA),PowerShell/7.3.7
Accept-Encoding               : gzip
SdkVersion                    : graph-powershell/2.6.1
client-request-id             : f99174f7-6fec-4d07-a08f-6e0a8f567a5

Body:

DEBUG: ============================ HTTP RESPONSE ============================

**Module Version**

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.6.1                 Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disc…
Script     2.6.1                 Microsoft.Graph.Groups              {Add-MgGroupDriveListContentTypeCopy, Add…
Script     2.6.1                 Microsoft.Graph.Users               {Get-MgUser, Get-MgUserCount, Get-MgUserC…

**Environment Data**

Name                           Value
----                           -----
PSVersion                      7.3.7
PSEdition                      Core
GitCommitId                    7.3.7
OS                             Linux 6.1.0 #1 SMP Thu Dec 15 20:31:06 MSK 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Additional context**
Just want to do a lookup on all valid email addresses.

**Comment by SeniorConsulting** [comment]
Hi Rayksland,

While proxyAddress [is supported](https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties) by the API, it isn't [returned by default](https://learn.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http#request).

You'll need to try:
Get-MgUser -UserId bob@contoso.com -property UserPrincipalName,proxyAddresses | FT UserPrincipalName,proxyAddresses

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/a7ca66ae-6f4d-49b3-829f-0af7bcafbcd2)

**Comment by rayksland** [comment]
so are GetMgUser and GetMgGroup written by different developers so that they behave slightly differently? (no answer required)

Anyway thanks for that. I don't see why I need the magic of Format-Table to see those addresses, but okay.

**Comment by SeniorConsulting** [comment]
They're not written by different developers, the PowerShell SDK team simply provide a wrapper around what the Graph API provides, so any behaviours present in the API will get pulled through to the PowerShell SDK also.

Regarding the format table, you don't really need to use it, I just wanted to display things nicely on screen so that you could see it would work. Reason being, when you specify the -property parameter you will need to stipulate all the properties you want to return (it generally won't return the other ones by default). So using my example, you'll actually drop seeing displayName, Id, Mail etc if you don't specify it.

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/9a0cb658-005a-41e3-a334-9aa065056c17)

So if I wanted to return proxyAddresses, DisplayName, Id, AND UserPrincipalName, you'd need to do the following:
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/110941550/adb8ceb5-a3b5-4442-96c1-6bbf90e594e3)

Note also in the screenshot above how without specifying Format-Table, proxyAddresses still isn't returned? That's the main reason I included it in my screenshot.

**Comment by ddyett** [comment]
correct, this is only returned with a $select call.

**Comment by rayksland** [comment]
> Note also in the screenshot above how without specifying Format-Table, proxyAddresses still isn't returned? That's the main reason I included it in my screenshot.

Well that's what I meant by magic. I don't really understand why Get-MgUser can't display everything you specify.
Get-MgUser  -property proxyAddresses -all  should give you a list of all proxyAddresses (full stop.) 

Yes I did discover the thing about the $select call... I would think that should be built into Get-MgUser.
