### ISSUE TITLE
Set-MgUserPhotoContent ... documentation ... stream usage

### ISSUE THREAD

**Issue by OtterKring** [microsoftgraph/msgraph-sdk-powershell#2351]
Set-UserPhoto is going to be retired as of Nov 30th 2023 and MS suggests using MSGraph instead. Since I do not want to fumble with REST calls directly, I'd like to use Set-MgUserPhotoContent and found several things that bug me:

1) Will this update the Exchange Online picture? This is what I actually need, since the pic from AzureAD is only synced to EXO once and never again

2) [The documentation for updating the user photo using Graph](https://learn.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&tabs=powershell#example-2-update-the-photo-of-a-team) shows the use of -BodyParameter. But according to the [powershell help page for the command](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.users/set-mguserphotocontent?view=graph-powershell-1.0#syntax), there is no -BodyParameter.

3) **Now the ACTUAL feature request:**
Set-MgUserPhotoContent requires the -Infile parameter, but provides an optional -Data parameter accepting a System.IO.Stream object. The latter would be much more useful for me for syncing my AD pictures to M365, because I could do everything in memory. As it is set up know, I would have to save every single user photo from AD to file and then upload it to M365 from the file again, then erase the file. VERY inconvenient.

**Describe the solution you'd like**
ad 2) please align the documentation so both refer to the same code and verbose on which systems the photo will be updated. There is a hint about it in the documentation for beta API at least. And please also update the powershell help page for the command. There are no examples and the -Data parameter is not described at all.
ad 3) Provide a possibility to use a System.IO.MemoryStream as input, omitting the necessity of using a file.

**Describe alternatives you've considered**
afaik MS does not provide any alternative solutions after November 23rd 2023.

**Additional context**
Here is the actual very limited [information about the retirement of Set-UserPhoto](https://admin.microsoft.com/Adminportal/Home?ref=MessageCenter/:/messages/MC678855).

Thank you!

**Comment by mrmueller** [comment]
Additionally, a parameter accepting binary data would allow us to export photos from MIM without first saving them to a file.

**Comment by AzGuineaPig** [comment]
Same request here - please provide a parameter that uses a Byte[] type, as we're currently leveraging this with the Set-UserPhoto -PictureData parameter.

**Comment by DocJelly** [comment]
I've been playing around with this today and managed to make it work. I have another function that pulls the user photo from our HRIS API and saves it as a byte array (similar to how AD and EXO store them) and was trying to get it into Entra by way of the graph cmdlets.

First, everyone above is right. You HAVE to specify the -inFile parameter even if you're using the -data parameter... but it doesn't seem to do any checking. I put in -infile doesnotexist.txt and and it passed validation and ran the cmdlet, even though the file did not exist. One of those cmdlet constructors should have -inFile optional and -Data mandatory, or something like that.

Here's the syntax I used:
`Set-MgUserPhotoContent -Passthru -InFile nonExistat.lat -UserId someEmail@domain.com -Data ([System.IO.MemoryStream]::new($varContainingByteArray))`

Since I used -Passthru it returned "True" 
This was based on a [comment on this thread on Reddit:](https://www.reddit.com/r/PowerShell/comments/175ol1l/setuserphoto_to_setmguserphotocontent_script/)

I'll also point out that when I tried this "interactively" by using connect-mggraph and signing in as myself, it threw a 403 Forbidden. When I connected using an appid, tenantid and certificate thumbnail (which has user.read.all and user.readwrite.all) then it worked.

**Comment by timayabi2020** [comment]
@OtterKring have you tried @DocJelly's solution?

**Comment by jpawlowski** [comment]
Retrieving the photo from a URL into memory and uploading it afterwards works here this way:

````PowerShell

$UserPhotoUrl = 'https://example.com/User-Default-Photo.png'
Write-Verbose "Retrieving user photo from URL '$($UserPhotoUrl)'"
$null = Invoke-WebRequest `
    -UseBasicParsing `
    -Method GET `
    -Uri $UserPhotoUrl `
    -TimeoutSec 3 `
    -RetryIntervalSec 5 `
    -MaximumRetryCount 3 `
    -OutVariable UserPhoto
if (
    (-Not $UserPhoto) -or
    ($UserPhoto.StatusCode -ne 200) -or
    (-Not $UserPhoto.Content)
) {
    Write-Error "Unable to download photo from URL '$($UserPhotoUrl)'"
    exit 1
}
if (
    ($UserPhoto.Headers.'Content-Type' -ne 'image/png') -and
    ($UserPhoto.Headers.'Content-Type' -ne 'image/jpeg')

) {
    Write-Error "Photo from URL '$($UserPhotoUrl)' must have Content-Type 'image/png' or 'image/jpeg'."
    exit 1
}
Write-Verbose "Updating user photo"
$null = Set-MgUserPhotoContent `
    -InFile nonExistat.lat `
    -UserId $userObj.Id `
    -Data ([System.IO.MemoryStream]::new($UserPhoto.Content))
````

**Comment by celticview1** [comment]
Has there been a change to the cmdlet since the solution above was proposed?

I have tried to use the same process to pass a stream to the Set-MgUserPhotoContent -Data parameter but I get an error every time

"Set-MgUserPhotoContent_Set: Object reference not set to an instance of an object."

I am looking to process a batch of user's thumbnail photos and having to save each one as a jpg file only to then read it back again using Set-MgUserPhotoContent is a real pain and slows the process down hugely.

**Comment by jpawlowski** [comment]
I am not aware of any changes.

As the code above is a simplification of what I am using in my code here, maybe it already helps if you change

````
powershell
$null = Set-MgUserPhotoContent `
    -InFile nonExistat.lat `
    -UserId $userObj.Id `
    -Data ([System.IO.MemoryStream]::new($UserPhoto.Content))
````

to

````
powershell
$null = Set-MgUserPhotoContent `
    -InFile nonExistat.lat `
    -UserId $userObj.Id `
    -Data $([System.IO.MemoryStream]::new($UserPhoto.Content))
`````

(note the `$(...)` instead of `(...)` for the `-Data` parameter.

**Comment by jpawlowski** [comment]
Indeed, this does no longer work.

I think it's better to avoid using `Set-MgUserPhotoContent` and use the Graph API directly like this:

````powershell
$params = @{
    UseBasicParsing = $true
    Method          = 'GET'
    Uri             = 'https://example.com/User-Default-Photo.png'
    TimeoutSec      = 10
    ErrorAction     = 'SilentlyContinue'
}
$UserPhoto = Invoke-WebRequest @params

if (
    (-Not $UserPhoto) -or
    ($UserPhoto.StatusCode -ne 200) -or
    (-Not $UserPhoto.Content)
) {
    Write-Error "Unable to download photo from URL '$($params.Uri)'"
    exit 1
}

if (
    ($UserPhoto.Headers.'Content-Type' -ne 'image/png') -and
    ($UserPhoto.Headers.'Content-Type' -ne 'image/jpeg')

) {
    Write-Error "Photo from URL '$($UserPhotoUrl)' must have Content-Type 'image/png' or 'image/jpeg'."
    exit 1
}

Write-Verbose "Updating user photo"
$params = @{
    Method      = 'PUT'
    Uri         = "https://graph.microsoft.com/v1.0/users/$($UserObj.Id)/photo/`$value"
    Body        = $UserPhoto.Content
    ContentType = [string]$UserPhoto.Headers.'Content-Type'
    ErrorAction = 'Stop'
}
Invoke-MgGraphRequest @params
````

**Comment by Celticview** [comment]
Hi, 

Thanks for checking that, That was the conclusion I came to as well.

I am also using the Invoke-MgGraphRequest method you showed above and this seems to work correctly for my specific requirements.

I think think this is just as good a solution as trying to use the specific cmdlet for this purpose.

**Comment by OtterKring** [comment]
> [@OtterKring](https://github.com/OtterKring) have you tried [@DocJelly](https://github.com/DocJelly)'s solution?

Sorry, I completely forgot about this request and found it again today by googling for the same topic, hoping to find that something has changed. 🙈
Thanks to all the commenting folks who posted viable solutions. I can confirm that the "Set-MgUserPhotoContent_Set: Object reference not set to an instance of an object." error still exist in the Microsoft.Graph module version 2.25.0. Haven't tried the InvokeWebRequest solution. My script runs stable creating and deleting several hundred temp files twice a day. Not pretty, but it works.
Fun fact: the -Data parameter still exists, its description in the official documentation, however, only consists of a dot. Typical Graph style documentation, I'd say. 🙄
