### ISSUE TITLE
Get-MgUserMailFolder does not list all folders in the mailbox

### ISSUE THREAD

**Issue by Deas-h** [microsoftgraph/msgraph-sdk-powershell#2357]
Graph API is 2.7.0

I am quite sure this is not a bug report, but I am unable to find the right solution...

When I use Get-MgUserMailFolder it does not list all folders in the mailbox. Sure, not all are mail folders, but I am missing Tasks, Journal, Calendar, Contacts and Notes for example in the output.

How can I get those folders and - this links to my other issue - set the folder attribute IsHidden?

**Comment by peombwa** [comment]
Are the folders hidden? If so, you'll need to use includeHiddenFolders query parameter (`-Includehiddenfolders` in PowerShell). Otherwise, please note that the API does only returns the child folders of the root folder by default and each child folder will have to be traversed separately. See API reference doc at https://learn.microsoft.com/graph/api/user-list-mailfolders for more details:
> By default, this operation does not return hidden folders. Use a query parameter includeHiddenFolders to include them in the response. This operation does not return all mail folders in a mailbox, only the child folders of the root folder. To return all mail folders in a mailbox, each child folder must be [traversed separately](https://learn.microsoft.com/en-us/graph/api/mailfolder-list-childfolders?view=graph-rest-1.0).
