### ISSUE TITLE
Get-MgUserPhotoContent does not return what was set using Set-MgUserPhotoContent

### ISSUE THREAD

**Issue by mrmueller** [microsoftgraph/msgraph-sdk-powershell#2389]
**Describe the bug**
> When using Set-MgUserPhotoContent and then Get-MgUserPhotoContent, the returned value is not the same as was set using Set-MgUserPhotoContent. I assume the image is compressed.

**To Reproduce**
Set-MgUserPhotoContent -infile C:\Temp\photoIn.jpg
Get-MgUserPhotoContent -outfile C:\Temp\photoOut.jpg

**Expected behavior**
I would expect the two files to be identical

**Debug Output**
not applicable

**Module Version**
2.8.0

**Environment Data**
Name                           Value
----                           -----
PSVersion                      5.1.19041.3570
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3570
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Additional context**
This is important for tools syncing photos. MIM for example. MIM performs a "confirming import" to check if the correct value was set in the target system.

**Comment by peombwa** [comment]
Thanks for following up on this.

Could you clarify what you mean by `"the returned value is not the same as was set using Set-MgUserPhotoContent"`. Do you mean a difference in the size of the uploaded and downloaded image? If so, this is probably due to compression by the service and https://developer.microsoft.com/graph/support is the recommended place to ask API questions.

Per my testing, the API returns the uploaded image with the original resolution in a smaller size (properly due to compression by the service).

**Comment by mrmueller** [comment]
Yes, downloaded image looks to be compressed.
Will close this and post an API question
