### ISSUE TITLE
Get-MgTeam without -TeamId does not return all property values.

### ISSUE THREAD

**Issue by anthonyherring** [microsoftgraph/msgraph-sdk-powershell#2423]
When using Get-MgTeam without supplying a -TeamId, values for some properties are not returned, such as CreatedDateTime and IsArchived. Supplying -All or -Top with or without -Property and specifying property names is no help; still no values returned.

When supplying a -TeamId, the property values are returned for the specific Team.

**Comment by timayabi2020** [comment]
@anthonyherring  please refer to the note section on this reference https://learn.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-1.0&tabs=http. This is by design that some of properties are not being returned.

![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/10947120/29db476e-3fe3-401f-83da-3cdd65346739)
