### ISSUE TITLE
New-MgServicePrincipal Missing the PublisherName Parameter

### ISSUE THREAD

**Issue by NikCharlebois** [microsoftgraph/msgraph-sdk-powershell#2520]
**Describe the bug**
We are facing an issue where it seems like the New-MgServicePrincipal cmdlet no longer supports the -PublisherName property. This used to work at some point, and is even listed as and accepted parameter in our documentation:
 
[New-MgBetaServicePrincipal (Microsoft.Graph.Beta.Applications) | Microsoft Learn](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.beta.applications/new-mgbetaserviceprincipal?view=graph-powershell-beta#-publishername)

**To Reproduce**
1 - Run the New-MgServicePrincipal cmdlet with the -PublisherName property

**Expected behavior**
The property is accepted and set.

**Debug Output**
* N/A

**Module Version**
2.11.1

**Environment Data**
5.1

**Screenshots**
* N/A

**Comment by timayabi2020** [comment]
Hi @NikCharlebois,
I checked the properties supported by the API from the [API reference doc](https://learn.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0) and the publisherName property (which transalates to ``-PublisherName``) is missing.  I am not best placed to give a reason why it was removed; therefore, I request that you raise an issue here https://developer.microsoft.com/en-us/graph/support so that the API owner can respond to it.

If you check the offline documentation ``Get-Help New-MgServicePrincipal  -Detail`` you'll realize that the parameter has not been listed. I have created another issue [here](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/issues/463) on the online docs repository to have the list of supported parameters updated.
