### ISSUE TITLE
Urgent: Make response headers optional 

### ISSUE THREAD

**Issue by CarolKigoonya** [microsoftgraph/msgraph-sdk-powershell#2600]
Provide a parameter e.g. -rhv v when you want to access response headers instead of returning 2 objects (which is a breaking change to customers).

**Comment by pbo-top** [comment]
Sample of breaking-change we have hit since we picked up the 2.14.0 version in automated scripts during this weekend (was working with 2.13.1).

$entApp = Get-MgServicePrincipal -Filter "AppId eq '$($app.application_id)'"

When a given application_id was not found in 2.13.1 the function returned $null, which we were checking for, now the function returns a System.Collections.Hashtable with something like this, aka far from null.

x-ms-ags-diagnostic {"ServerInfo":{"DataCenter":"West Europe","Slice":"E","Ring":"5","ScaleUnit":"002","RoleInstance":"AM2PEPF0000BE1A"}} 
OData-Version 4.0 
Transfer-Encoding chunked 
request-id f89fc6e7-9bea-4c62-a66a-82df45259498 
Vary Accept-Encoding 
Strict-Transport-Security max-age=31536000 
client-request-id fc3fb26e-51ba-4c8e-a83c-30070d92bfc7 
Date Mon, 19 Feb 2024 10:27:19 GMT 
x-ms-resource-unit 1 
Cache-Control no-cache

**Comment by skellyatsnhu** [comment]
Similarly, this cmdlet returns a pile of blank data (which is should never do) whereas before it would correctly filter things out:

```
Get-ADUser -Filter 'enabled -eq $true' |ForEach-Object{get-mguser -userid $_.userprincipalname -Property UserPrincipalName,otherMails,CreatedDateTime|Select-Object userprincipalname,OtherMails,CreatedDateTime}|Where-Object{!$_.OtherMails}
```

Do you have an ETA on a fix?

**Comment by BohrenAn** [comment]
Same Issue as documented here:
https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2584

**Comment by CarolKigoonya** [comment]
We have a new version out to address the issue. https://www.powershellgallery.com/packages/Microsoft.Graph/2.14.1. Apologies to everyone for inconveniences caused on the previous version.
