### ISSUE TITLE
Newtonsoft.Json.dll in Microsoft Graph PowerShell SDK Package is not signed

### ISSUE THREAD

**Issue by g2mula** [microsoftgraph/msgraph-sdk-powershell#2741]
### Describe the bug

I am trying to use Microsoft Graph Powershell SDK in a production environment
This causes a Sev2 to be raised due to unsigned binaries.

[- AzSysLock Alert -] [- CI -] The ‘\Device\HarddiskVolume3\Users\TheUser.MachineName\Documents\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\2.18.0\Dependencies\Desktop\Newtonsoft.Json.dll’ binary file / script violated code sign policy but was not blocked (audited only)

https://portal.microsofticm.com/imp/v3/incidents/incident/498622566/summary

### Expected behavior

Installation should complete without raising any Sev2

### How to reproduce

Install-Module Microsoft.Graph

### SDK Version

2.18.0

### Known Workarounds

None

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by petrhollayms** [comment]
The Newtonsoft.Json.dll file our MS Graph PowerShell SDK is using (version 13.0.3 in SDK v2.19) is signed and the issue is not with the lack of the signature but with the signature not being trusted by the Windows Server 2019 environment.

Here is how to check the certificate of the DLL file:

1. Download the 13.0.3 (the latest) package we're using,[NuGet Gallery | Newtonsoft.Json 13.0.3](https://www.nuget.org/packages/Newtonsoft.Json/13.0.3)
2. Extract \lib\netstandard2.0\Newtonsoft.Json.dll
3. Open file properties and check the certificate in the VM to see if is it shown as valid or not
4. Do the same for the root certificate in the chain which is "DigiCert CS RSA4096 Root G5".

We're exploring several options to mitigate the issue now.

**Comment by petrhollayms** [comment]
After some more testing in the affected environment with @g2mula , we came to the conclusion that it was one-time issue that we were unable to reproduce.

The ultimate solution will be to replace the Netonsoft.Json parser by System.Text.Json, https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0
