### ISSUE TITLE
Find-MgGraphCommand by permission type does not work for delegated permission type

### ISSUE THREAD

**Issue by CarolKigoonya** [microsoftgraph/msgraph-sdk-powershell#2860]
### Describe the bug

Find permissions by permission type using Find-MgGraphCommand -Command "Get-MgApplication" | Select-Object -ExpandProperty Permissions | Where-Object { $_.PermissionType -eq "Application" }

### Expected behavior

Show permissions for the command by permission type

### How to reproduce

Find-MgGraphCommand -Command "Get-MgApplication" | Select-Object -ExpandProperty Permissions | Where-Object { $_.PermissionType -eq "Delegated" }

![Screenshot (651)](https://github.com/user-attachments/assets/90b60771-247e-4b87-b741-45bbe472e29a)
![Screenshot (652)](https://github.com/user-attachments/assets/006459a6-4203-40af-ae1b-7bfff98d60ec)

### SDK Version

2.19 and 2.20

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by timayabi2020** [comment]
@CarolKigoonya please try using the ``-like`` operator. e.g ``Find-MgGraphCommand -Command "Get-MgApplication" | Select-Object -ExpandProperty Permissions | Where-Object { $_.PermissionType -like "Delegated*" } |select Name, PermissionType`` since delegated permission type is either DelegatedPersonal or DelegatedWork.
<img width="849" alt="image" src="https://github.com/user-attachments/assets/fe4a9159-3975-484b-9b83-ea42a9fdb452">

**Comment by CarolKigoonya** [comment]
That works. Thanks Tim
