### ISSUE TITLE
Please add the missing "Update-MgEntitlementManagementAssignmentPolicy" cmdlet in Microsoft.Graph.Identity.Governance

### ISSUE THREAD

**Issue by Horgster** [microsoftgraph/msgraph-sdk-powershell#2956]
### Is your feature request related to a problem? Please describe the problem.

Hello!

I need to have the possibility to update (add / remove / modify) the SpecificAllowedTargets in the assignment policy of an access package. 

If this cmdlet is not added to this module due to that it is expected that we shall use "Set-MgEntitlementManagementAssignmentPolicy", this this cmdlet must be fixed as it simply destroys and empties the assignment policies when using the "-SpecificAllowedTargets" parameter.

### Describe the solution you'd like.

Please include "Update-MgEntitlementManagementAssignmentPolicy" cmdlet. 

This cmdlet should allow you to modify any configuration parameters of an assignment policy with parameters switches, representing the configuration item that you want to modify.

Example;
If I would like to update the list of Allowed Specified Targets connected domains";

Update-MgEntitlementManagementAssignmentPolicy -AccessPackageAssignmentPolicyId <GUID> -SpecificAllowedTargets @(Array of #microsoft.graph.connectedOrganizationMembers)

ref;
https://learn.microsoft.com/en-us/graph/api/resources/connectedorganizationmembers?view=graph-rest-1.0

**Comment by timayabi2020** [comment]
Hi @Horgster thank you for logging this issue. However as per the Api documentation here https://learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-1.0&tabs=http the API owner hasn't availed a ``PATCH`` operation for the service, instead a ``PUT`` operation has been defined and that's why we generate ``Set-MgEntitlementManagementAssignmentPolicy`` as the equivalent cmdlet. Unfortunately for API related issues/questions we are not best placed to give an answer. Kindly raise an issue here https://developer.microsoft.com/en-us/graph/support so that the API owner can respond to it.
