### ISSUE TITLE
Microsoft.Graph.Reports - Get-MgReportTeamUserActivityCount

### ISSUE THREAD

**Issue by JohanssonMarkus** [microsoftgraph/msgraph-sdk-powershell#407]
Get-MgReportTeamUserActivityCount -Period "D7" Give an error 

PS H:\> Get-MgReportTeamUserActivityCount -Period "D7"
Get-MgReportTeamUserActivityCount : Expected '{' or '['. Was String: Report.
At line:1 char:1
+ Get-MgReportTeamUserActivityCount -Period "D7"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgReportTeamUserActivityCount_Get1], ParserException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgReportTeamUserActivityCount_Get1 
[AB#7395](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7395)

**Comment by MIchaelMainer** [comment]
This is a known issue where the metadata describes this as JSON and the response is csv.

**Comment by JohanssonMarkus** [comment]
@MIchaelMainer  Ok good to know, when will it be solved?

**Comment by MIchaelMainer** [comment]
We don't have this scheduled yet on our side, and I'm unaware what the story is on the server side for this API set. This scenario requires the use of [Invoke-GraphRequest](https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/245) for now.

**Comment by joshtransient** [comment]
Also adding that the cmdlets in Microsoft.Graph.Reports fail when the file specified by -OutFile doesn't already exist.

**Comment by darrelmiller** [comment]
I was able to repro this issue:

```
C:\src\msgraph-sdk-powershell [dev ≡ +4 ~2 -0 !]> Get-MgReportTeamDeviceUsageUserCount -Period "D7" -OutFile report.txt
Get-MgReportTeamDeviceUsageUserCount_Get: Cannot find path 'C:\src\msgraph-sdk-powershell\report.txt' because it does not exist.
```

**Comment by finsharp** [comment]
@JohanssonMarkus 
A workaround for now would be to use `Invoke-MgGraphRequest` 
The following options:- 

`-InferOutputFileName` - Infer the output file name and store it in the current directory.
 `
Connect-Graph -Scopes @("Reports.Read.All") 
Invoke-MgGraphRequest -Uri "https://graph.microsoft.com/v1.0/reports/getTeamsUserActivityUserDetail(period='D7')" -InferOutputFileName
`
![image](https://user-images.githubusercontent.com/1641829/106495633-03d07b00-64cd-11eb-9ff8-c18b04c17f47.png)

`-OutputFilePath` specify the name of the output file. 
`Invoke-MgGraphRequest -Uri "https://graph.microsoft.com/v1.0/reports/getTeamsUserActivityUserDetail(period='D7')" -OutputFilePath report.csv
`
![image](https://user-images.githubusercontent.com/1641829/106495857-41350880-64cd-11eb-853d-7cbf48ecbbf5.png)

**Comment by peombwa** [comment]
The [OpenAPI document](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/openApiDocs/v1.0/Reports.yml#L3326) currently represents the content-type of this response as `application/json` instead of `application/octet-stream`. To solve this, we need to ensure that all content-types of report functions are accurately represented in the converted OpenAPI. Without this, code generators won't be able to know how to properly handle responses.

### Currently
This in CSDL:
![image](https://user-images.githubusercontent.com/7061532/115089355-e9e8e680-9ec6-11eb-928f-cc163f94b912.png)
![image](https://user-images.githubusercontent.com/7061532/115089908-413b8680-9ec8-11eb-9e86-4f75303c3ce3.png)

Gets converted to this in OpenAPI:
![image](https://user-images.githubusercontent.com/7061532/115088029-31ba3e80-9ec4-11eb-84a9-7da833767b20.png)

### Expected
For the cmldet to function as described in [MS Graph docs](https://docs.microsoft.com/en-us/graph/api/reportroot-getteamsuseractivitycounts?view=graph-rest-1.0#response), we need to ensure that the response is describes as shown below:
![image](https://user-images.githubusercontent.com/7061532/115088128-60d0b000-9ec4-11eb-8914-12dfba509f2d.png)

cc\ @ddyett , @darrelmiller: Should we address this in the metadata or let DevX API handle it.

**Comment by chenxizhang** [comment]
some error here, do we have plan to fix the issue?

![image](https://user-images.githubusercontent.com/1996954/116563430-9949a280-a936-11eb-83ab-1fa000f16bd4.png)

**Comment by peombwa** [comment]
This is being tracked here https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/552 and will be fixed via XSLT transform.

**Comment by weyCC81** [comment]
This is still happening with Module "Microsoft.Graph" at Version "1.7.0", please fix

**Comment by maisarissi** [comment]
Hi @silijon . We have been working with other teams to get this fixed.
As you can see [here](https://github.com/microsoft/OpenAPI.NET.OData/issues/200) the team managed to fix and now we are just waiting for the next version release to be out so we can validate on our side.
Once we get this done, we will update and close this issue.
