### ISSUE TITLE
Get-mgplace returns 406 (not acceptaple)

### ISSUE THREAD

**Issue by Michael19842** [microsoftgraph/msgraph-sdk-powershell#423]
Get-mgplace returns 406 (not acceptaple)  
[AB#7400](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7400)

**Comment by Michael19842** [comment]
Get-MgPlace : The server responded with a Request Error, Status: NotAcceptable
At line:1 char:1
+ Get-MgPlace -Verbose
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Top = , Skip ...ndProperty =  }:<>f__AnonymousType15`8) [Get-MgPlace_List], RestException`1
    + FullyQualifiedErrorId : UnknownError,Microsoft.Graph.PowerShell.Cmdlets.GetMgPlace_List

**Comment by Michael19842** [comment]
Get-MgPlace : The server responded with a Request Error, Status: NotAcceptable
At line:1 char:1
+ Get-MgPlace -Verbose
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Top = , Skip ...ndProperty =  }:<>f__AnonymousType15`8) [Get-MgPlace_List], RestException`1
    + FullyQualifiedErrorId : UnknownError,Microsoft.Graph.PowerShell.Cmdlets.GetMgPlace_List

**Comment by Michael19842** [comment]
Get-MgPlace : The server responded with a Request Error, Status: NotAcceptable
At line:1 char:1
+ Get-MgPlace -Top 10 -Debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Top = 10, Ski...ndProperty =  }:<>f__AnonymousType15`8) [Get-MgPlace_List], RestException`1
    + FullyQualifiedErrorId : UnknownError,Microsoft.Graph.PowerShell.Cmdlets.GetMgPlace_List
DEBUG: HTTP/1.1 406 Not Acceptable
request-id: ac13c32f-f9ab-4914-b6ac-9005f37e8f2a
client-request-id: ac13c32f-f9ab-4914-b6ac-9005f37e8f2a
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceC","Ring":"5","ScaleUnit":"003","RoleInstance":"AGSFE_IN_33"}}
Strict-Transport-Security: max-age=31536000
Cache-Control: private
Date: Thu, 08 Oct 2020 15:15:20 GMT
Content-Length: 266
Content-Type: application/json

**Comment by ddyett** [comment]
i think you need a placeId such as microsoft.graph.room to get back some information. get-mgplace -placeid microosft.graph.room.  places itself is abstract.  @peombwa everything seems to be ending up in additionalproperties.

**Comment by peombwa** [comment]
This is because in the [OpenAPI doc](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/po/InternalFeeds/openApiDocs/v1.0/Places.yml#L158-L161), `/places/{place-id}` returns a single `microsoft.graph.place` entity and not a collection.

We should consider adding room type parameter to `/places` or generate paths for all room types (OData cast).

**Comment by NunoFilipeMota** [comment]
Any development on this? I'm also getting the _NotAcceptable_ error and can't find a way of getting all Places/Meeting Rooms using the SDK and the Get-MgPlace command... Thank you!

**Comment by Michael19842** [comment]
Seems to be dead :S

**Comment by jetedoff** [comment]
Pinging this thread again, is there any code fixing happening for *-MgPlace? I can't steer customers away from Azure PowerShell and tell them to adopt Graph PowerShell if the code doesn't work, yet documentation says to do just that.

**Comment by peombwa** [comment]
Fixed by https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/2.0.0-rc1.

OData cast support was added to V2 of the SDK via `Get-Mg*As<DerivedType>` convention. Please use, ` Get-MgPlaceAsRoom` to get a collection of places as rooms:
<img width="612" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/7061532/f7d8dbd7-be63-46e2-85a1-2a95567e38f3">
