### ISSUE TITLE
Set $top to -Top Value with -All Parameter

### ISSUE THREAD

**Issue by ryanspletzer** [microsoftgraph/msgraph-sdk-powershell#457]
I noticed via tracing with Fiddler that using `-All` does pagination with `$top=100` and that if you additionally add the `-Top 999` parameter it still uses `$top=100` in the request.

Is `$top=100` the most efficient pagination amount for `-All`? I would think that grabbing more results per page would be more efficient... (Maybe I'm wrong, though.) Regardless of that, would it be possible to have the cmdlets set `$top` accordingly when `-Top` is specified with `-All`?

**Comment by ryanspletzer** [comment]
To add to this, I think `-All` should probably use `$top=999` by default all the time (where `$top` is supported for the resource). For example, if I do pagination on a group's members for a large group of about 4k users using `$top=999` it cuts off a significant chunk of time compared to `$top=100`.

**Comment by KirkMunro** [comment]
@ryanspletzer: There is a `-PageSize` parameter for this purpose. e.g. `Get-MgUser -All -PageSize 999`. Does that not work like you expect?

I think the current parameter set definition is a little off with both `-Top` and `-All` being defined in the same parameter set. Ideally it wouldn't be possible to use `-Top` with `-All`, because from a usability perspective, even though both might use `$top` behind the scenes, the two use cases really are different.

**Comment by ryanspletzer** [comment]
Thanks @KirkMunro that works! Had no noticed the `-PageSize` param. :)
