### ISSUE TITLE
Why does the property Contacts in Get-MgUser always return null?

### ISSUE THREAD

**Issue by sulligogs** [microsoftgraph/msgraph-sdk-powershell#464]
In PowerShell I want to list the personal contacts of a user using Graph API.

`$user=Get-MgUser -UserId "test1@mydomain.com" -Property * | Select *;$user.Contacts`

The contacts are there in Outlook and OWA, but show as empty (null) in PowerShell. My script is using every "most privilege" permission available (81 in fact) under Application Permissions in Azure AD and all show as having admin consent. The script connects to the graph using a client certificate and Mg-Context shows it's connected as AppOnly.

Even properties like AccountEnabled and CreatedDateTime return the same, but the common ones like Id and UserPrincipalName return proper values.

Can anybody give any advice?

**Comment by peombwa** [comment]
@sulligogs This is by design from the API. See the API [doc page](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http).

To get additional properties outside the default ones, you'll need to use `-Property {Property-Names}` parameter. e.g. 
``` powershell
 $user = Get-MgUser -UserId "test1@mydomain.com" -Property Id, DisplayName, AccountEnabled, CreatedDateTime
```

You should use ` Get-MgUserContact -UserId {User-Id}` to get a user's contacts since contacts is a non-expandable property. We will remove non expandable properties form response objects in #89.

**Comment by sulligogs** [comment]
Hi peombwa

My bad I can now see with some Get-Command all the cmdlets containing the word "contacts" and there's plenty of them, including the one you specified.  I will remember to specify exactly the properties I want too.

Thank you very much!
