### ISSUE TITLE
[FEATURE] Get-MgTeams By Team Name

### ISSUE THREAD

**Issue by YuriySamorodov** [microsoftgraph/msgraph-sdk-powershell#506]
It would be great to have an option getting Team in Teams with `Get-MgTEam` by Team name to avoid extra step enumerating groups first. 
[AB#7695](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7695)

**Comment by peombwa** [comment]
This is possible today by calling `Get-MgGroup` with a `-Filter` like this:
``` powershell
Get-MgGroup -Filter "StartsWith(DisplayName, '$TeamName') and ResourceProvisioningOptions/any(c:c eq 'Team')"
```
See https://docs.microsoft.com/en-us/graph/teams-list-all-teams?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#get-a-list-of-groups-using-beta-apis.

I would suggest you open a feature request for the service team at https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests. After you post the feature request, please add a link in this issue so that other folks can find your feature request.

**Comment by YuriySamorodov** [comment]
Thanks @peombwa
