### ISSUE TITLE
Connect-MgGraph: -AccessToken ParameterSet Issues (dead parameters, silent failures, etc.)

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/msgraph-sdk-powershell#510]
Issues found while developing https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/509

- [ ] `-TenantId` parameter does nothing, it still just uses the tenant specified in the JWT accesstoken
- [ ] Should do a simple test such as `/me` to verify the token is valid and immediately throw error if not. Doesn't seem to error until attempted to be used once.
- [ ] Silently fails if token is invalid, doesn't even try to check it according to fiddler trace, should test and throw error.
- [ ] `-ForceRefresh` does nothing (it can't because no refresh token is included) and should be removed from parameterset
- [ ] `-Environment` does nothing 
- [ ] `-ContextScope CurrentUser` does not seem to work, it doesn't preserve for the current user, starting a new process bails on it
[AB#7711](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7711)

**Comment by finsharp** [comment]
@JustinGrote We execute a `/me` request https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/4d3d126735895606519b01a07721b2cbb8e85bd5/src/Authentication/Authentication/Cmdlets/ConnectMgGraph.cs#L226

Looking into the other issues.

**Comment by peombwa** [comment]
@JustinGrote I agree with you that `TenantId`, `ForceRefresh` and `ContextScope` should not be in the same parameter set as `-AccessToken`.  We will remove them in our next release.

 `-Environment` on the hand should be present in all parameter sets since it's used to specify which [national cloud](https://docs.microsoft.com/en-us/graph/deployments) one wants to connect to. This still holds true for situations in which one uses `-AccessToken` since access tokens are issued by a specific national authority (Azure AD endpoint). You can use `Get-MgEnvironment` to see the default set of environments the SDK ships with.

We cannot rely on making a call to `/me` to validate a token since one can set an access token that's meant for calling graph without a user (application calls) thus resulting in an error even though the token is valid. This starts getting complicated once you start considering scopes etc. The best we could do is check the expiration of the access token and throw an error is it has expired or right a warning if it will expire in less than 10 minutes.

**Comment by JustinGrote** [comment]
Thank you for the investigation, I'd say the commit to remove the other parameters in the parameterset can close this issue.
