### ISSUE TITLE
[FEATURE] Get-MgSubscribedSku Friendly Name

### ISSUE THREAD

**Issue by YuriySamorodov** [microsoftgraph/msgraph-sdk-powershell#514]
For now the only properties I get when executing `Get-MgSubscribedSku` are:

- AppliesTo
- CapabilityStatus
- ConsumedUnits
- PrepaidUnits
- ServicePlans
- SkuId
- SkuPartNumber

I must admit this is per documentation:
https://docs.microsoft.com/en-us/graph/api/subscribedsku-list?view=graph-rest-1.0&tabs=http

However, it would be great to have `Get-MgSubscribedSku` shiow Friendly Name for:

- SKU
- ServicePlan

As it can be seen in Azure Portal:
![image](https://user-images.githubusercontent.com/5260172/105553162-fc171680-5d15-11eb-9ba0-e87fbe88ee70.png)

 
[AB#7730](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7730)

**Comment by peombwa** [comment]
This a great feature request for the service team. I would suggest you open a feature request at https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests. After you post the feature request, please add a link in this issue so that other folks can find your feature request and upvote.

As an SDK, we try to represent the data from the service as is to maintain data integrity.

**Comment by YuriySamorodov** [comment]
Thanks @peombwa !
I have posted idea as per your request: https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/42557332-get-mgsubscribedsku-friendlyname
On a side not: it looks like https://microsoftgraph.uservoice.com has a weirdlogin issue - I was not able to authenticate using my federated gmail/live.com account

**Comment by peombwa** [comment]
Great! Here is another related request https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/41878498-add-friendlyname-to-subscribedskus-endpoint.
