### ISSUE TITLE
Get-MgUserLicenseDetail -All requires UserId.

### ISSUE THREAD

**Issue by stvpwrs** [microsoftgraph/msgraph-sdk-powershell#548]
The `Get-MgUserLicenseDetail` Cmd-let with the `-All` argument does not return all users, but asks for a `userId` argument.

Expected behavior:

`Get-MgUserLicenseDetail -All:$true` should return license details for all users. Instead it returns:

```
Supply values for the following parameters:
UserId: 
``` 
[AB#8041](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8041)

**Comment by peombwa** [comment]
This is by design. The API requires a userId inorder to retreive user's license details https://docs.microsoft.com/en-us/graph/api/user-list-licensedetails?view=graph-rest-1.0&tabs=http.

**Comment by stvpwrs** [comment]
Should -All be a switch for the cmdlet then?

**Comment by peombwa** [comment]
`-All` is needed because you are getting a [collection of license details](https://docs.microsoft.com/en-us/graph/api/user-list-licensedetails?view=graph-rest-1.0&tabs=http#response) for a user (`-UserId`). `-All` simply instructs the command to handle paging for you by following `@odata.nextLink` that's returned by the service, see https://docs.microsoft.com/en-us/graph/paging. User's license details can span multiple pages.

You can run `Get-MgUserLicenseDetail -UserId $UserId -All -Debug` to see how the command is handling paging.
