### ISSUE TITLE
Get-MgGroupPlanner 'You do not have the required permissions to access this item.'

### ISSUE THREAD

**Issue by mattgrif** [microsoftgraph/msgraph-sdk-powershell#624]
While running Get-MgGroupPlanner receiving the error 'You do not have the required permissions to access this item.'

AuthType: Delegated
Scopes: Chat.ReadWrite, Directory.Read.All, Group.Read.All, Group.ReadWrite.All, Mail.ReadWrite, openid, People.Read, profile, Sites.Manage.All, Tasks.Read, Tasks.ReadWrite, User.Read, User.ReadWrite.All, email 
[AB#9024](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9024)

**Comment by peombwa** [comment]
From my testing, this happens when you use `Get-MgGroupPlanner` on group that the signed in user is not a `memberOf`. You can use `Get-MgUserMemberOf -UserId $UserId | select Id, AdditionalProperties` to list all groups that a user is a `memberOf`. Alternatively, you can use ` Get-MgGroupMember -GroupId $GroupId | select id, AdditionalProperties` to list member of the group. See https://docs.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-1.0#microsoft-365-groups

**Comment by mattgrif** [comment]
As a global admin, is there a way to query what Planners (if any) are owned by a Group, without being a member of every group?

**Comment by peombwa** [comment]
This is a service limitation, and I can see there is an [existing feature request](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/application-permissions-for-planner-apis/idi-p/2266449) for it. I'd recommend you upvote on it as that will get more visibility from the service team to implement.

**Comment by peombwa** [comment]
Closing as this is not actionable by the SDK. An existing service feature request already exists at https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/application-permissions-for-planner-apis/idi-p/2266449. Please upvote on it!
