### ISSUE TITLE
Get-MgDeviceManagementDeviceCompliancePolicyDeviceScheduledToRetire not recognized

### ISSUE THREAD

**Issue by Lebrack** [microsoftgraph/msgraph-sdk-powershell#639]
This CMDLET is listed by "get-command -Module Microsoft.Graph.*"
But not recognized if you run it. Is this a know issue?
v6.1907.1.0 Microsoft.Graph.Intune 
[AB#9150](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9150)

**Comment by peombwa** [comment]
@Lebrack This happens when you haven't selected beta profile. By default, the SDK loads Microsoft Graph v1.0 commands. You can change this by using `Select-MgProfile beta`, see https://docs.microsoft.com/en-us/graph/powershell/get-started?view=graph-rest-1.0#api-version.

I'll add this to the known issues section.

**Comment by Lebrack** [comment]
Thanks for clarify it. It´s working now.
