### ISSUE TITLE
Support for Client Secret

### ISSUE THREAD

**Issue by RobinDadswell** [microsoftgraph/msgraph-sdk-powershell#686]
I can see that you have certificate based authentication allowed but is it possible to have the ability to use ClientSecret as part of the authentication methods - this is available when authenticating an app against Microsoft Graph normally so would be super handy for use in PowerShell 
[AB#9818](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9818)

**Comment by peombwa** [comment]
We do not support client secrets due to security reasons such as; unintentionally adding a secret to a script and committing it to a public repo. This is also what [MSAL recommends](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-credential-flows#credentials) when it comes to production apps. I'd suggest you use a certificate instead.

We also have plans to support [managed identities](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview) which will resolve the security concerns with secrets and credentials. See our authentication roadmap here https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/142#issuecomment-600819834.

**Comment by RobinDadswell** [comment]
Agree that other methods should be used, I don't have an issue with that approach!
