### ISSUE TITLE
Microsoft.Graph Module Slow to Load

### ISSUE THREAD

**Issue by bpurchell** [microsoftgraph/msgraph-sdk-powershell#688]
I've looked around for an answer but haven't come across anything, so wanted to ask here. I'm getting started with the Microsoft.Graph PS SDK. When I load the module it takes up to 2 minutes to load, is this normal? Can it get sped up, am I doing something wrong? I also get these warnings:

```
WARNING: Selected Microsoft Graph profile 'v1.0' does not exist for module 'Microsoft.Graph.Compliance'. No cmdlets
were loaded.

WARNING: Selected Microsoft Graph profile 'v1.0' does not exist for module 'Microsoft.Graph.Financials'. No cmdlets
were loaded.

WARNING: Selected Microsoft Graph profile 'v1.0' does not exist for module 'Microsoft.Graph.Bookings'. No cmdlets were
loaded.
```

This occurs on W10, Server 2016, and macOS.

**Comment by villeodell** [comment]
I am seeing a similar issue.

```
PS C:\Windows\system32> Import-Module Microsoft.Graph
WARNING: Selected Microsoft Graph profile 'v1.0' does not exist for module 'Microsoft.Graph.Compliance'. No cmdlets were loaded.
WARNING: Selected Microsoft Graph profile 'v1.0' does not exist for module 'Microsoft.Graph.Financials'. No cmdlets were loaded.
WARNING: Selected Microsoft Graph profile 'v1.0' does not exist for module 'Microsoft.Graph.Bookings'. No cmdlets were loaded.
```

```
PS C:\Windows\system32> Connect-MgGraph -Scopes "User.Read.All","Group.ReadWrite.All"
Connect-MgGraph : Device code terminal timed-out after 120 seconds. Please try again.
At line:1 char:1
+ Connect-MgGraph -Scopes "User.Read.All","Group.ReadWrite.All"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-MgGraph], Exception
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Authentication.Cmdlets.ConnectMgGraph
```

**Comment by georgend** [comment]
@villeodell Some modules are only available in `beta`, Compliance, Financials and Bookings are only available in beta.
- **Compliance** -> https://docs.microsoft.com/en-us/graph/api/resources/complianceapioverview?view=graph-rest-beta&viewFallbackFrom=graph-rest-1.0
- **Financials** -> https://docs.microsoft.com/en-us/graph/api/resources/dynamics-graph-reference?view=graph-rest-beta
- **Bookings** -> https://docs.microsoft.com/en-us/graph/api/resources/booking-api-overview?view=graph-rest-beta
To get access to these beta modules please change your profile to beta using ` Select-MgProfile beta`

@bpurchell To speed up your process, consider *only* installing the modules you need instead of the whole meta module.
https://www.powershellgallery.com/packages/Microsoft.Graph.Bookings/1.6.0
https://www.powershellgallery.com/packages/Microsoft.Graph.Financials/1.6.0
https://www.powershellgallery.com/packages/Microsoft.Graph.Compliance/1.6.0

**Comment by dkattan** [comment]
I'd really love to see this improved. I run this module in contrained language mode and I preload the modules in the InitialSessionState. When I call runspace.Open() it takes forever. When I procmon the process it appears to be attempting to load the same dependent DLLs over and over and over. It takes an eternity.

I wish the methods were all exposed by the DLL instead of having hundreds of wrapper functions.

**Comment by schindld** [comment]
Please reopen this issue. It's a major annoyance. I get a similar slow load when importing the Microsoft.Graph.Identity.Governance module.

**Comment by CoolDadTx** [comment]
Just ran across this as well and it isn't even `Import-Module`.  This code causes the stall as well.

```powershell
#Requires -Modules Microsoft.Graph
```

It is so bad that it is faster to call `Get-InstalledModule` to confirm it is available and then just call the graph function you want.

**Comment by S-dn-Y** [comment]
Hey Guys,

Wondering why this got closed?
I like the MgGraph module but trying to fall back on the API now since like @schindld says loading Microsoft.Graph.Identity.Governance takes ages (2 minutes in my development environment, 1 minute on a laptop that's doing nothing).

When I have a script open that uses any MgGraph command in VS Code the PowerShell extension crashes non-stop because it likely tries to loads stuff in the background and other PowerShell windows have issues loading as well until the background process finishes (PowerShell 5.1).

Any suggestions?

Thanks.
Best regards,
Sidney
