### ISSUE TITLE
Manifest files are ignoring PowerShell best practices

### ISSUE THREAD

**Issue by KirkMunro** [microsoftgraph/msgraph-sdk-powershell#76]
In PowerShell, when you create a module manifest, you should _not_ use a wildcard for any of the `*ToExport` fields. The reason for this is simply for performance: when you use a wildcard, PowerShell needs to look deeper to see what cmdlets/functions/aliases are in the module. Instead, as a best practice, modules must identify the commands that they export in the appropriate `*ToExport` field.

This is clearly documented in manifests generated using `New-ModuleManifest` in the comments immediately preceding these fields. For example, I just copied this from one of the Graph module manifests:

> \# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.

For the Graph beta module bundle, there are a few mistakes here:
1. For any command types that are not exported by a module, those values must be set to an empty array.

    e.g. `FunctionsToExport = @()`

1. For any command types that are exported by a module, those values must be set correctly.

    Today, almost all command names are being written to the `CmdletsToExport` fields of manifests, yet all commands that are exported from Graph modules except for `Connect-Graph` and `Disconnect-Graph` are _functions_, so the `FunctionsToExport` field should be where those command names are written.

**Comment by darrelmiller** [comment]
Hey @KirkMunro thanks for the feedback.  

@peombwa Is this something that we control or something that AutoREST generates for us?

**Comment by joeyaiello** [comment]
Just came over to file this one, was pleased to see @KirkMunro beat me to the punch. :) 

@darrelmiller: the big deal here is any of these being set to a wildcard. As the Graph modules grow in scope, this problem will continue to get worse. And unfortunately, due to the nature of module auto-loading, this impacts the performance of users who have the Graph modules installed even when they don't have it loaded.

If you need any more context, feel free to reach out

**Comment by darrelmiller** [comment]
@joeyaiello I see someone from the AutoREST team put the issue on their Feb milestone so we should automatically get this fixed when we update.  Feel free to head over to the [issue](https://github.com/Azure/autorest.powershell/issues/556) and add some weight to the request :-)  It will help all the new Azure modules too.

**Comment by darrelmiller** [comment]
@peombwa The FunctionsToExport is being rendered as a wildcard still.  See here https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/src/Beta/Groups.Drive/Groups.Drive/Microsoft.Graph.Groups.Drive.psd1#L71

**Comment by peombwa** [comment]
@darrelmiller, 0.2.1 fixed it. Azure devops didn't update the branch since it is a generated file. https://www.powershellgallery.com/packages/Microsoft.Graph.Groups.Drive/0.2.1/Content/Microsoft.Graph.Groups.Drive.psd1

I'll update the pipeline to sync the generated files back to dev branch when working on https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/139

**Comment by KirkMunro** [comment]
@darrelmiller @peombwa This is only partially fixed. `AliasesToExport` is still assigned to '*'. None of the `ToExport` manifest entries should be assigned a wildcard value. They all must be present, and they should be assigned an explicitly defined array or an empty array. Can we please get this reopened and get the `AliasesToExport` issue addressed as well?
