### ISSUE TITLE
getting  error on Remove-MgChatMessage  

### ISSUE THREAD

**Issue by Tovishal2002** [microsoftgraph/msgraph-sdk-powershell#767]
Get-MgChatMessage -ChatId "***********@unq.gbl.spaces" -ChatMessageId "1****304" is working perfectly fine ,but when try to execute Remove-MgChatMessage -ChatId "***********@unq.gbl.spaces" -ChatMessageId "1****304" throwing error "**Remove-MgChatMessage : The server responded with a Request Error, Status: NotFound**"

please advise. 
[AB#10237](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10237)

**Comment by georgend** [comment]
@Tovishal2002 
Kindly share Debug logs, by passing `-Debug` parameter to the failing command. This will help us triage and understand the issue.

**Comment by peombwa** [comment]
@Tovishal2002 Deleting a chat message [isn't supported by the API](https://docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0). `Remove-MgChatMessage` is generated because the metadata isn't appropriately annotated to tell us whether or not a delete operation is supported. We will remove this command in our subsequent releases.

I'd recommend you upvote on this existing feature request for the service owners to add this - https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/ability-to-delete-a-chat-via-the-api/idi-p/2396576
