### ISSUE TITLE
PIM URIs need to updated to new management paths

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/msgraph-sdk-powershell#777]
The API has been split into aadRoles and azure roles and new commands for both need to be generated.

For example:
/beta/privilegedAccess/test/roleAssignments

Is now 
/beta/privilegedAccess/aadRoles/test/RoleAssignments 

https://docs.microsoft.com/en-us/azure/active-directory/privileged-identity-management/powershell-for-azure-ad-roles
[AB#10370](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10370)

**Comment by janegilring** [comment]
Any updates on this issue?

**Comment by peombwa** [comment]
@janegilring, the old PIM APIs have since been deprecated. Please follow the migration guide at https://docs.microsoft.com/en-us/graph/api/resources/privilegedidentitymanagement-root?view=graph-rest-beta#migrate-from-pim-v2-to-pim-v3-apis to use the new commands/APIs.

@JustinGrote, this isn't what the service metadata describes (https://graph.microsoft.com/beta/$metadata). We use the metadata as the single source of truth for the commands that we generate:
``` xml
<EntityType Name="privilegedAccess" BaseType="graph.entity">
  <Property Name="displayName" Type="Edm.String" />
  <NavigationProperty Name="resources" Type="Collection(graph.governanceResource)" ContainsTarget="true" />
  <NavigationProperty Name="roleAssignmentRequests" Type="Collection(graph.governanceRoleAssignmentRequest)" ContainsTarget="true" />
  <NavigationProperty Name="roleAssignments" Type="Collection(graph.governanceRoleAssignment)" ContainsTarget="true" />
  <NavigationProperty Name="roleDefinitions" Type="Collection(graph.governanceRoleDefinition)" ContainsTarget="true" />
  <NavigationProperty Name="roleSettings" Type="Collection(graph.governanceRoleSetting)" ContainsTarget="true" />
</EntityType>
```
Also, the link you provided is for AzureAD Graph API and not Microsoft Graph API.

**Comment by JustinGrote** [comment]
@peombwa thanks for the review, this issue was opened nearly a year ago so things have changed since then, it was valid at that time...
