### ISSUE TITLE
$select not supported by Cloud PC Endpoint

### ISSUE THREAD

**Issue by georgend** [microsoftgraph/msgraph-sdk-powershell#800]
Executing `Get-MgDeviceManagementVirtualEndpointAuditEvent -Property Actor` returns the full result set instead of only the `Actor` property. 
This generates `https://graph.microsoft.com/beta/deviceManagement/virtualEndpoint/auditEvents?$select=actor` which when executed always returns the full result set. The service does not seem to support `$select`.
 
[AB#10507](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10507)

**Comment by peombwa** [comment]
@georgend, this is a service issue and is also mentioned in the API known issues - https://docs.microsoft.com/en-us/graph/known-issues?context=graph%2Fapi%2Fbeta&view=graph-rest-beta#query-parameter-limitations.
> Query parameters specified in a request might fail silently. This can be true for unsupported query parameters as well as for unsupported combinations of query parameters.

As an SDK, there is little that we can do to address this since `-Property` accepts `<String[]>` and the metadata isn't fully annotated with `SelectSupport` annotation - https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Capabilities.V1.xml#L319.

It would be nice if the workload team could add $select support; this is considered a known issue until then.

**Comment by georgend** [comment]
Yes, I have informed them, they have acknowledged.
