### ISSUE TITLE
Odd naming of various DeviceManagement cmdlets

### ISSUE THREAD

**Issue by hstrang** [microsoftgraph/msgraph-sdk-powershell#867]
Various cmdlets under DeviceManagement are named according to the related platforms like Android and MacOS, but then there is a large set named "Window" instead of "Window**s**" although these are referring to the Windows operating system and the underlying Graph API calls and all related objects are named *Windows*. Maybe there is some higher logic behind this decision but it appears very odd and is very confusing.

**Comment by peombwa** [comment]
Thanks for surfacing this. Our code-gen singularizes all words that make up a command to be compliant with PowerShell's naming convention. This has the limitation of singularizing everything, including product names. We will fix this when we move to v2 of the SDK since renaming this now would result in a breaking change for customers who have taken a dependency on existing commands.

In the meantime, we will alias `*-Mg*Window*` commands to `*-Mg*Windows*` to address this.

**Comment by peombwa** [comment]
Fixed by #1573.
