### ISSUE TITLE
Need to to supress Update-MgEntitlementManagementAccessPackageAssignmentPolicy cmdlet

### ISSUE THREAD

**Issue by vikama-microsoft** [microsoftgraph/msgraph-sdk-powershell#870]
Currently ELM does not support patch of this API and seem like the auto generator of this cmdlets generated using PATCH ,c an you please help to suppress this cmdlet.
https://www.powershellgallery.com/packages/Microsoft.Graph.Identity.Governance/1.7.0

**Comment by KaiWalter** [comment]
What does "suppress this cmdlet" imply? Take it away? In my scenario I actually need this kind of operation / cmdlet to update obsolete policy assignment policies.

**Comment by peombwa** [comment]
The command should be updated to use `PUT` instead of `PATCH` as described in the [API reference docs](https://docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&tabs=csharp).

Related to #714 and will be fixed by https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/607.

**Comment by magichappens89** [comment]
Any updates on this? The fact that this cmdlet uses the wrong method makes it quite useless. Although app and job exists there is no way around the error:
`Update-MgServicePrincipalSynchronizationJobSchema : {"Message":"No HTTP resource was found that matches the request URI 'https://syncfabric.windowsazure.com/api/serv
icePrincipals('[PrincipalObjectId]')/synchronization/jobs('[SyncronizationJobId]')/schema?api
-version=2.0'."}`
