### ISSUE TITLE
Investigate how to map key names when pipelining input object.s

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-powershell#90]
Instead of having to do this:

`get-GroupMember -GroupId $groupid | % { write-output @{ UserId=$_.id } } | get-user`

we should be able to do this,

`get-GroupMember -GroupId $groupid | get-user`

**Comment by alexandair** [comment]
This particular cmdlet (Get-MgGroupMember) should not even need a pipeline to give us the info about group members. ATM, it outputs only IDs. That's not good enough. That's not what users expect.

Here is an other example when pipeline should just work:
`Get-MgUser -UserId <someuserid> | Get-MgUserPresence`

That pipeline doesn't work right now because of two reasons:
1. `-InputObject` accepts pipeline input `ByValue` expecting `IUsersUserIdentity` type. `Get-MgUser` returns an object of `Microsoft.Graph.PowerShell.Models.MicrosoftGraphUser` type. Types don't match and pipeline doesn't work.

2. Pipeline could work if you've implemented pipeline support `ByPropertyName` for `UserId` parameter in `Get-MgUserPresence`. Then we could do:
```
Get-MgUser -UserId <someuserid> | select @{n="UserId";e={$_.Id}} | Get-MgUserPresence
```

However, that's not optimal either, because we need to manually fix the problem that object's property name and parameter name in the receiving cmdlet are not the same. The right way to deal with this kind of a problem is to add `UserId` *AliasProperty* to the object that `Get-MgUser` returns.

**Comment by dolauli** [comment]
1. Please find sample for adding alias for a parameter in https://github.com/Azure/autorest.powershell/blob/master/docs/directives.md#Parameter-Aliasing
2. If you seek for pipeline support that is not implemented in the generator, you may do it by adding a parameter set through customization. And for how to add parameter set, you may find some samples in https://github.com/Azure/autorest.powershell/blob/master/docs/customization.md.
