### ISSUE TITLE
Get-MgTeamChannelTabTeamApp - not working

### ISSUE THREAD

**Issue by cweste82** [microsoftgraph/msgraph-sdk-powershell#909]
Hey together,

today I wanted to access the tabApp information from a specific teams Team

via the graphAPI i can use the following call:

https://graph.microsoft.com/v1.0/teams/5e9c2b75-xxxx-4b8e-b2f8-7448740878fc/channels/19:19180194f33c47cfb9cdade3cb2xxxxx@thread.tacv2/tabs?$expand=teamsApp

And get the result I wanted to have 

But compared the the powershell SDK

I use
Get-MgTeamChannelTabTeamApp -TeamId 5e9c2b75-xxxx-4b8e-b2f8-7448740878fc -ChannelId 19:19180194f33c47cfb9cdade3cb2cxxxx@thread.tacv2 -TeamsTabId 2f4abffe-f334-4759-b672-77e2525cxxxx

But I constantly got the error

Get-MgTeamChannelTabTeamApp : 404 page not found

Would be nice if someone could check if it's a problem on my side or if it's a bug in the SDK

Thx for the feedback 

Chris

**Comment by peombwa** [comment]
What you are looking for is shown below since you are expandig the relationship via `?$expand=teamsApp`:
``` powershell
Import-Module Microsoft.Graph.Teams

Get-MgTeamChannelTab -TeamId $teamId -ChannelId $channelId -ExpandProperty "teamsApp" 
```

- `Get-MgTeamChannelTabTeamApp` calls `/teams/{team-id}/channels/{channel-id}/tabs/{teamsTab-id}/teamsApp`
- `Get-MgTeamChannelTab -ExpandProperty "teamsApp"` calls `/teams/{team-id}/channels/{channel-id}/tabs?$expand=teamsApp`
