### ISSUE TITLE
Issues connecting to Graph with GCCH tenant

### ISSUE THREAD

**Issue by ranoichman** [microsoftgraph/msgraph-sdk-powershell#981]
When connecting to Graph via the powershell module, I can open the MFA login window simply by calling Connect-mggraph. This will allow me to login successfully, but only if I am a commercial tenant user. If I am a GCCH or GCCH DOD user, I need to provide the -Environment parameter with the appropriate environment I want to log in to.
My issue is that we are utilizing the login window in code, and I have no way of knowing what user will attempt to authenticate. Therefor when I try to login with a GCCH user to the regular call - I fail (with an incoherent error message if I might add).
The old AzureAD module didn't have that issue, and I expect the new module to not have it as well as currently to be able to workaround this issue I need to perform a nasty try-cacth, and if I fail I attempt to login to GCCH, if fail attempt to login to DoD.
There has got to to be a better solution then that. Can you please assist?

**Comment by peombwa** [comment]
There is no way for us to know ahead of time which environment/national cloud you intend to connect to. The old AzureAD module was pre-authorized to connect to any tenant/cloud without consent. This is not recommended from a security point of view.

A solution for you would be to add a [proxy function](https://devblogs.microsoft.com/scripting/proxy-functions-spice-up-your-powershell-core-cmdlets) that calls `Connect-MgGraph` with a pre-configured environment. This will allow you to abstract our generic implementation with your environment/cloud-specific configuration. Your customers will then use your proxy function to authenticate to MS Graph.

Here is an example of a module that calls `Connect-MgGraph` in a proxy function - https://github.com/microsoft/Microsoft365DSC/blob/322baf8acf87dfa2619c996587c99a4a7cedefe1/Modules/Microsoft365DSC/Modules/M365DSCPermissions.psm1#L123.

**Comment by ranoichman** [comment]
Hi Peter,

I reviewed your suggestion and didn't fully understand it as the examples
provided are irrelevant for our use case.
We need to call Connect-MgGraph and for it to open the login window, as I
mentioned, at this stage I don't know what user or password the user will
enter and therefore I can't anticipate and prepare the Tenant as you
suggested.

As per Microsoft documentation, this PowerShell module is the recommended
module and the replacement for the soon deprecated AzureAD which did
support this flow. I therefore expect the replacer to enhance the user
experience, not reduce it.

How can you assist?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ranoichman** [comment]
Any info on this?

**Comment by peombwa** [comment]
Hi @ranoichman, there is no mechanism available for us to "auto-discover" which cloud/environment a user intends to use. This is by design since national/air-gapped clouds are [designed to be isolated from global cloud](https://docs.microsoft.com/en-us/graph/deployments). A try-catch is also not viable since Microsoft Graph supports well-known national clouds and air-gapped clouds (user-defined). Since you are working with a couple of national clouds (GCCH and GCCH DOD), you could write a try-catch in a proxy function to do this on your end.

All [Microsoft SDKs](https://github.com/microsoft/Federal-Business-Applications/tree/main/demos/powershell-gov-samples#teams) require that a customer specifies the name of the cloud/environment they intend to connect to before authenticating. What AzureAD had was a security bug and not a feature. We cannot implement a feature that will make customers vulnerable to security risks.

Your solutions here are:
- Ask your users to specify `-Environment` parameter when connecting to Microsoft Graph as per our [official guidance](https://github.com/microsoft/Federal-Business-Applications/tree/main/demos/powershell-gov-samples#microsoft-graph-powershell).
- Write a proxy function that calls `Connect-MgGraph` with try-catch for GCCH and GCCH DOD. Your customers will then use this proxy function to authenticate to Microsoft Graph.
- Write a proxy function that calls `Connect-MgGraph` with a predetermined `-Environment`. This assumes that your customers will only connect to one environment.

cc\ @maisarissi

**Comment by ranoichman** [comment]
Hi Peter,

I understand your point, but the problem with the proxy function (which I
wrote) is that the try catch in it works, but makes for a poor UI as the
user needs to enter its credentials over and over again until the right
catch for the right environment is triggered.
How can I avoid this without opening the login windows over and over again?

**Comment by maisarissi** [comment]
Hi @ranoichman .

If you can't know which Environment you should be using based on a user, unfortunately, you can't avoid this behavior unless you pre-ask, before calling Graph, which environment the user wants to connect.

> there is no mechanism available for us to "auto-discover" which cloud/environment a user intends to use. This is by design since national/air-gapped clouds are [designed to be isolated from global cloud](https://docs.microsoft.com/en-us/graph/deployments)

As @peombwa pointed out before, this behavior is by design. Every time someone tries to connect to Graph a request is made for a different server and there is no way to redirect your call unless you make a new one. And every time a user needs to connect to Graph, they need to provide credentials for security reasons.  
![image](https://user-images.githubusercontent.com/22648831/155805238-93c6f0f7-4dfe-4a0c-bbda-77f226b9dce8.png)

Check this [PR](https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/425) for more details.

I'm closing as it isn't actionable on our side.
